import { SUPPORTED_LOCALES, type SupportedLocale } from "~/utils/locales";

const messages = {
  en: {
    "nav.world": "World", "nav.features": "Features", "nav.devlogs": "Devlogs", "nav.vision": "Vision", "nav.faq": "FAQ", "nav.changelog": "Changelog", "nav.feedback": "Feedback", "nav.roadmap": "Roadmap", "nav.wishlist": "Wishlist", "nav.wishlistSteam": "Wishlist on Steam", "nav.menu": "Menu", "nav.openMenu": "Open menu", "nav.more": "More", "nav.language": "Change language", "nav.primary": "Primary", "nav.mobile": "Mobile", "nav.footer": "Footer", "nav.home": "Elegon home",
    "hero.live": "Open playtest live 24/7 on Steam", "hero.tagline": "An MMORPG inspired by the classics", "hero.description": "Step into a world where your progression matters and adventure awaits.", "hero.community": "Join the Community", "hero.begin": "Begin your journey", "hero.platforms": "Available platforms",
    "seo.title": "Elegon: A Classic-Inspired Indie MMORPG", "seo.description": "A solo-developed MMORPG inspired by the classics. Earned progression, a living open world, and no pay-to-win. Join the free 24/7 playtest on Steam.",
    "footer.description": "A classic-inspired MMORPG, built in the open by a solo developer. Earned progression, a living world, and never a cash shop.", "footer.game": "The Game", "footer.community": "Community", "footer.shape": "Shape Elegon", "footer.world": "The World", "footer.vision": "The Vision", "footer.feedback": "Feedback Board", "footer.rights": "Solo-developed with passion. All rights reserved.", "footer.london": "Forged in London",
    "changelog.title": "Changelog & Patch Notes", "changelog.description": "Every Elegon patch note in one place: the latest fixes, improvements and new features added to the MMORPG's 24/7 Steam playtest.", "changelog.today": "Today", "changelog.yesterday": "Yesterday", "changelog.daysAgo": "days ago",
    "world.eyebrow": "Welcome, traveller", "world.title": "Not the Chosen One", "world.intro": "Hey, I'm Keone, a solo developer building Elegon. I started this project because I've always loved this genre, but truly compelling online worlds that respect players' time and effort have become harder to find.", "world.identity": "Elegon is an always-online, open-world MMORPG where you are not the chosen hero, but one small part of a much larger story.", "world.adventure": "Grow stronger over time, defeat powerful enemies, make friends, and stand against the evils of the world in pursuit of its greatest rewards.", "world.playtest": "Elegon is being developed in the open. Join the 24/7 Steam playtest and help shape the game with your feedback. After version 1.0, development will continue as the world expands and evolves.", "world.nowOpen": "Now open", "world.playtestLabel": "24/7 Steam Playtest", "world.noP2w": "No pay-to-win. Ever.", "world.statPlaytest": "Open playtest on Steam", "world.statDevlogs": "Weekly devlogs on YouTube", "world.weekly": "Weekly", "world.statShop": "Items in a cash shop", "world.statPlatforms": "Platforms: Windows, Linux & macOS",
    "features.eyebrow": "Forge your legend", "features.title": "What Awaits in Elegon", "features.intro": "A world inspired by the MMORPGs that defined the genre, built for players who want their time to mean something.", "features.p1.tag": "Progression", "features.p1.title": "Progression That's Earned", "features.p1.text": "Grow stronger through time, effort and adventure. Unlock class spells as you level and shape your character with talents.", "features.p2.tag": "Exploration", "features.p2.title": "An Always-Online World", "features.p2.text": "Explore a persistent open world shared with other players, with new zones and world bosses added as it grows.", "features.p3.tag": "Challenge", "features.p3.title": "Breaches & Rare Loot", "features.p3.text": "Take on instanced breaches and face their final bosses for a chance at the world's rarest rewards, including mounts.", "features.p4.tag": "Social", "features.p4.title": "Adventure Together", "features.p4.text": "Make friends, form a party and stand against the world's evils side by side. Some foes aren't meant to be faced alone.", "features.p5.tag": "Discovery", "features.p5.title": "The Compendium", "features.p5.text": "Chronicle everything you uncover on your journey and chase the final percentage of total discoveries.", "features.p6.tag": "Fair play", "features.p6.title": "Fair by Design", "features.p6.text": "One simple subscription. No in-game cash shop, no cosmetics for sale and never any pay-to-win.",
    "devlogs.eyebrow": "From the forge", "devlogs.title": "Weekly Devlogs", "devlogs.p1": "Subscribe to the YouTube channel to follow Elegon's development through weekly updates and behind-the-scenes videos about the game's progress.", "devlogs.p2": "Building Elegon openly with the community matters to me. Your feedback and ideas help shape the game, and these updates keep you close to the world as it grows.", "devlogs.subscribe": "Subscribe on YouTube", "devlogs.changelog": "Read the changelog",
    "vision.eyebrow": "Why Elegon exists", "vision.title": "The Vision", "vision.quote": "Progression in Elegon is designed to feel earned.", "vision.credit": "Keone, creator of Elegon", "vision.pillar": "Pillar", "vision.p1.title": "The Spirit of the Classics", "vision.p1.text": "Elegon aims to create an online world inspired by classic MMORPGs such as early World of Warcraft and other foundational RPGs. These games created worlds that felt meaningful, social, and rewarding to explore. Elegon brings that feeling back while thoughtfully embracing modern ideas where they improve the experience.", "vision.p2.title": "Earned, Never Bought", "vision.p2.text": "Your character grows stronger through time, effort, and adventure, not purchases. There will never be an in-game cash shop selling cosmetics or pay-to-win items. A simple monthly subscription will support development and keep the focus on the world and player experience.", "vision.p3.title": "A World Built to Last", "vision.p3.text": "Elegon is a long-term passion project: a living world that will continue to grow and evolve for years. My goal as a solo developer is to build a world players can invest in, return to, and feel part of.",
    "updates.eyebrow": "Chronicles of development", "updates.title": "Latest Updates", "updates.intro": "Elegon is built in the open and updated constantly. Here's what has landed in the world most recently.", "updates.shipped": "Changes shipped", "updates.since": "since", "updates.viewAll": "View full changelog", "updates.latest": "Latest",
    "supporters.eyebrow": "Hall of heroes", "supporters.title": "Patreon Supporters", "supporters.intro": "Elegon is made possible by the generosity of these adventurers. Their names are etched into the history of the world.", "supporters.loading": "Summoning supporters…", "supporters.hero": "hero", "supporters.heroes": "heroes", "supporters.become": "Become a Supporter", "supporters.legendary": "Legendary Supporters", "supporters.epic": "Epic Supporters", "supporters.rare": "Rare Supporters",
    "faq.eyebrow": "Tavern talk", "faq.title": "Frequently Asked Questions", "faq.more": "Still have questions?", "faq.discordText": "Pull up a chair in the Discord. Ask anything, share ideas, and meet fellow adventurers.", "faq.join": "Join the Discord", "faq.q1": "How will Elegon be monetized?", "faq.a1": "Elegon will be supported by a single monthly subscription. There will never be an in-game store selling cosmetics or pay-to-win items. Purchases outside the subscription may include merchandise, never anything that exists inside the world of Elegon.", "faq.q2": "What platforms is Elegon available on?", "faq.a2": "Elegon can be played through Steam on Windows, Linux, and macOS. The macOS version currently needs a small workaround because the app is not code-signed yet; this will be addressed in the future.", "faq.q3": "Who are you? Have you built anything like this before?", "faq.a3": "I'm Keone, a software developer based in London, UK. I work full-time outside games and develop Elegon in my free time. I have around 10 years of software development experience, and Elegon is my first large-scale game project.", "faq.q4": "What technology does Elegon use?", "faq.a4": "Elegon is built with the Godot game engine, which is open source, flexible, and capable of supporting the project. Elegon uses SpacetimeDB for networking and backend systems, a high-performance modern platform suited to persistent online worlds.", "faq.q5": "How can I support the development of Elegon?", "faq.a5": "Your support is appreciated but never required. You can support the project on Patreon or Ko-fi. Watching devlogs, joining the playtest, and sharing feedback also help enormously.", "faq.q6": "Can I make videos, streams, or articles about Elegon?", "faq.a6": "Absolutely! You're very welcome to create content around Elegon, including YouTube videos, livestreams, articles, and more. No permission is needed, and I'd love to see what you make, so feel free to share it in the Discord.",
    "cta.eyebrow": "The journey begins", "cta.title": "Your Adventure Awaits", "cta.text": "Add Elegon to your Steam wishlist, join the 24/7 playtest, and help shape a world built to last.", "cta.wishlist": "Wishlist on Steam", "cta.discord": "Join the Discord", "footer.engine": "Built with Godot & SpacetimeDB",
  },
  de: {
    "nav.world": "Welt", "nav.features": "Features", "nav.devlogs": "Entwicklerblogs", "nav.vision": "Vision", "nav.faq": "FAQ", "nav.changelog": "Änderungsprotokoll", "nav.feedback": "Feedback", "nav.roadmap": "Roadmap", "nav.wishlist": "Wunschliste", "nav.wishlistSteam": "Auf Steam wünschen", "nav.menu": "Menü", "nav.openMenu": "Menü öffnen", "nav.more": "Mehr", "nav.language": "Sprache ändern", "nav.primary": "Hauptnavigation", "nav.mobile": "Mobilnavigation", "nav.footer": "Footer", "nav.home": "Elegon-Startseite",
    "hero.live": "Offener Playtest rund um die Uhr auf Steam", "hero.tagline": "Ein von Klassikern inspiriertes MMORPG", "hero.description": "Betritt eine Welt, in der dein Fortschritt zählt und Abenteuer auf dich warten.", "hero.community": "Der Community beitreten", "hero.begin": "Beginne deine Reise", "hero.platforms": "Verfügbare Plattformen",
    "seo.title": "Elegon: Ein von Klassikern inspiriertes Indie-MMORPG", "seo.description": "Ein von einem Solo-Entwickler geschaffenes MMORPG, inspiriert von den Klassikern. Verdienter Fortschritt, eine lebendige offene Welt und kein Pay-to-win. Spiele den kostenlosen 24/7-Playtest auf Steam.",
    "footer.description": "Ein von Klassikern inspiriertes MMORPG, offen entwickelt von einem Solo-Entwickler. Verdienter Fortschritt, eine lebendige Welt und kein Cash-Shop.", "footer.game": "Das Spiel", "footer.community": "Community", "footer.shape": "Gestalte Elegon", "footer.world": "Die Welt", "footer.vision": "Die Vision", "footer.feedback": "Feedback-Board", "footer.rights": "Mit Leidenschaft solo entwickelt. Alle Rechte vorbehalten.", "footer.london": "Geschmiedet in London",
    "changelog.title": "Änderungsprotokoll & Patchnotizen", "changelog.description": "Alle Elegon-Patchnotizen an einem Ort: die neuesten Fehlerbehebungen, Verbesserungen und Funktionen aus dem 24/7-Steam-Playtest.", "changelog.today": "Heute", "changelog.yesterday": "Gestern", "changelog.daysAgo": "Tage her", "world.weekly": "Wöchentlich",
    "world.eyebrow": "Willkommen, Reisender", "world.title": "Nicht der Auserwählte", "world.intro": "Hallo, ich bin Keone und entwickle Elegon allein. Ich habe dieses Projekt begonnen, weil ich das Genre liebe. Doch Online-Welten, die wirklich fesseln und die Zeit und Mühe ihrer Spieler respektieren, sind seltener geworden.", "world.identity": "Elegon ist ein dauerhaft online verfügbares Open-World-MMORPG. Du bist nicht der auserwählte Held, sondern ein kleiner Teil einer viel größeren Geschichte.", "world.adventure": "Werde mit der Zeit stärker, besiege mächtige Gegner, finde Freunde und stelle dich den Mächten des Bösen, um die größten Belohnungen der Welt zu erringen.", "world.playtest": "Elegon entsteht öffentlich. Spiele beim rund um die Uhr verfügbaren Steam-Playtest mit und gestalte das Spiel mit deinem Feedback. Auch nach Version 1.0 wird die Welt weiterwachsen und sich entwickeln.", "world.nowOpen": "Jetzt geöffnet", "world.playtestLabel": "Steam-Playtest rund um die Uhr", "world.noP2w": "Kein Pay-to-win. Niemals.", "world.statPlaytest": "Offener Playtest auf Steam", "world.statDevlogs": "Wöchentliche Devlogs auf YouTube", "world.statShop": "Artikel im Echtgeld-Shop", "world.statPlatforms": "Plattformen: Windows, Linux & macOS",
    "features.eyebrow": "Schmiede deine Legende", "features.title": "Das erwartet dich in Elegon", "features.intro": "Eine Welt, inspiriert von den MMORPGs, die das Genre geprägt haben – für Spieler, deren Zeit etwas bedeuten soll.", "features.p1.tag": "Fortschritt", "features.p1.title": "Fortschritt, den du dir verdienst", "features.p1.text": "Werde durch Zeit, Einsatz und Abenteuer stärker. Schalte beim Stufenaufstieg Klassenzauber frei und forme deinen Charakter mit Talenten.", "features.p2.tag": "Erkundung", "features.p2.title": "Eine dauerhaft lebendige Welt", "features.p2.text": "Erkunde eine beständige offene Welt mit anderen Spielern. Während sie wächst, kommen neue Gebiete und Weltbosse hinzu.", "features.p3.tag": "Herausforderung", "features.p3.title": "Risse und seltene Beute", "features.p3.text": "Stelle dich instanzierten Rissen und ihren Endgegnern, um eine Chance auf die seltensten Belohnungen der Welt zu erhalten – darunter Reittiere.", "features.p4.tag": "Gemeinschaft", "features.p4.title": "Gemeinsam ins Abenteuer", "features.p4.text": "Finde Freunde, bilde eine Gruppe und kämpfe Seite an Seite gegen die Übel der Welt. Manche Gegner sollte man nicht allein bezwingen.", "features.p5.tag": "Entdeckung", "features.p5.title": "Das Kompendium", "features.p5.text": "Halte alle Entdeckungen deiner Reise fest und jage den letzten Prozentpunkten der vollständigen Sammlung nach.", "features.p6.tag": "Fairness", "features.p6.title": "Von Grund auf fair", "features.p6.text": "Ein einfaches Abo. Kein Echtgeld-Shop, keine käuflichen kosmetischen Gegenstände und niemals Pay-to-win.",
    "devlogs.eyebrow": "Aus der Schmiede", "devlogs.title": "Wöchentliche Entwicklerblogs", "devlogs.p1": "Abonniere den YouTube-Kanal und verfolge Elegons Entwicklung mit wöchentlichen Neuigkeiten und Einblicken hinter die Kulissen.", "devlogs.p2": "Elegon gemeinsam mit der Community offen zu entwickeln, ist mir wichtig. Euer Feedback und eure Ideen helfen, das Spiel zu gestalten. Die Updates zeigen, wie die Welt weiterwächst.", "devlogs.subscribe": "YouTube abonnieren", "devlogs.changelog": "Änderungsprotokoll lesen",
    "vision.eyebrow": "Warum es Elegon gibt", "vision.title": "Die Vision", "vision.quote": "Fortschritt in Elegon soll sich verdient anfühlen.", "vision.credit": "Keone, Schöpfer von Elegon", "vision.pillar": "Grundsatz", "vision.p1.title": "Der Geist der Klassiker", "vision.p1.text": "Elegon möchte eine Online-Welt erschaffen, die von klassischen MMORPGs wie dem frühen World of Warcraft und prägenden Rollenspielen inspiriert ist. Diese Spiele machten ihre Welten bedeutungsvoll, gemeinschaftlich und lohnenswert. Elegon greift diesen Geist auf und nutzt moderne Ideen dort, wo sie das Spielerlebnis verbessern.", "vision.p2.title": "Verdient, niemals erkauft", "vision.p2.text": "Dein Charakter wächst durch Zeit, Einsatz und Abenteuer, nicht durch Käufe. Es wird keinen Echtgeld-Shop für kosmetische oder spielentscheidende Gegenstände geben. Ein einfaches Monatsabo unterstützt die Entwicklung und hält den Fokus auf der Welt und dem Spielerlebnis.", "vision.p3.title": "Eine Welt für die Zukunft", "vision.p3.text": "Elegon ist ein langfristiges Herzensprojekt: eine lebendige Welt, die über Jahre weiterwachsen und sich entwickeln soll. Als Solo-Entwickler möchte ich einen Ort schaffen, in den Spieler investieren, zu dem sie zurückkehren und zu dem sie sich zugehörig fühlen.",
    "updates.eyebrow": "Chronik der Entwicklung", "updates.title": "Neueste Updates", "updates.intro": "Elegon entsteht offen und erhält laufend Updates. Hier siehst du, was zuletzt in der Welt hinzugekommen ist.", "updates.shipped": "Veröffentlichte Änderungen", "updates.since": "seit", "updates.viewAll": "Alle Änderungen ansehen", "updates.latest": "Neueste",
    "supporters.eyebrow": "Ruhmeshalle", "supporters.title": "Patreon-Unterstützer", "supporters.intro": "Dank der Großzügigkeit dieser Abenteurer wird Elegon möglich. Ihre Namen sind in die Geschichte der Welt eingraviert.", "supporters.loading": "Unterstützer werden gerufen…", "supporters.hero": "Held", "supporters.heroes": "Helden", "supporters.become": "Unterstützer werden", "supporters.legendary": "Legendäre Unterstützer", "supporters.epic": "Epische Unterstützer", "supporters.rare": "Seltene Unterstützer",
    "faq.eyebrow": "Gespräche in der Taverne", "faq.title": "Häufig gestellte Fragen", "faq.more": "Noch Fragen?", "faq.discordText": "Nimm Platz auf unserem Discord. Frag uns alles, teile deine Ideen und lerne andere Abenteurer kennen.", "faq.join": "Discord beitreten", "faq.q1": "Wie wird Elegon finanziert?", "faq.a1": "Elegon wird durch ein einziges Monatsabo unterstützt. Es wird niemals einen In-Game-Shop mit kosmetischen oder spielentscheidenden Gegenständen geben. Außerhalb des Abos könnte es Merchandise geben, aber nichts, das in der Welt von Elegon existiert.", "faq.q2": "Auf welchen Plattformen ist Elegon verfügbar?", "faq.a2": "Elegon ist über Steam für Windows, Linux und macOS spielbar. Die macOS-Version benötigt derzeit einen kleinen Umweg, da die App noch nicht signiert ist. Das wird künftig behoben.", "faq.q3": "Wer bist du? Hast du schon etwas Ähnliches entwickelt?", "faq.a3": "Ich bin Keone, Softwareentwickler aus London. Ich arbeite hauptberuflich außerhalb der Spielebranche und entwickle Elegon in meiner Freizeit. Ich habe etwa zehn Jahre Erfahrung; Elegon ist mein erstes großes Spielprojekt.", "faq.q4": "Welche Technologie nutzt Elegon?", "faq.a4": "Elegon basiert auf der Open-Source-Engine Godot, die flexibel ist und alle Anforderungen des Projekts erfüllt. Netzwerk und Backend nutzen SpacetimeDB, eine leistungsstarke, moderne Plattform für persistente Online-Welten.", "faq.q5": "Wie kann ich die Entwicklung von Elegon unterstützen?", "faq.a5": "Deine Unterstützung ist willkommen, aber nie notwendig. Du kannst das Projekt auf Patreon oder Ko-fi unterstützen. Entwicklerblogs anzusehen, am Playtest teilzunehmen und Feedback zu geben hilft ebenfalls enorm.", "faq.q6": "Darf ich Videos, Streams oder Artikel über Elegon machen?", "faq.a6": "Auf jeden Fall! Du bist herzlich eingeladen, Inhalte rund um Elegon zu erstellen, etwa YouTube-Videos, Livestreams, Artikel und mehr. Du brauchst dafür keine Erlaubnis, und ich freue mich darauf, deine Werke zu sehen. Teile sie gerne auf Discord.",
    "cta.eyebrow": "Die Reise beginnt", "cta.title": "Dein Abenteuer wartet", "cta.text": "Setze Elegon auf deine Steam-Wunschliste, spiele beim rund um die Uhr verfügbaren Playtest mit und gestalte eine Welt, die bleibt.", "cta.wishlist": "Auf Steam wünschen", "cta.discord": "Discord beitreten", "footer.engine": "Erstellt mit Godot und SpacetimeDB",
  },
  es: {
    "nav.world": "Mundo", "nav.features": "Características", "nav.devlogs": "Diarios", "nav.vision": "Visión", "nav.faq": "Preguntas", "nav.changelog": "Novedades", "nav.feedback": "Comentarios", "nav.roadmap": "Hoja de ruta", "nav.wishlist": "Lista de deseos", "nav.wishlistSteam": "Añadir en Steam", "nav.menu": "Menú", "nav.openMenu": "Abrir menú", "nav.more": "Más", "nav.language": "Cambiar idioma", "nav.primary": "Navegación principal", "nav.mobile": "Navegación móvil", "nav.footer": "Pie de página", "nav.home": "Inicio de Elegon",
    "hero.live": "Prueba abierta 24/7 en Steam", "hero.tagline": "Un MMORPG inspirado en los clásicos", "hero.description": "Entra en un mundo donde tu progreso importa y la aventura te espera.", "hero.community": "Únete a la comunidad", "hero.begin": "Comienza tu viaje", "hero.platforms": "Plataformas disponibles",
    "seo.title": "Elegon: un MMORPG indie inspirado en los clásicos", "seo.description": "Un MMORPG creado por un desarrollador en solitario e inspirado en los clásicos. Progresión ganada, mundo abierto vivo y sin pay-to-win. Únete a la prueba gratuita 24/7 en Steam.",
    "footer.description": "Un MMORPG inspirado en los clásicos, creado abiertamente por un desarrollador en solitario. Progresión ganada, un mundo vivo y nunca una tienda de efectivo.", "footer.game": "El juego", "footer.community": "Comunidad", "footer.shape": "Da forma a Elegon", "footer.world": "El mundo", "footer.vision": "La visión", "footer.feedback": "Tablero de comentarios", "footer.rights": "Desarrollado en solitario con pasión. Todos los derechos reservados.", "footer.london": "Forjado en Londres",
    "changelog.title": "Novedades y notas de parche", "changelog.description": "Todas las notas de parche de Elegon en un solo lugar: las últimas correcciones, mejoras y funciones de la prueba 24/7 de Steam.", "changelog.today": "Hoy", "changelog.yesterday": "Ayer", "changelog.daysAgo": "días atrás", "world.weekly": "Semanal",
    "world.eyebrow": "Te damos la bienvenida, viajero", "world.title": "No eres el elegido", "world.intro": "Hola, soy Keone y desarrollo Elegon en solitario. Empecé este proyecto porque siempre me ha apasionado el género, pero cada vez cuesta más encontrar mundos en línea atractivos que respeten el tiempo y el esfuerzo de quienes juegan.", "world.identity": "Elegon es un MMORPG de mundo abierto siempre conectado. No eres el héroe elegido, sino una pequeña parte de una historia mucho más grande.", "world.adventure": "Hazte más fuerte con el tiempo, derrota enemigos poderosos, haz amistades y enfréntate a las fuerzas del mal para conseguir las mayores recompensas del mundo.", "world.playtest": "Elegon se desarrolla abiertamente. Únete a la prueba de Steam disponible las 24 horas y ayuda a dar forma al juego con tus comentarios. Después de la versión 1.0, el mundo seguirá creciendo y evolucionando.", "world.nowOpen": "Ya disponible", "world.playtestLabel": "Prueba de Steam 24/7", "world.noP2w": "Sin pagar para ganar. Jamás.", "world.statPlaytest": "Prueba abierta en Steam", "world.statDevlogs": "Diarios semanales en YouTube", "world.statShop": "Artículos en la tienda", "world.statPlatforms": "Plataformas: Windows, Linux y macOS",
    "features.eyebrow": "Forja tu leyenda", "features.title": "Lo que te espera en Elegon", "features.intro": "Un mundo inspirado en los MMORPG que definieron el género, creado para quienes quieren que su tiempo importe.", "features.p1.tag": "Progresión", "features.p1.title": "Progresión que te ganas", "features.p1.text": "Hazte más fuerte con tiempo, esfuerzo y aventuras. Desbloquea hechizos de clase al subir de nivel y personaliza tu personaje con talentos.", "features.p2.tag": "Exploración", "features.p2.title": "Un mundo siempre conectado", "features.p2.text": "Explora un mundo persistente compartido con otros jugadores, que seguirá creciendo con nuevas zonas y jefes de mundo.", "features.p3.tag": "Desafío", "features.p3.title": "Brechas y botín raro", "features.p3.text": "Entra en brechas instanciadas y enfréntate a sus jefes finales para conseguir recompensas excepcionales, incluidas monturas.", "features.p4.tag": "Comunidad", "features.p4.title": "Aventuras en compañía", "features.p4.text": "Haz amistades, forma un grupo y combate el mal del mundo codo con codo. Algunos enemigos no están hechos para enfrentarlos a solas.", "features.p5.tag": "Descubrimiento", "features.p5.title": "El compendio", "features.p5.text": "Registra todo lo que descubras durante tu viaje y persigue el último porcentaje de descubrimientos.", "features.p6.tag": "Juego justo", "features.p6.title": "Justo desde el diseño", "features.p6.text": "Una sola suscripción sencilla. Sin tienda dentro del juego, sin cosméticos a la venta y nunca pagar para ganar.",
    "devlogs.eyebrow": "Desde la forja", "devlogs.title": "Diarios semanales de desarrollo", "devlogs.p1": "Suscríbete al canal de YouTube para seguir el desarrollo de Elegon con novedades semanales y vídeos entre bastidores sobre el progreso del juego.", "devlogs.p2": "Para mí es muy importante crear Elegon abiertamente junto a la comunidad. Vuestras opiniones e ideas ayudan a dar forma al juego y estas novedades os mantienen al día mientras el mundo crece.", "devlogs.subscribe": "Suscribirse en YouTube", "devlogs.changelog": "Leer las novedades",
    "vision.eyebrow": "Por qué existe Elegon", "vision.title": "La visión", "vision.quote": "La progresión de Elegon debe sentirse ganada.", "vision.credit": "Keone, creador de Elegon", "vision.pillar": "Principio", "vision.p1.title": "El espíritu de los clásicos", "vision.p1.text": "Elegon quiere crear un mundo en línea inspirado en MMORPG clásicos como los primeros World of Warcraft y otros juegos de rol que definieron el género. Aquellos mundos eran significativos, sociales y gratificantes de explorar. Elegon recupera ese espíritu e incorpora ideas modernas cuando mejoran la experiencia.", "vision.p2.title": "Se gana, no se compra", "vision.p2.text": "Tu personaje progresa con tiempo, esfuerzo y aventuras, no con compras. No habrá tienda de dinero real para cosméticos ni artículos que den ventaja. Una sencilla suscripción mensual financiará el desarrollo y permitirá centrarse en la calidad del mundo y la experiencia de juego.", "vision.p3.title": "Un mundo hecho para perdurar", "vision.p3.text": "Elegon es un proyecto personal a largo plazo: un mundo vivo que seguirá creciendo y evolucionando durante años. Como desarrollador en solitario, quiero crear un lugar en el que los jugadores puedan invertir, al que quieran volver y del que se sientan parte.",
    "updates.eyebrow": "Crónicas del desarrollo", "updates.title": "Últimas novedades", "updates.intro": "Elegon se desarrolla abiertamente y recibe actualizaciones constantes. Esto es lo último que ha llegado al mundo.", "updates.shipped": "Cambios publicados", "updates.since": "desde", "updates.viewAll": "Ver todas las novedades", "updates.latest": "Lo último",
    "supporters.eyebrow": "Salón de héroes", "supporters.title": "Colaboradores de Patreon", "supporters.intro": "Elegon es posible gracias a la generosidad de estos aventureros. Sus nombres están grabados en la historia del mundo.", "supporters.loading": "Buscando colaboradores…", "supporters.hero": "héroe", "supporters.heroes": "héroes", "supporters.become": "Hazte colaborador", "supporters.legendary": "Colaboradores legendarios", "supporters.epic": "Colaboradores épicos", "supporters.rare": "Colaboradores excepcionales",
    "faq.eyebrow": "Charla de taberna", "faq.title": "Preguntas frecuentes", "faq.more": "¿Aún tienes preguntas?", "faq.discordText": "Acércate al Discord. Pregunta lo que quieras, comparte tus ideas y conoce a otros aventureros.", "faq.join": "Unirse a Discord", "faq.q1": "¿Cómo se financiará Elegon?", "faq.a1": "Elegon se financiará con una única suscripción mensual. Nunca habrá una tienda dentro del juego con cosméticos o artículos para pagar para ganar. Fuera de la suscripción, podría haber productos físicos, nada que exista dentro del mundo de Elegon.", "faq.q2": "¿En qué plataformas está disponible Elegon?", "faq.a2": "Puedes jugar a Elegon en Steam desde Windows, Linux y macOS. Por ahora, la versión de macOS requiere un pequeño paso adicional porque la aplicación aún no está firmada; lo solucionaremos más adelante.", "faq.q3": "¿Quién eres? ¿Has creado algo parecido antes?", "faq.a3": "Soy Keone, desarrollador de software en Londres. Trabajo a jornada completa fuera del sector de los videojuegos y desarrollo Elegon en mi tiempo libre. Tengo unos diez años de experiencia y Elegon es mi primer gran proyecto de juego.", "faq.q4": "¿Qué tecnología utiliza Elegon?", "faq.a4": "Elegon está creado con Godot, un motor de código abierto y flexible. Para las redes y el backend utiliza SpacetimeDB, una plataforma moderna y de alto rendimiento para mundos persistentes en línea.", "faq.q5": "¿Cómo puedo apoyar el desarrollo de Elegon?", "faq.a5": "Agradecemos mucho tu apoyo, aunque nunca es obligatorio. Puedes colaborar en Patreon o Ko-fi. También ayuda muchísimo ver los diarios, participar en la prueba y compartir tus comentarios.", "faq.q6": "¿Puedo hacer vídeos, directos o artículos sobre Elegon?", "faq.a6": "¡Por supuesto! Puedes crear contenido sobre Elegon, como vídeos de YouTube, directos, artículos y mucho más. No necesitas permiso, y me encantaría ver lo que haces, así que no dudes en compartirlo en Discord.",
    "cta.eyebrow": "El viaje comienza", "cta.title": "Tu aventura te espera", "cta.text": "Añade Elegon a tu lista de deseos de Steam, participa en la prueba 24/7 y ayuda a construir un mundo duradero.", "cta.wishlist": "Añadir a la lista de Steam", "cta.discord": "Unirse a Discord", "footer.engine": "Creado con Godot y SpacetimeDB",
  },
  fr: {
    "nav.world": "Monde", "nav.features": "Fonctionnalités", "nav.devlogs": "Journaux", "nav.vision": "Vision", "nav.faq": "FAQ", "nav.changelog": "Mises à jour", "nav.feedback": "Avis", "nav.roadmap": "Feuille de route", "nav.wishlist": "Liste de souhaits", "nav.wishlistSteam": "Ajouter sur Steam", "nav.menu": "Menu", "nav.openMenu": "Ouvrir le menu", "nav.more": "Plus", "nav.language": "Changer de langue", "nav.primary": "Navigation principale", "nav.mobile": "Navigation mobile", "nav.footer": "Pied de page", "nav.home": "Accueil Elegon",
    "hero.live": "Playtest ouvert 24 h/24, 7 j/7 sur Steam", "hero.tagline": "Un MMORPG inspiré des classiques", "hero.description": "Entrez dans un monde où votre progression compte et où l'aventure vous attend.", "hero.community": "Rejoindre la communauté", "hero.begin": "Commencez votre voyage", "hero.platforms": "Plateformes disponibles",
    "seo.title": "Elegon : un MMORPG indépendant inspiré des classiques", "seo.description": "Un MMORPG développé en solo et inspiré des classiques. Une progression méritée, un monde ouvert vivant et aucun pay-to-win. Rejoignez le playtest gratuit 24 h/24 sur Steam.",
    "footer.description": "Un MMORPG inspiré des classiques, développé ouvertement par un créateur solo. Une progression méritée, un monde vivant et jamais de boutique en jeu.", "footer.game": "Le jeu", "footer.community": "Communauté", "footer.shape": "Façonnez Elegon", "footer.world": "Le monde", "footer.vision": "La vision", "footer.feedback": "Tableau d'avis", "footer.rights": "Développé en solo avec passion. Tous droits réservés.", "footer.london": "Forgé à Londres",
    "changelog.title": "Mises à jour et notes de patch", "changelog.description": "Toutes les notes de patch d'Elegon au même endroit : les derniers correctifs, améliorations et contenus du playtest Steam 24 h/24.", "changelog.today": "Aujourd'hui", "changelog.yesterday": "Hier", "changelog.daysAgo": "jours plus tôt", "world.weekly": "Chaque semaine",
    "world.eyebrow": "Bienvenue, voyageur", "world.title": "Vous n'êtes pas l'élu", "world.intro": "Bonjour, je m'appelle Keone et je développe Elegon en solo. J'ai lancé ce projet par passion pour le genre, mais les mondes en ligne captivants qui respectent le temps et les efforts des joueurs se font rares.", "world.identity": "Elegon est un MMORPG en monde ouvert et toujours connecté. Vous n'êtes pas le héros élu, mais une petite partie d'une histoire bien plus vaste.", "world.adventure": "Devenez plus fort au fil du temps, terrassez de puissants ennemis, nouez des amitiés et combattez les forces du mal pour obtenir les plus grandes récompenses du monde.", "world.playtest": "Elegon est développé au grand jour. Rejoignez le playtest Steam disponible 24 h/24 et contribuez au jeu avec vos retours. Après la version 1.0, le monde continuera de grandir et d'évoluer.", "world.nowOpen": "Ouvert", "world.playtestLabel": "Playtest Steam 24 h/24", "world.noP2w": "Aucun pay-to-win. Jamais.", "world.statPlaytest": "Playtest ouvert sur Steam", "world.statDevlogs": "Journaux hebdomadaires sur YouTube", "world.statShop": "Articles en boutique", "world.statPlatforms": "Plateformes : Windows, Linux et macOS",
    "features.eyebrow": "Forgez votre légende", "features.title": "Ce qui vous attend dans Elegon", "features.intro": "Un monde inspiré des MMORPG qui ont défini le genre, conçu pour les joueurs qui veulent que leur temps compte.", "features.p1.tag": "Progression", "features.p1.title": "Une progression méritée", "features.p1.text": "Gagnez en puissance grâce au temps, aux efforts et à l'aventure. Débloquez des sorts de classe en montant de niveau et façonnez votre personnage avec des talents.", "features.p2.tag": "Exploration", "features.p2.title": "Un monde toujours connecté", "features.p2.text": "Explorez un monde persistant partagé avec d'autres joueurs, qui s'enrichira de nouvelles zones et de boss mondiaux.", "features.p3.tag": "Défi", "features.p3.title": "Brèches et butin rare", "features.p3.text": "Affrontez des brèches instanciées et leurs boss finaux pour tenter d'obtenir les récompenses les plus rares, montures comprises.", "features.p4.tag": "Social", "features.p4.title": "L'aventure à plusieurs", "features.p4.text": "Faites-vous des amis, formez un groupe et combattez côte à côte les forces du mal. Certains adversaires ne se combattent pas seuls.", "features.p5.tag": "Découverte", "features.p5.title": "Le Compendium", "features.p5.text": "Consignez chaque découverte de votre voyage et tentez d'atteindre le dernier pourcentage de complétion.", "features.p6.tag": "Équité", "features.p6.title": "L'équité au cœur du jeu", "features.p6.text": "Un abonnement simple. Aucune boutique en jeu, aucun cosmétique à vendre et jamais de pay-to-win.",
    "devlogs.eyebrow": "Depuis la forge", "devlogs.title": "Journaux de développement hebdomadaires", "devlogs.p1": "Abonnez-vous à la chaîne YouTube pour suivre Elegon grâce aux actualités hebdomadaires et aux coulisses du projet.", "devlogs.p2": "Développer Elegon ouvertement avec la communauté est essentiel pour moi. Vos retours et vos idées contribuent au jeu, et ces actualités vous tiennent au courant de l'évolution du monde.", "devlogs.subscribe": "S'abonner sur YouTube", "devlogs.changelog": "Lire les mises à jour",
    "vision.eyebrow": "Pourquoi Elegon existe", "vision.title": "La vision", "vision.quote": "Dans Elegon, la progression doit se mériter.", "vision.credit": "Keone, créateur d'Elegon", "vision.pillar": "Principe", "vision.p1.title": "L'esprit des classiques", "vision.p1.text": "Elegon veut créer un monde inspiré des MMORPG classiques, comme les premiers World of Warcraft et les jeux fondateurs du genre. Ces jeux proposaient des mondes riches de sens, sociaux et gratifiants à explorer. Elegon retrouve cet esprit et adopte des idées modernes lorsqu'elles améliorent réellement l'expérience.", "vision.p2.title": "Mérité, jamais acheté", "vision.p2.text": "Votre personnage progresse grâce au temps, aux efforts et à l'aventure, pas aux achats. Il n'y aura aucune boutique en jeu pour les cosmétiques ou les objets pay-to-win. Un abonnement mensuel simple soutiendra le développement et permettra de se concentrer sur le monde et l'expérience de jeu.", "vision.p3.title": "Un monde fait pour durer", "vision.p3.text": "Elegon est un projet passionné conçu pour durer : un monde vivant qui continuera de grandir pendant des années. En tant que développeur solo, je souhaite créer un lieu dans lequel les joueurs peuvent s'investir, revenir et se sentir chez eux.",
    "updates.eyebrow": "Chroniques du développement", "updates.title": "Dernières actualités", "updates.intro": "Elegon est développé ouvertement et reçoit des mises à jour régulières. Voici les nouveautés les plus récentes du monde.", "updates.shipped": "Modifications publiées", "updates.since": "depuis", "updates.viewAll": "Voir toutes les mises à jour", "updates.latest": "Dernière actualité",
    "supporters.eyebrow": "Panthéon des héros", "supporters.title": "Soutiens Patreon", "supporters.intro": "La générosité de ces aventuriers rend Elegon possible. Leurs noms sont gravés dans l'histoire du monde.", "supporters.loading": "Appel des soutiens…", "supporters.hero": "héros", "supporters.heroes": "héros", "supporters.become": "Devenir un soutien", "supporters.legendary": "Soutiens légendaires", "supporters.epic": "Soutiens épiques", "supporters.rare": "Soutiens rares",
    "faq.eyebrow": "Paroles de taverne", "faq.title": "Foire aux questions", "faq.more": "Vous avez encore des questions ?", "faq.discordText": "Installez-vous sur Discord. Posez vos questions, partagez vos idées et rencontrez d'autres aventuriers.", "faq.join": "Rejoindre Discord", "faq.q1": "Comment Elegon sera-t-il financé ?", "faq.a1": "Elegon sera financé par un abonnement mensuel unique. Il n'y aura jamais de boutique en jeu vendant des cosmétiques ou des objets pay-to-win. En dehors de l'abonnement, seuls des produits dérivés pourraient être proposés, rien qui existe dans le monde d'Elegon.", "faq.q2": "Sur quelles plateformes Elegon est-il disponible ?", "faq.a2": "Elegon est jouable sur Steam sous Windows, Linux et macOS. La version macOS nécessite actuellement une petite manipulation car l'application n'est pas encore signée ; cela sera corrigé à l'avenir.", "faq.q3": "Qui êtes-vous ? Avez-vous déjà créé un jeu similaire ?", "faq.a3": "Je m'appelle Keone et je suis développeur logiciel à Londres. Je travaille à temps plein hors du secteur du jeu vidéo et développe Elegon pendant mon temps libre. J'ai environ dix ans d'expérience ; Elegon est mon premier grand projet de jeu.", "faq.q4": "Quelles technologies utilise Elegon ?", "faq.a4": "Elegon utilise le moteur open source Godot, flexible et adapté au projet. Le réseau et le backend reposent sur SpacetimeDB, une plateforme moderne et performante pour les mondes en ligne persistants.", "faq.q5": "Comment soutenir le développement d'Elegon ?", "faq.a5": "Votre soutien est apprécié, mais jamais obligatoire. Vous pouvez soutenir le projet sur Patreon ou Ko-fi. Regarder les journaux, participer au playtest et partager vos retours aide aussi énormément.", "faq.q6": "Puis-je faire des vidéos, des streams ou des articles sur Elegon ?", "faq.a6": "Absolument ! Vous êtes les bienvenus pour créer du contenu autour d'Elegon : vidéos YouTube, streams, articles et plus encore. Aucune autorisation n'est nécessaire, et j'adorerais voir ce que vous créez, alors n'hésitez pas à le partager sur Discord.",
    "cta.eyebrow": "L'aventure commence", "cta.title": "L'aventure vous attend", "cta.text": "Ajoutez Elegon à votre liste de souhaits Steam, rejoignez le playtest 24 h/24 et contribuez à bâtir un monde durable.", "cta.wishlist": "Ajouter aux souhaits Steam", "cta.discord": "Rejoindre Discord", "footer.engine": "Créé avec Godot et SpacetimeDB",
  },
  "pt-BR": {
    "nav.world": "Mundo", "nav.features": "Recursos", "nav.devlogs": "Diários", "nav.vision": "Visão", "nav.faq": "Perguntas", "nav.changelog": "Novidades", "nav.feedback": "Feedback", "nav.roadmap": "Roteiro", "nav.wishlist": "Lista de desejos", "nav.wishlistSteam": "Adicionar à Steam", "nav.menu": "Menu", "nav.openMenu": "Abrir menu", "nav.more": "Mais", "nav.language": "Alterar idioma", "nav.primary": "Navegação principal", "nav.mobile": "Navegação móvel", "nav.footer": "Rodapé", "nav.home": "Página inicial do Elegon",
    "hero.live": "Playtest aberto 24 horas por dia na Steam", "hero.tagline": "Um MMORPG inspirado nos clássicos", "hero.description": "Entre em um mundo em que sua progressão importa e a aventura espera por você.", "hero.community": "Entrar na comunidade", "hero.begin": "Comece sua jornada", "hero.platforms": "Plataformas disponíveis",
    "seo.title": "Elegon: um MMORPG indie inspirado nos clássicos", "seo.description": "Um MMORPG criado por um desenvolvedor solo e inspirado nos clássicos. Progressão conquistada, mundo aberto vivo e sem pay-to-win. Entre no playtest gratuito 24 horas por dia na Steam.",
    "footer.description": "Um MMORPG inspirado nos clássicos, criado abertamente por um desenvolvedor solo. Progressão conquistada, mundo vivo e nenhuma loja de dinheiro.", "footer.game": "O jogo", "footer.community": "Comunidade", "footer.shape": "Molde Elegon", "footer.world": "O mundo", "footer.vision": "A visão", "footer.feedback": "Quadro de feedback", "footer.rights": "Desenvolvido solo com paixão. Todos os direitos reservados.", "footer.london": "Forjado em Londres",
    "changelog.title": "Novidades e notas de atualização", "changelog.description": "Todas as notas de atualização de Elegon em um só lugar: as correções, melhorias e recursos mais recentes do playtest 24 horas por dia na Steam.", "changelog.today": "Hoje", "changelog.yesterday": "Ontem", "changelog.daysAgo": "dias atrás", "world.weekly": "Semanal",
    "world.eyebrow": "Boas-vindas, viajante", "world.title": "Você não é o escolhido", "world.intro": "Olá, sou Keone e desenvolvo Elegon sozinho. Comecei este projeto porque sempre fui apaixonado pelo gênero, mas está cada vez mais difícil encontrar mundos online envolventes que respeitem o tempo e o esforço de quem joga.", "world.identity": "Elegon é um MMORPG de mundo aberto e sempre online. Você não é o herói escolhido, mas uma pequena parte de uma história muito maior.", "world.adventure": "Fique mais forte com o tempo, derrote inimigos poderosos, faça amizades e enfrente as forças do mal em busca das maiores recompensas do mundo.", "world.playtest": "Elegon está sendo desenvolvido abertamente. Participe do playtest da Steam, disponível 24 horas por dia, e ajude a moldar o jogo com seu feedback. Depois da versão 1.0, o mundo continuará crescendo e evoluindo.", "world.nowOpen": "Aberto agora", "world.playtestLabel": "Playtest da Steam 24/7", "world.noP2w": "Sem pay-to-win. Nunca.", "world.statPlaytest": "Playtest aberto na Steam", "world.statDevlogs": "Diários semanais no YouTube", "world.statShop": "Itens na loja do jogo", "world.statPlatforms": "Plataformas: Windows, Linux e macOS",
    "features.eyebrow": "Forje sua lenda", "features.title": "O que espera por você em Elegon", "features.intro": "Um mundo inspirado nos MMORPGs que definiram o gênero, feito para quem quer que seu tempo tenha valor.", "features.p1.tag": "Progressão", "features.p1.title": "Uma progressão conquistada", "features.p1.text": "Fique mais forte com tempo, dedicação e aventura. Desbloqueie magias de classe ao subir de nível e personalize seu personagem com talentos.", "features.p2.tag": "Exploração", "features.p2.title": "Um mundo sempre online", "features.p2.text": "Explore um mundo persistente compartilhado com outros jogadores, que continuará recebendo novas regiões e chefes mundiais.", "features.p3.tag": "Desafio", "features.p3.title": "Fendas e itens raros", "features.p3.text": "Enfrente fendas instanciadas e seus chefes finais para tentar obter as recompensas mais raras do mundo, incluindo montarias.", "features.p4.tag": "Social", "features.p4.title": "Aventura em grupo", "features.p4.text": "Faça amizades, forme um grupo e enfrente o mal lado a lado. Alguns inimigos não foram feitos para serem enfrentados sozinhos.", "features.p5.tag": "Descoberta", "features.p5.title": "O Compêndio", "features.p5.text": "Registre tudo o que descobrir durante sua jornada e busque os últimos pontos percentuais de descobertas.", "features.p6.tag": "Jogo justo", "features.p6.title": "Justo por princípio", "features.p6.text": "Uma assinatura simples. Sem loja dentro do jogo, sem cosméticos à venda e nunca pay-to-win.",
    "devlogs.eyebrow": "Da forja", "devlogs.title": "Diários semanais de desenvolvimento", "devlogs.p1": "Inscreva-se no canal do YouTube para acompanhar o desenvolvimento de Elegon com atualizações semanais e bastidores do progresso do jogo.", "devlogs.p2": "Desenvolver Elegon abertamente com a comunidade é muito importante para mim. Suas opiniões e ideias ajudam a moldar o jogo, e estas atualizações mostram como o mundo continua crescendo.", "devlogs.subscribe": "Inscrever-se no YouTube", "devlogs.changelog": "Ler as novidades",
    "vision.eyebrow": "Por que Elegon existe", "vision.title": "A visão", "vision.quote": "Em Elegon, a progressão deve ser conquistada.", "vision.credit": "Keone, criador de Elegon", "vision.pillar": "Princípio", "vision.p1.title": "O espírito dos clássicos", "vision.p1.text": "Elegon quer criar um mundo online inspirado em MMORPGs clássicos, como os primeiros World of Warcraft e outros RPGs que definiram o gênero. Esses jogos criaram mundos significativos, sociais e recompensadores de explorar. Elegon resgata esse espírito e adota ideias modernas quando elas melhoram a experiência.", "vision.p2.title": "Conquistado, nunca comprado", "vision.p2.text": "Seu personagem evolui com tempo, dedicação e aventura, não com compras. Não haverá loja de dinheiro real para cosméticos ou itens pay-to-win. Uma assinatura mensal simples apoiará o desenvolvimento e manterá o foco na qualidade do mundo e da experiência dos jogadores.", "vision.p3.title": "Um mundo feito para durar", "vision.p3.text": "Elegon é um projeto pessoal de longo prazo: um mundo vivo que continuará crescendo e evoluindo por anos. Como desenvolvedor solo, quero criar um lugar no qual os jogadores possam investir, retornar e sentir que fazem parte.",
    "updates.eyebrow": "Crônicas do desenvolvimento", "updates.title": "Últimas atualizações", "updates.intro": "Elegon é desenvolvido abertamente e recebe atualizações constantes. Veja o que chegou recentemente ao mundo.", "updates.shipped": "Alterações lançadas", "updates.since": "desde", "updates.viewAll": "Ver todas as novidades", "updates.latest": "Mais recente",
    "supporters.eyebrow": "Salão dos heróis", "supporters.title": "Apoiadores do Patreon", "supporters.intro": "Elegon existe graças à generosidade destes aventureiros. Seus nomes estão gravados na história do mundo.", "supporters.loading": "Convocando apoiadores…", "supporters.hero": "herói", "supporters.heroes": "heróis", "supporters.become": "Torne-se apoiador", "supporters.legendary": "Apoiadores lendários", "supporters.epic": "Apoiadores épicos", "supporters.rare": "Apoiadores raros",
    "faq.eyebrow": "Conversa na taverna", "faq.title": "Perguntas frequentes", "faq.more": "Ainda tem dúvidas?", "faq.discordText": "Puxe uma cadeira no Discord. Pergunte o que quiser, compartilhe ideias e conheça outros aventureiros.", "faq.join": "Entrar no Discord", "faq.q1": "Como Elegon será monetizado?", "faq.a1": "Elegon será mantido por uma única assinatura mensal. Nunca haverá uma loja no jogo vendendo cosméticos ou itens pay-to-win. Fora da assinatura, poderá haver produtos físicos, mas nada que exista dentro do mundo de Elegon.", "faq.q2": "Em quais plataformas Elegon está disponível?", "faq.a2": "Elegon pode ser jogado pela Steam no Windows, Linux e macOS. Por enquanto, a versão para macOS exige um pequeno procedimento porque o aplicativo ainda não tem assinatura digital; isso será resolvido futuramente.", "faq.q3": "Quem é você? Já criou algo parecido?", "faq.a3": "Sou Keone, desenvolvedor de software em Londres. Trabalho em tempo integral fora da indústria de jogos e desenvolvo Elegon no meu tempo livre. Tenho cerca de dez anos de experiência, e Elegon é meu primeiro grande projeto de jogo.", "faq.q4": "Que tecnologia Elegon usa?", "faq.a4": "Elegon é feito com Godot, uma engine de código aberto e flexível. A rede e o backend usam SpacetimeDB, uma plataforma moderna e de alto desempenho para mundos online persistentes.", "faq.q5": "Como posso apoiar o desenvolvimento de Elegon?", "faq.a5": "Seu apoio é muito bem-vindo, mas nunca obrigatório. Você pode apoiar o projeto no Patreon ou Ko-fi. Assistir aos diários, participar do playtest e compartilhar feedback também ajuda muito.", "faq.q6": "Posso fazer vídeos, lives ou artigos sobre Elegon?", "faq.a6": "Com certeza! Você é muito bem-vindo para criar conteúdo sobre Elegon, como vídeos no YouTube, lives, artigos e muito mais. Não é preciso pedir permissão, e eu adoraria ver o que você criar, então fique à vontade para compartilhar no Discord.",
    "cta.eyebrow": "A jornada começa", "cta.title": "Sua aventura espera por você", "cta.text": "Adicione Elegon à sua lista de desejos na Steam, participe do playtest 24/7 e ajude a construir um mundo duradouro.", "cta.wishlist": "Adicionar à lista da Steam", "cta.discord": "Entrar no Discord", "footer.engine": "Feito com Godot e SpacetimeDB",
  },
  ru: {
    "nav.world": "Мир", "nav.features": "Особенности", "nav.devlogs": "Дневники разработки", "nav.vision": "Видение", "nav.faq": "Вопросы", "nav.changelog": "Список изменений", "nav.feedback": "Отзывы", "nav.roadmap": "План разработки", "nav.wishlist": "В желаемое", "nav.wishlistSteam": "Добавить в желаемое Steam", "nav.menu": "Меню", "nav.openMenu": "Открыть меню", "nav.more": "Ещё", "nav.language": "Изменить язык", "nav.primary": "Основная навигация", "nav.mobile": "Мобильная навигация", "nav.footer": "Нижняя навигация", "nav.home": "Главная страница Elegon",
    "hero.live": "Открытый плейтест в Steam 24/7", "hero.tagline": "MMORPG, вдохновлённая классикой", "hero.description": "Окунитесь в мир, где ваш прогресс важен и приключения уже ждут.", "hero.community": "Присоединиться к сообществу", "hero.begin": "Начать путешествие", "hero.platforms": "Доступные платформы",
    "seo.title": "Elegon: инди-MMORPG, вдохновлённая классикой", "seo.description": "MMORPG от сольного разработчика, вдохновлённая классикой. Заслуженный прогресс, живой открытый мир и никакого pay-to-win. Присоединяйтесь к бесплатному плейтесту в Steam 24/7.",
    "footer.description": "MMORPG, вдохновлённая классикой и открыто создаваемая сольным разработчиком. Заслуженный прогресс, живой мир и никакого магазина за реальные деньги.", "footer.game": "Игра", "footer.community": "Сообщество", "footer.shape": "Создавайте Elegon", "footer.world": "Мир", "footer.vision": "Видение", "footer.feedback": "Доска отзывов", "footer.rights": "Создано в одиночку с любовью. Все права защищены.", "footer.london": "Создано в Лондоне",
    "changelog.title": "Список изменений и заметки к патчам", "changelog.description": "Все заметки к патчам Elegon в одном месте: последние исправления, улучшения и новинки открытого плейтеста Steam 24/7.", "changelog.today": "Сегодня", "changelog.yesterday": "Вчера", "changelog.daysAgo": "дней назад", "world.weekly": "Еженедельно",
    "world.eyebrow": "Добро пожаловать, путник", "world.title": "Ты не избранный герой", "world.intro": "Привет, я Keone, разработчик Elegon. Я начал этот проект, потому что всегда любил этот жанр, но в последние годы стало труднее найти по-настоящему увлекательные онлайн-миры, которые ценят время и усилия игроков.", "world.identity": "Elegon — постоянно работающая MMORPG с открытым миром. Ты не избранный герой, а лишь часть большой истории.", "world.adventure": "Становись сильнее, побеждай могучих врагов, заводи друзей и сражайся со злом ради величайших наград мира.", "world.playtest": "Elegon разрабатывается открыто. Присоединяйся к круглосуточному плейтесту в Steam и помогай формировать игру своими отзывами. После версии 1.0 мир продолжит расти и меняться.", "world.nowOpen": "Уже открыто", "world.playtestLabel": "Плейтест в Steam 24/7", "world.noP2w": "Никакого pay-to-win. Никогда.", "world.statPlaytest": "Открытый плейтест в Steam", "world.statDevlogs": "Еженедельные дневники на YouTube", "world.statShop": "Товаров в игровом магазине", "world.statPlatforms": "Платформы: Windows, Linux и macOS",
    "features.eyebrow": "Создай свою легенду", "features.title": "Что ждёт тебя в Elegon", "features.intro": "Мир, вдохновлённый MMORPG, определившими жанр, создан для игроков, чьё время имеет значение.", "features.p1.tag": "Развитие", "features.p1.title": "Прогресс, которого ты добился", "features.p1.text": "Становись сильнее благодаря времени, усилиям и приключениям. Открывай классовые заклинания при повышении уровня и развивай героя талантами.", "features.p2.tag": "Исследование", "features.p2.title": "Постоянно живой мир", "features.p2.text": "Исследуй открытый мир вместе с другими игроками. По мере его роста будут появляться новые зоны и мировые боссы.", "features.p3.tag": "Испытание", "features.p3.title": "Разломы и редкая добыча", "features.p3.text": "Проходи разломы и сражайся с финальными боссами, чтобы получить шанс на редчайшие награды, включая ездовых животных.", "features.p4.tag": "Общение", "features.p4.title": "Приключения вместе", "features.p4.text": "Заводи друзей, собирай группу и вместе противостой злу. Некоторые враги слишком опасны для одиночного боя.", "features.p5.tag": "Открытия", "features.p5.title": "Компендиум", "features.p5.text": "Записывай всё, что открываешь в путешествии, и стремись заполнить последний процент коллекции.", "features.p6.tag": "Честная игра", "features.p6.title": "Честность заложена в основу", "features.p6.text": "Простая подписка. Никакого магазина в игре, косметики на продажу и преимуществ за деньги.",
    "devlogs.eyebrow": "Из кузницы", "devlogs.title": "Еженедельные дневники разработки", "devlogs.p1": "Подпишись на YouTube-канал, чтобы следить за созданием Elegon: каждую неделю выходят новости и видео о ходе разработки.", "devlogs.p2": "Для меня важно открыто создавать Elegon вместе с сообществом. Ваши отзывы и идеи помогают формировать игру, а обновления рассказывают, как развивается мир.", "devlogs.subscribe": "Подписаться на YouTube", "devlogs.changelog": "Читать список изменений",
    "vision.eyebrow": "Зачем существует Elegon", "vision.title": "Видение", "vision.quote": "Прогресс в Elegon должен быть заслуженным.", "vision.credit": "Keone, создатель Elegon", "vision.pillar": "Принцип", "vision.p1.title": "Дух классических игр", "vision.p1.text": "Elegon стремится создать онлайн-мир, вдохновлённый классическими MMORPG, ранними версиями World of Warcraft и другими ролевыми играми, сформировавшими жанр. Их миры были значимыми, социальными и интересными для исследования. Elegon возвращает этот дух и использует современные идеи, когда они улучшают игровой опыт.", "vision.p2.title": "Заслужить, а не купить", "vision.p2.text": "Персонаж становится сильнее благодаря времени, усилиям и приключениям, а не покупкам. В игре не будет магазина косметики или предметов, дающих преимущество. Ежемесячная подписка поддержит разработку и позволит сосредоточиться на мире и впечатлениях игроков.", "vision.p3.title": "Мир, созданный надолго", "vision.p3.text": "Elegon — долгосрочный проект, созданный с увлечением: живой мир, который будет расти и развиваться годами. Я хочу создать место, куда игроки смогут вкладывать силы, возвращаться и чувствовать себя частью мира.",
    "updates.eyebrow": "Хроники разработки", "updates.title": "Последние обновления", "updates.intro": "Elegon создаётся открыто и постоянно обновляется. Вот что недавно появилось в мире.", "updates.shipped": "Выпущено изменений", "updates.since": "с", "updates.viewAll": "Все изменения", "updates.latest": "Последнее",
    "supporters.eyebrow": "Зал героев", "supporters.title": "Поклонники на Patreon", "supporters.intro": "Щедрость этих искателей приключений помогает создавать Elegon. Их имена вписаны в историю мира.", "supporters.loading": "Призываем поклонников…", "supporters.hero": "герой", "supporters.heroes": "героев", "supporters.become": "Поддержать проект", "supporters.legendary": "Легендарные покровители", "supporters.epic": "Эпические покровители", "supporters.rare": "Редкие покровители",
    "faq.eyebrow": "Беседы в таверне", "faq.title": "Частые вопросы", "faq.more": "Остались вопросы?", "faq.discordText": "Заходи в Discord. Задавай любые вопросы, делись идеями и знакомься с другими искателями приключений.", "faq.join": "Присоединиться к Discord", "faq.q1": "Как будет финансироваться Elegon?", "faq.a1": "Elegon будет поддерживаться одной ежемесячной подпиской. В игре никогда не появится магазин косметики или предметов, дающих преимущество за деньги. За пределами подписки возможен мерч, но не товары внутри мира Elegon.", "faq.q2": "На каких платформах доступна Elegon?", "faq.a2": "В Elegon можно играть через Steam на Windows, Linux и macOS. Сейчас для версии macOS нужен небольшой обходной шаг, так как приложение ещё не подписано; это будет исправлено в будущем.", "faq.q3": "Кто ты? Ты уже создавал что-то подобное?", "faq.a3": "Я Keone, разработчик программного обеспечения из Лондона. Я работаю полный день вне игровой индустрии и создаю Elegon в свободное время. У меня около десяти лет опыта, а Elegon — мой первый крупный игровой проект.", "faq.q4": "Какие технологии использует Elegon?", "faq.a4": "Elegon создана на движке Godot с открытым исходным кодом, который гибок и подходит проекту. Для сети и сервера используется SpacetimeDB — современная высокопроизводительная платформа для онлайн-миров.", "faq.q5": "Как поддержать разработку Elegon?", "faq.a5": "Мы ценим поддержку, но она не обязательна. Проект можно поддержать на Patreon или Ko-fi. Просмотр дневников, участие в плейтесте и отзывы тоже очень помогают.", "faq.q6": "Можно ли делать видео, стримы или статьи об Elegon?", "faq.a6": "Конечно! Вы можете создавать любой контент об Elegon: видео на YouTube, стримы, статьи и многое другое. Разрешение не требуется, и мне будет очень интересно увидеть ваши работы, так что делитесь ими в Discord.",
    "cta.eyebrow": "Путешествие начинается", "cta.title": "Твоё приключение ждёт", "cta.text": "Добавь Elegon в список желаемого Steam, присоединяйся к плейтесту 24/7 и помоги создать мир, который останется надолго.", "cta.wishlist": "В список желаемого Steam", "cta.discord": "Присоединиться к Discord", "footer.engine": "Создано на Godot и SpacetimeDB",
  },
  "zh-CN": {
    "nav.world": "世界", "nav.features": "特色", "nav.devlogs": "开发日志", "nav.vision": "愿景", "nav.faq": "常见问题", "nav.changelog": "更新日志", "nav.feedback": "反馈", "nav.roadmap": "路线图", "nav.wishlist": "加入愿望单", "nav.wishlistSteam": "加入 Steam 愿望单", "nav.menu": "菜单", "nav.openMenu": "打开菜单", "nav.more": "更多", "nav.language": "切换语言", "nav.primary": "主导航", "nav.mobile": "移动导航", "nav.footer": "页脚导航", "nav.home": "Elegon 首页",
    "hero.live": "Steam 全天候开放测试现已开启", "hero.tagline": "一款致敬经典的 MMORPG", "hero.description": "踏入一个成长至关重要、冒险正在等待你的世界。", "hero.community": "加入社区", "hero.begin": "开始你的旅程", "hero.platforms": "支持的平台",
    "seo.title": "Elegon：一款致敬经典的独立 MMORPG", "seo.description": "由独立开发者打造、致敬经典的 MMORPG。努力终有回报，鲜活的开放世界，绝不付费取胜。现在即可在 Steam 加入全天候免费测试。",
    "footer.description": "一款由独立开发者公开打造、致敬经典的 MMORPG。努力终有回报，世界鲜活永续，绝不设现金商城。", "footer.game": "游戏", "footer.community": "社区", "footer.shape": "塑造 Elegon", "footer.world": "世界", "footer.vision": "愿景", "footer.feedback": "反馈板", "footer.rights": "独立开发，倾注热爱。保留所有权利。", "footer.london": "于伦敦铸就",
    "changelog.title": "更新日志与补丁说明", "changelog.description": "在这里查看 Elegon 的全部补丁说明：Steam 全天候开放测试中的最新修复、改进与新内容。", "changelog.today": "今天", "changelog.yesterday": "昨天", "changelog.daysAgo": "天前", "world.weekly": "每周",
    "world.eyebrow": "欢迎，旅人", "world.title": "你并非天选之人", "world.intro": "你好，我是 Keone，一名独立开发者，正在打造 Elegon。我一直热爱 MMORPG，但近些年，真正引人入胜、尊重玩家时间与付出的在线世界越来越难得，因此我开始了这个项目。", "world.identity": "Elegon 是一款全天在线的开放世界 MMORPG。你不是天选英雄，而是宏大故事中的一员。", "world.adventure": "随着时间不断成长，击败强敌，结识伙伴，与世界的邪恶势力抗争，追寻最丰厚的奖励。", "world.playtest": "Elegon 正在开放开发中。欢迎加入 Steam 全天候测试，通过反馈一起塑造游戏。正式版 1.0 发布后，世界仍会持续扩展与进化。", "world.nowOpen": "现已开放", "world.playtestLabel": "Steam 全天候测试", "world.noP2w": "绝不付费取胜。", "world.statPlaytest": "Steam 开放测试", "world.statDevlogs": "YouTube 每周开发日志", "world.statShop": "商城道具", "world.statPlatforms": "平台：Windows、Linux 和 macOS",
    "features.eyebrow": "铸就你的传奇", "features.title": "Elegon 中的精彩内容", "features.intro": "致敬定义 MMORPG 类型的经典作品，为珍惜时间价值的玩家打造一个世界。", "features.p1.tag": "成长", "features.p1.title": "努力换来的成长", "features.p1.text": "通过时间、努力与冒险变得更强。升级解锁职业法术，并用天赋塑造角色。", "features.p2.tag": "探索", "features.p2.title": "永不停歇的世界", "features.p2.text": "与其他玩家共同探索持续运行的开放世界，世界还会不断加入新区域与世界首领。", "features.p3.tag": "挑战", "features.p3.title": "裂隙与稀有战利品", "features.p3.text": "挑战副本裂隙及其最终首领，赢取世界上最稀有奖励的机会，包括坐骑。", "features.p4.tag": "社交", "features.p4.title": "结伴冒险", "features.p4.text": "结交伙伴、组建队伍，并肩对抗世界的邪恶势力。有些敌人并不适合独自面对。", "features.p5.tag": "发现", "features.p5.title": "探索图鉴", "features.p5.text": "记录旅途中发现的一切，追逐探索完成度的最后几个百分点。", "features.p6.tag": "公平游戏", "features.p6.title": "公平融入设计", "features.p6.text": "简单订阅制。没有游戏内商城，不售卖外观道具，绝不付费取胜。",
    "devlogs.eyebrow": "来自锻造炉", "devlogs.title": "每周开发日志", "devlogs.p1": "订阅 YouTube 频道，通过每周更新和幕后开发日志，持续了解 Elegon 的开发进展。", "devlogs.p2": "对我来说，与社区公开开发 Elegon 非常重要。大家的反馈与想法能帮助塑造游戏，每次更新也会带你了解世界的成长。", "devlogs.subscribe": "订阅 YouTube", "devlogs.changelog": "阅读更新日志",
    "vision.eyebrow": "Elegon 为何而生", "vision.title": "我们的愿景", "vision.quote": "在 Elegon，成长应当靠努力赢得。", "vision.credit": "Elegon 创作者 Keone", "vision.pillar": "理念", "vision.p1.title": "经典 MMORPG 的精神", "vision.p1.text": "Elegon 希望打造一个致敬经典 MMORPG 的在线世界，例如早期《魔兽世界》以及其他定义这一类型的角色扮演游戏。那些世界充满意义、社交乐趣，也值得探索。Elegon 将延续这份精神，并在现代设计确实能改善体验时加以借鉴。", "vision.p2.title": "靠努力获得，而非购买", "vision.p2.text": "角色会通过时间、付出与冒险成长，而非消费。游戏内不会出售外观或付费取胜道具。简单的月度订阅将支持开发，让我们专注于世界品质与玩家体验。", "vision.p3.title": "一个长久发展的世界", "vision.p3.text": "Elegon 是一个长期投入的热爱项目：一个未来多年仍会不断成长与变化的鲜活世界。作为独立开发者，我希望创造一个让玩家愿意投入、再次归来并真正感到归属的地方。",
    "updates.eyebrow": "开发纪事", "updates.title": "最新更新", "updates.intro": "Elegon 持续公开开发与更新。来看看最近有哪些新内容加入了世界。", "updates.shipped": "已发布改动", "updates.since": "自", "updates.viewAll": "查看完整更新日志", "updates.latest": "最新",
    "supporters.eyebrow": "英雄殿堂", "supporters.title": "Patreon 支持者", "supporters.intro": "这些冒险者的慷慨支持让 Elegon 得以实现。他们的名字将铭刻在世界的历史中。", "supporters.loading": "正在召唤支持者……", "supporters.hero": "位英雄", "supporters.heroes": "位英雄", "supporters.become": "成为支持者", "supporters.legendary": "传奇支持者", "supporters.epic": "史诗支持者", "supporters.rare": "稀有支持者",
    "faq.eyebrow": "酒馆闲谈", "faq.title": "常见问题", "faq.more": "还有疑问吗？", "faq.discordText": "欢迎来 Discord 坐坐。提出任何问题、分享想法，也认识其他冒险者。", "faq.join": "加入 Discord", "faq.q1": "Elegon 将如何盈利？", "faq.a1": "Elegon 将采用单一月度订阅。游戏内绝不会出售外观道具或付费取胜道具。订阅之外可能会有周边商品，但不会销售存在于 Elegon 世界中的物品。", "faq.q2": "Elegon 支持哪些平台？", "faq.a2": "Elegon 可通过 Steam 在 Windows、Linux 和 macOS 上游玩。目前 macOS 版本需要一个简单的额外步骤，因为应用尚未签名；未来会解决这个问题。", "faq.q3": "你是谁？之前做过类似项目吗？", "faq.a3": "我是 Keone，一名居住在伦敦的软件开发者。我在非游戏公司全职工作，利用业余时间开发 Elegon。我有约十年的软件开发经验，Elegon 是我的第一个大型游戏项目。", "faq.q4": "Elegon 使用什么技术？", "faq.a4": "Elegon 使用开源且灵活的 Godot 游戏引擎。网络与后端系统采用 SpacetimeDB，这是适合持久在线世界的现代高性能平台。", "faq.q5": "如何支持 Elegon 的开发？", "faq.a5": "非常感谢你的支持，但完全没有义务。你可以通过 Patreon 或 Ko-fi 支持项目。观看开发日志、参与测试和提供反馈也能带来很大帮助。", "faq.q6": "我可以制作关于 Elegon 的视频、直播或文章吗？", "faq.a6": "当然可以！非常欢迎你围绕 Elegon 创作内容，比如 YouTube 视频、直播、文章等等。无需获得许可，我也很期待看到你的作品，欢迎在 Discord 中分享。",
    "cta.eyebrow": "旅程即将开始", "cta.title": "冒险正等待着你", "cta.text": "将 Elegon 加入 Steam 愿望单，参与全天候测试，一起打造一个长久发展的世界。", "cta.wishlist": "加入 Steam 愿望单", "cta.discord": "加入 Discord", "footer.engine": "使用 Godot 与 SpacetimeDB 打造",
  },
} as const;

const localizedPatchNotes: Record<number, Partial<Record<SupportedLocale, string>>> = {
  561: {
    de: "Charakterinventar auf 160 Plätze erweitert", es: "Se amplió el inventario del personaje a 160 espacios", fr: "Inventaire des personnages agrandi à 160 emplacements", "pt-BR": "Inventário do personagem ampliado para 160 espaços", ru: "Размер инвентаря персонажа увеличен до 160 ячеек", "zh-CN": "角色背包容量扩展至 160 格",
  },
  560: {
    de: "Kartenoberfläche aktualisiert", es: "Se actualizó la interfaz del mapa", fr: "Interface de la carte mise à jour", "pt-BR": "Interface do mapa atualizada", ru: "Обновлён интерфейс карты", "zh-CN": "地图界面已更新",
  },
  559: {
    de: "Beuteoberfläche verbessert und flüssiger gestaltet", es: "Se mejoró la interfaz de botín para que resulte más ágil y satisfactoria", fr: "Interface de butin améliorée pour une expérience plus fluide et agréable", "pt-BR": "Interface de saque aprimorada para ser mais ágil e satisfatória", ru: "Интерфейс добычи стал быстрее и приятнее", "zh-CN": "优化战利品界面，让拾取更加流畅顺手",
  },
  558: {
    de: "Optik und Animationen der EP-Leiste verbessert", es: "Se mejoraron los gráficos y las animaciones de la barra de EXP", fr: "Visuels et animations de la barre d'EXP améliorés", "pt-BR": "Visuais e animações da barra de EXP aprimorados", ru: "Улучшены внешний вид и анимация полосы опыта", "zh-CN": "优化经验条的视觉效果与动画",
  },
  557: {
    de: "Fehler behoben, durch den an Aktionsleisten gebundene Gegenstände falsche Werte anzeigten", es: "Se corrigió un error que impedía mostrar correctamente las estadísticas de los objetos vinculados a las barras de acción", fr: "Correction d'un problème d'affichage des statistiques des objets associés aux barres d'action", "pt-BR": "Corrigido um problema que impedia a exibição correta dos atributos de itens vinculados às barras de ação", ru: "Исправлена ошибка: характеристики предметов, привязанных к панелям действий, отображались неверно", "zh-CN": "修复了快捷栏绑定物品未显示正确属性的问题",
  },
};

export function useLocale() {
  const route = useRoute();
  const locale = computed<SupportedLocale>(() => {
    const candidate = route.path.match(/^\/(de|es|fr|pt-BR|ru|zh-CN)(?:\/|$)/)?.[1];
    return typeof candidate === "string" && SUPPORTED_LOCALES.includes(candidate as SupportedLocale)
      ? (candidate as SupportedLocale)
      : "en";
  });
  const t = (key: keyof typeof messages.en) => messages[locale.value][key] ?? messages.en[key];
  const translatePatchNote = (id: number, fallback: string) => localizedPatchNotes[id]?.[locale.value] ?? fallback;
  const localePath = (path = "/", target = locale.value) => {
    const normalized = path.startsWith("/") ? path : `/${path}`;
    return target === "en" ? normalized : `/${target}${normalized === "/" ? "" : normalized}`;
  };
  return { locale, t, localePath, translatePatchNote };
}
