// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  friendAccountId: __t.identity().name("friend_account_id"),
  friendCharacterId: __t.u64().name("friend_character_id"),
  friendName: __t.string().name("friend_name"),
  friendTag: __t.i32().name("friend_tag"),
  isOnline: __t.bool().name("is_online"),
});
