// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  otherCharacterId: __t.u64().name("other_character_id"),
  groupedCount: __t.i32().name("grouped_count"),
  whisperCount: __t.i32().name("whisper_count"),
  tradeCount: __t.i32().name("trade_count"),
  firstMetAt: __t.timestamp().name("first_met_at"),
  lastInteractionAt: __t.timestamp().name("last_interaction_at"),
});
