// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DbVector3,
} from "./types";


export default __t.row({
  id: __t.u64(),
  accountId: __t.identity().name("account_id"),
  name: __t.string(),
  raceSelection: __t.i32().name("race_selection"),
  sexSelection: __t.i32().name("sex_selection"),
  classSelection: __t.i32().name("class_selection"),
  get position() {
    return DbVector3;
  },
  chunkX: __t.i32().name("chunk_x"),
  chunkZ: __t.i32().name("chunk_z"),
  rotation: __t.f64(),
  level: __t.i32(),
  xp: __t.u64(),
  health: __t.i32(),
  maxHealth: __t.i32().name("max_health"),
  energy: __t.i32(),
  maxEnergy: __t.i32().name("max_energy"),
  vitality: __t.i32(),
  fortitude: __t.i32(),
  strength: __t.i32(),
  grace: __t.i32(),
  alacrity: __t.i32(),
  tempo: __t.i32(),
  createdAt: __t.timestamp().name("created_at"),
  deletedAt: __t.timestamp().name("deleted_at"),
  lastPlayed: __t.timestamp().name("last_played"),
  isWeaponDrawn: __t.bool().name("is_weapon_drawn"),
  tag: __t.i32(),
  gold: __t.i32(),
});
