// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  spellId: __t.u64().name("spell_id"),
  sourceCharacterId: __t.u64().name("source_character_id"),
  targetCharacterId: __t.u64().name("target_character_id"),
  targetEntityId: __t.u32().name("target_entity_id"),
  targetType: __t.u8().name("target_type"),
  effectType: __t.i32().name("effect_type"),
  isBuff: __t.bool().name("is_buff"),
  appliedAtUnix: __t.i64().name("applied_at_unix"),
  expiresAtUnix: __t.i64().name("expires_at_unix"),
  nextTickAtUnix: __t.i64().name("next_tick_at_unix"),
  tickIntervalMs: __t.i32().name("tick_interval_ms"),
  amount: __t.f32(),
});
