// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  cadence: __t.i32(),
  cycleNumber: __t.i32().name("cycle_number"),
  kind: __t.i32(),
  targetId: __t.u32().name("target_id"),
  zoneName: __t.string().name("zone_name"),
  requiredAmount: __t.i32().name("required_amount"),
  points: __t.i32(),
  recommendedLevel: __t.i32().name("recommended_level"),
  title: __t.string(),
  description: __t.string(),
  hasMarker: __t.bool().name("has_marker"),
  markerX: __t.f32().name("marker_x"),
  markerZ: __t.f32().name("marker_z"),
  markerRadius: __t.f32().name("marker_radius"),
  sortOrder: __t.i32().name("sort_order"),
});
