// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  cadence: __t.i32().primaryKey(),
  cycleNumber: __t.i32().name("cycle_number"),
  startsAtUnix: __t.i64().name("starts_at_unix"),
  endsAtUnix: __t.i64().name("ends_at_unix"),
});
