// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  name: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  rotation: __t.f32(),
  level: __t.i32(),
  scale: __t.f32(),
  modelPath: __t.string(),
  greetingText: __t.string(),
  targetId: __t.string(),
};
