// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  name: __t.string(),
  description: __t.string(),
  iconTexture: __t.string(),
  castTime: __t.f32(),
  cooldown: __t.f32(),
  minRange: __t.f32(),
  maxRange: __t.f32(),
  resourceGenerated: __t.i32(),
  resourceCost: __t.i32(),
  damage: __t.f32(),
  classRequired: __t.i32(),
  levelRequired: __t.i32(),
  isInstant: __t.bool(),
  activeEffectType: __t.i32(),
  activeEffectIsBuff: __t.bool(),
  activeEffectIsDurationless: __t.bool(),
  activeEffectTarget: __t.i32(),
  activeEffectDuration: __t.f32(),
  activeEffectTickInterval: __t.f32(),
  activeEffectAmount: __t.f32(),
  targetId: __t.string(),
};
