// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  itemId: __t.i32().primaryKey().name("item_id"),
  tier: __t.i32(),
  primaryStatId: __t.i32().name("primary_stat_id"),
  primaryBaseCentis: __t.i32().name("primary_base_centis"),
  primaryPerLevelCentis: __t.i32().name("primary_per_level_centis"),
  secondaryStatId: __t.i32().name("secondary_stat_id"),
  secondaryBaseCentis: __t.i32().name("secondary_base_centis"),
  secondaryPerLevelCentis: __t.i32().name("secondary_per_level_centis"),
  maxLevel: __t.i32().name("max_level"),
  itemLevelRequirement: __t.i32().name("item_level_requirement"),
});
