// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  accountId: __t.identity().primaryKey().name("account_id"),
  loginMethod: __t.string().name("login_method"),
  providerId: __t.string().name("provider_id"),
  preferredUsername: __t.string().name("preferred_username"),
  picture: __t.string(),
  isSteam: __t.bool().name("is_steam"),
  ownsConfiguredSteamApp: __t.bool().name("owns_configured_steam_app"),
  connectedAt: __t.timestamp().name("connected_at"),
  isQueued: __t.bool().name("is_queued"),
  queuePosition: __t.i32().name("queue_position"),
});
