// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  characterId: __t.u64().name("character_id"),
  spellId: __t.u64().name("spell_id"),
  damage: __t.f32(),
  healing: __t.f32(),
  castTime: __t.f32().name("cast_time"),
  activeEffectAmount: __t.f32().name("active_effect_amount"),
  talentRank: __t.i32().name("talent_rank"),
  isUnlocked: __t.bool().name("is_unlocked"),
});
