// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  characterId: __t.u64().primaryKey().name("character_id"),
  headSlotItemInstanceId: __t.i32().name("head_slot_item_instance_id"),
  neckSlotItemInstanceId: __t.i32().name("neck_slot_item_instance_id"),
  backSlotItemInstanceId: __t.i32().name("back_slot_item_instance_id"),
  shoulderSlotItemInstanceId: __t.i32().name("shoulder_slot_item_instance_id"),
  chestSlotItemInstanceId: __t.i32().name("chest_slot_item_instance_id"),
  waistSlotItemInstanceId: __t.i32().name("waist_slot_item_instance_id"),
  legSlotItemInstanceId: __t.i32().name("leg_slot_item_instance_id"),
  footSlotItemInstanceId: __t.i32().name("foot_slot_item_instance_id"),
  mainHandSlotItemInstanceId: __t.i32().name("main_hand_slot_item_instance_id"),
  offHandSlotItemInstanceId: __t.i32().name("off_hand_slot_item_instance_id"),
});
