// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DbVector3,
} from "./types";


export default __t.row({
  characterId: __t.u64().primaryKey().name("character_id"),
  get position() {
    return DbVector3;
  },
  chunkX: __t.i32().name("chunk_x"),
  chunkZ: __t.i32().name("chunk_z"),
  rotation: __t.f64(),
  isWeaponDrawn: __t.bool().name("is_weapon_drawn"),
});
