// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  characterId: __t.u64().name("character_id"),
  entryType: __t.string().name("entry_type"),
  entryId: __t.u32().name("entry_id"),
  discoveredAt: __t.timestamp().name("discovered_at"),
  isSeen: __t.bool().name("is_seen"),
  bestQuality: __t.i32().name("best_quality"),
});
