// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DbVector3,
} from "./types";


export default __t.row({
  characterId: __t.u64().primaryKey().name("character_id"),
  npcId: __t.u32().name("npc_id"),
  get position() {
    return DbVector3;
  },
  rotation: __t.f64(),
});
