// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  characterId: __t.u64().name("character_id"),
  weekNumber: __t.i32().name("week_number"),
  points: __t.i32(),
  tasksCompleted: __t.i32().name("tasks_completed"),
  dailiesCompleted: __t.i32().name("dailies_completed"),
  breachClears: __t.i32().name("breach_clears"),
  bestBreachMapId: __t.string().name("best_breach_map_id"),
  bestBreachLevel: __t.i32().name("best_breach_level"),
  highestInstability: __t.u32().name("highest_instability"),
  isClaimed: __t.bool().name("is_claimed"),
  claimedAtUnix: __t.i64().name("claimed_at_unix"),
});
