// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  accountId: __t.identity().name("account_id"),
  name: __t.string(),
  raceSelection: __t.i32().name("race_selection"),
  sexSelection: __t.i32().name("sex_selection"),
  classSelection: __t.i32().name("class_selection"),
  createdAt: __t.timestamp().name("created_at"),
  deletedAt: __t.timestamp().name("deleted_at"),
  lastPlayed: __t.timestamp().name("last_played"),
  tag: __t.i32(),
});
