// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  characterId: __t.u64().name("character_id"),
  spellId: __t.i32().name("spell_id"),
  amount: __t.f32(),
  entityId: __t.i32().name("entity_id"),
  isCrit: __t.bool().name("is_crit"),
  chunkX: __t.i32().name("chunk_x"),
  chunkZ: __t.i32().name("chunk_z"),
});
