// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  itemId: __t.i32().name("item_id"),
  effectKind: __t.i32().name("effect_kind"),
  statId: __t.i32().name("stat_id"),
  amount: __t.f32(),
  durationSeconds: __t.f32().name("duration_seconds"),
  tickIntervalSeconds: __t.f32().name("tick_interval_seconds"),
  sortOrder: __t.i32().name("sort_order"),
});
