// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  affinity: __t.i32(),
  tier: __t.i32(),
  itemId: __t.i32().name("item_id"),
  requiredCookingSkill: __t.i32().name("required_cooking_skill"),
  cookSeconds: __t.f32().name("cook_seconds"),
  skillXp: __t.i32().name("skill_xp"),
});
