// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DbVector3,
} from "./types";


export default __t.row({
  characterId: __t.u64().primaryKey().name("character_id"),
  get position() {
    return DbVector3;
  },
  instanceId: __t.u32().name("instance_id"),
  chunkX: __t.i32().name("chunk_x"),
  chunkZ: __t.i32().name("chunk_z"),
  litFromX: __t.f32().name("lit_from_x"),
  litFromY: __t.f32().name("lit_from_y"),
  litFromZ: __t.f32().name("lit_from_z"),
  expiresAtUnix: __t.i64().name("expires_at_unix"),
});
