// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DbVector3,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  enemyEntityId: __t.u32().name("enemy_entity_id"),
  instanceId: __t.u32().name("instance_id"),
  chunkX: __t.i32().name("chunk_x"),
  chunkZ: __t.i32().name("chunk_z"),
  get position() {
    return DbVector3;
  },
  directionX: __t.f32().name("direction_x"),
  directionZ: __t.f32().name("direction_z"),
  radius: __t.f32(),
  halfAngle: __t.f32().name("half_angle"),
  startedAtUnix: __t.i64().name("started_at_unix"),
  activatesAtUnix: __t.i64().name("activates_at_unix"),
  expiresAtUnix: __t.i64().name("expires_at_unix"),
  tickIntervalMs: __t.i32().name("tick_interval_ms"),
  power: __t.f32(),
  spellId: __t.u64().name("spell_id"),
});
