// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  enemyEntityId: __t.u32().primaryKey().name("enemy_entity_id"),
  spellId: __t.u64().name("spell_id"),
  abilitySlot: __t.i32().name("ability_slot"),
  rosterLength: __t.i32().name("roster_length"),
  targetCharacterId: __t.u64().name("target_character_id"),
  startedAtUnix: __t.i64().name("started_at_unix"),
  completesAtUnix: __t.i64().name("completes_at_unix"),
  instanceId: __t.u32().name("instance_id"),
  chunkX: __t.i32().name("chunk_x"),
  chunkZ: __t.i32().name("chunk_z"),
});
