// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  name: __t.string(),
  level: __t.i32(),
  xpReward: __t.i32().name("xp_reward"),
  moveSpeed: __t.f32().name("move_speed"),
  isAggressive: __t.bool().name("is_aggressive"),
  maxHealth: __t.i32().name("max_health"),
  attackDamage: __t.i32().name("attack_damage"),
  respawnSeconds: __t.i32().name("respawn_seconds"),
  aggroRange: __t.f32().name("aggro_range"),
  maxDistanceFromSpawn: __t.f32().name("max_distance_from_spawn"),
  modelPath: __t.string().name("model_path"),
  deathSoundPath: __t.string().name("death_sound_path"),
  wanderRadius: __t.f32().name("wander_radius"),
  scale: __t.f32(),
  attackSoundPath: __t.string().name("attack_sound_path"),
});
