// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DbVector3,
} from "./types";


export default __t.row({
  id: __t.i32().primaryKey(),
  enemyId: __t.i32().name("enemy_id"),
  itemId: __t.i32().name("item_id"),
  quantity: __t.i32(),
  get position() {
    return DbVector3;
  },
  chunkX: __t.i32().name("chunk_x"),
  chunkZ: __t.i32().name("chunk_z"),
  characterId: __t.u64().name("character_id"),
  goldAmount: __t.i32().name("gold_amount"),
  qualityLevel: __t.i32().name("quality_level"),
});
