// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DbVector3,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  entityTypeId: __t.u8().name("entity_type_id"),
  entityDataId: __t.u32().name("entity_data_id"),
  get spawnPosition() {
    return DbVector3.name("spawn_position");
  },
  get position() {
    return DbVector3;
  },
  rotation: __t.f32(),
  health: __t.i32(),
  chunkX: __t.i32().name("chunk_x"),
  chunkZ: __t.i32().name("chunk_z"),
  targets: __t.array(__t.u64()),
  isAlive: __t.bool().name("is_alive"),
  respawnAtUnix: __t.i64().name("respawn_at_unix"),
  isAttacking: __t.bool().name("is_attacking"),
  isReturningToSpawn: __t.bool().name("is_returning_to_spawn"),
  targetX: __t.f32().name("target_x"),
  targetZ: __t.f32().name("target_z"),
  nextMoveTimeUnix: __t.i64().name("next_move_time_unix"),
  targetCharacterId: __t.option(__t.u64()).name("target_character_id"),
  nextAttackTimeUnix: __t.i64().name("next_attack_time_unix"),
  lastUpdateUnix: __t.i64().name("last_update_unix"),
  lastWanderUnix: __t.i64().name("last_wander_unix"),
});
