// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  itemId: __t.i32().primaryKey().name("item_id"),
  levelRequirement: __t.i32().name("level_requirement"),
  requiredClass: __t.i32().name("required_class"),
  quality: __t.i32(),
  damage: __t.f32(),
  armor: __t.f32(),
  vitality: __t.i32(),
  fortitude: __t.i32(),
  strength: __t.i32(),
  grace: __t.i32(),
  alacrity: __t.i32(),
  tempo: __t.i32(),
  slot: __t.string(),
  weaponHand: __t.string().name("weapon_hand"),
});
