// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  itemId: __t.i32().primaryKey().name("item_id"),
  zone: __t.string(),
  minFishingLevel: __t.i32().name("min_fishing_level"),
  weight: __t.i32(),
  rarity: __t.i32(),
  skillXp: __t.i32().name("skill_xp"),
});
