// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  fromNpcId: __t.option(__t.i32()).name("from_npc_id"),
  fromCharId: __t.option(__t.u64()).name("from_char_id"),
  toNpcId: __t.option(__t.i32()).name("to_npc_id"),
  toCharId: __t.option(__t.u64()).name("to_char_id"),
  action: __t.string(),
  amount: __t.option(__t.f32()),
  timestamp: __t.timestamp(),
  duration: __t.option(__t.f32()),
  chunkX: __t.i32().name("chunk_x"),
  chunkZ: __t.i32().name("chunk_z"),
});
