// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.0 (commit 31fd1c8c3346dfec38dfcc2e89c2ecf457cf26ff).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AbandonQuestReducer from "./abandon_quest_reducer";
import AcceptPartyInviteReducer from "./accept_party_invite_reducer";
import AcceptQuestReducer from "./accept_quest_reducer";
import AddChangelogEntryReducer from "./add_changelog_entry_reducer";
import AddEnemyReducer from "./add_enemy_reducer";
import AddEnemyEntityReducer from "./add_enemy_entity_reducer";
import AddItemReducer from "./add_item_reducer";
import AddLootTableEntryReducer from "./add_loot_table_entry_reducer";
import AddNpcReducer from "./add_npc_reducer";
import AddNpcEntityReducer from "./add_npc_entity_reducer";
import AddQuestReducer from "./add_quest_reducer";
import AddSpellReducer from "./add_spell_reducer";
import AddWorldObjectReducer from "./add_world_object_reducer";
import AddWorldObjectEntityReducer from "./add_world_object_entity_reducer";
import BuyItemFromNpcReducer from "./buy_item_from_npc_reducer";
import CancelSpellCastReducer from "./cancel_spell_cast_reducer";
import CastArcSpellReducer from "./cast_arc_spell_reducer";
import CastAreaSpellReducer from "./cast_area_spell_reducer";
import CastMobilitySpellReducer from "./cast_mobility_spell_reducer";
import CastRecallReducer from "./cast_recall_reducer";
import CompleteQuestReducer from "./complete_quest_reducer";
import CreateCharacterReducer from "./create_character_reducer";
import DamageEnemyReducer from "./damage_enemy_reducer";
import DeclinePartyInviteReducer from "./decline_party_invite_reducer";
import DeleteAllEnemiesReducer from "./delete_all_enemies_reducer";
import DeleteAllEnemyEntitiesReducer from "./delete_all_enemy_entities_reducer";
import DeleteAllNpcEntitiesReducer from "./delete_all_npc_entities_reducer";
import DeleteAllNpcsReducer from "./delete_all_npcs_reducer";
import DeleteAllWorldObjectEntitiesReducer from "./delete_all_world_object_entities_reducer";
import DeleteAllWorldObjectsReducer from "./delete_all_world_objects_reducer";
import DeleteChangelogEntryReducer from "./delete_changelog_entry_reducer";
import DeleteCharacterReducer from "./delete_character_reducer";
import DeleteEnemyReducer from "./delete_enemy_reducer";
import DeleteItemReducer from "./delete_item_reducer";
import DeleteItemFromBagReducer from "./delete_item_from_bag_reducer";
import DeleteItemFromEquipmentReducer from "./delete_item_from_equipment_reducer";
import DeleteLootTableEntryReducer from "./delete_loot_table_entry_reducer";
import DeleteNpcReducer from "./delete_npc_reducer";
import DeleteQuestReducer from "./delete_quest_reducer";
import DeleteSpellReducer from "./delete_spell_reducer";
import DeleteWorldObjectReducer from "./delete_world_object_reducer";
import EnterWorldReducer from "./enter_world_reducer";
import EquipItemReducer from "./equip_item_reducer";
import ExitWorldReducer from "./exit_world_reducer";
import HealCharacterReducer from "./heal_character_reducer";
import InsertWoodPileAndNytheraQuestsReducer from "./insert_wood_pile_and_nythera_quests_reducer";
import InviteToPartyReducer from "./invite_to_party_reducer";
import JumpReducer from "./jump_reducer";
import LeavePartyReducer from "./leave_party_reducer";
import LootEnemyDropReducer from "./loot_enemy_drop_reducer";
import LootWorldObjectReducer from "./loot_world_object_reducer";
import MoveReducer from "./move_reducer";
import MoveItemReducer from "./move_item_reducer";
import PingReducer from "./ping_reducer";
import RepairCharacterSplitTablesReducer from "./repair_character_split_tables_reducer";
import RespawnCharacterReducer from "./respawn_character_reducer";
import SeedClassesReducer from "./seed_classes_reducer";
import SeedEnemiesReducer from "./seed_enemies_reducer";
import SeedItemsReducer from "./seed_items_reducer";
import SeedLevelRequirementsReducer from "./seed_level_requirements_reducer";
import SeedLootTablesReducer from "./seed_loot_tables_reducer";
import SeedNpcsReducer from "./seed_npcs_reducer";
import SeedQuestsReducer from "./seed_quests_reducer";
import SeedSpellsReducer from "./seed_spells_reducer";
import SeedStatDefinitionsReducer from "./seed_stat_definitions_reducer";
import SeedWorldObjectsReducer from "./seed_world_objects_reducer";
import SellItemToNpcReducer from "./sell_item_to_npc_reducer";
import SendMessageReducer from "./send_message_reducer";
import SetActionBarSpellReducer from "./set_action_bar_spell_reducer";
import SetWeaponDrawnReducer from "./set_weapon_drawn_reducer";
import UnequipItemReducer from "./unequip_item_reducer";
import UpdateChangelogEntryReducer from "./update_changelog_entry_reducer";
import UpdateEnemyReducer from "./update_enemy_reducer";
import UpdateExistingCharacterInventorySlotsReducer from "./update_existing_character_inventory_slots_reducer";
import UpdateItemReducer from "./update_item_reducer";
import UpdateLootTableEntryReducer from "./update_loot_table_entry_reducer";
import UpdateNpcReducer from "./update_npc_reducer";
import UpdateQuestReducer from "./update_quest_reducer";
import UpdateSpellReducer from "./update_spell_reducer";
import UpdateTagsReducer from "./update_tags_reducer";
import UpdateWorldObjectReducer from "./update_world_object_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AccountCharactersRow from "./account_characters_table";
import ActiveEffectsRow from "./active_effects_table";
import AuthSessionsRow from "./auth_sessions_table";
import BagSlotsRow from "./bag_slots_table";
import BagsRow from "./bags_table";
import ChangelogEntriesRow from "./changelog_entries_table";
import CharacterCurrenciesRow from "./character_currencies_table";
import CharacterEquipmentRow from "./character_equipment_table";
import CharacterMapFogRow from "./character_map_fog_table";
import CharacterStatesRow from "./character_states_table";
import CharacterStatsRow from "./character_stats_table";
import CharactersRow from "./characters_table";
import CharactersOfflineRow from "./characters_offline_table";
import ClassesRow from "./classes_table";
import CombatLogRow from "./combat_log_table";
import EnemiesRow from "./enemies_table";
import EnemyLootDropsRow from "./enemy_loot_drops_table";
import EntitiesRow from "./entities_table";
import GameEventRow from "./game_event_table";
import ItemInstancesRow from "./item_instances_table";
import ItemsRow from "./items_table";
import LevelRequirementsRow from "./level_requirements_table";
import LootTableEntriesRow from "./loot_table_entries_table";
import MessageEventRow from "./message_event_table";
import NpcsRow from "./npcs_table";
import PartiesRow from "./parties_table";
import PartyInvitesRow from "./party_invites_table";
import PartyMembersRow from "./party_members_table";
import QuestProgressRow from "./quest_progress_table";
import QuestsRow from "./quests_table";
import QuestsWithProgressRow from "./quests_with_progress_table";
import ServerSettingsRow from "./server_settings_table";
import SpellButtonBindingsRow from "./spell_button_bindings_table";
import SpellsRow from "./spells_table";
import StatDefinitionsRow from "./stat_definitions_table";
import WorldObjectsRow from "./world_objects_table";
import WorldTimeRow from "./world_time_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  ActiveEffects: __table({
    name: 'active_effects',
    indexes: [
      { accessor: 'Id', name: 'active_effects_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'TargetCharacterId', name: 'active_effects_target_character_id_idx_btree', algorithm: 'btree', columns: [
        'targetCharacterId',
      ] },
      { accessor: 'TargetEntityId', name: 'active_effects_target_entity_id_idx_btree', algorithm: 'btree', columns: [
        'targetEntityId',
      ] },
    ],
    constraints: [
      { name: 'active_effects_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ActiveEffectsRow),
  AuthSessions: __table({
    name: 'auth_sessions',
    indexes: [
      { accessor: 'AccountId', name: 'auth_sessions_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
    ],
    constraints: [
      { name: 'auth_sessions_account_id_key', constraint: 'unique', columns: ['accountId'] },
    ],
  }, AuthSessionsRow),
  BagSlots: __table({
    name: 'bag_slots',
    indexes: [
      { accessor: 'BagId', name: 'bag_slots_bag_id_idx_btree', algorithm: 'btree', columns: [
        'bagId',
      ] },
      { accessor: 'CharacterId', name: 'bag_slots_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { accessor: 'Id', name: 'bag_slots_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'bag_slots_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BagSlotsRow),
  Bags: __table({
    name: 'bags',
    indexes: [
      { accessor: 'CharacterId', name: 'bags_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { accessor: 'Id', name: 'bags_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'bags_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BagsRow),
  ChangelogEntries: __table({
    name: 'changelog_entries',
    indexes: [
      { accessor: 'ChangeDate', name: 'changelog_entries_date_idx_btree', algorithm: 'btree', columns: [
        'date',
      ] },
      { accessor: 'Id', name: 'changelog_entries_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'changelog_entries_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChangelogEntriesRow),
  CharacterCurrencies: __table({
    name: 'character_currencies',
    indexes: [
      { accessor: 'CharacterId', name: 'character_currencies_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
    ],
    constraints: [
      { name: 'character_currencies_character_id_key', constraint: 'unique', columns: ['characterId'] },
    ],
  }, CharacterCurrenciesRow),
  CharacterEquipment: __table({
    name: 'character_equipment',
    indexes: [
      { accessor: 'CharacterId', name: 'character_equipment_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
    ],
    constraints: [
      { name: 'character_equipment_character_id_key', constraint: 'unique', columns: ['characterId'] },
    ],
  }, CharacterEquipmentRow),
  CharacterMapFog: __table({
    name: 'character_map_fog',
    indexes: [
      { accessor: 'CharacterId', name: 'character_map_fog_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { accessor: 'CharacterZone', name: 'character_map_fog_character_id_zone_name_idx_btree', algorithm: 'btree', columns: [
        'characterId',
        'zoneName',
      ] },
      { accessor: 'Id', name: 'character_map_fog_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'character_map_fog_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CharacterMapFogRow),
  CharacterStates: __table({
    name: 'character_states',
    indexes: [
      { accessor: 'CharacterId', name: 'character_states_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { accessor: 'Chunk', name: 'character_states_chunk_x_chunk_z_idx_btree', algorithm: 'btree', columns: [
        'chunkX',
        'chunkZ',
      ] },
    ],
    constraints: [
      { name: 'character_states_character_id_key', constraint: 'unique', columns: ['characterId'] },
    ],
  }, CharacterStatesRow),
  CharacterStats: __table({
    name: 'character_stats',
    indexes: [
      { accessor: 'CharacterId', name: 'character_stats_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
    ],
    constraints: [
      { name: 'character_stats_character_id_key', constraint: 'unique', columns: ['characterId'] },
    ],
  }, CharacterStatsRow),
  Characters: __table({
    name: 'characters',
    indexes: [
      { accessor: 'AccountId', name: 'characters_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
      { accessor: 'Id', name: 'characters_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'NameTag', name: 'characters_name_tag_idx_btree', algorithm: 'btree', columns: [
        'name',
        'tag',
      ] },
    ],
    constraints: [
      { name: 'characters_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CharactersRow),
  CharactersOffline: __table({
    name: 'characters_offline',
    indexes: [
      { accessor: 'AccountId', name: 'characters_offline_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
      { accessor: 'Id', name: 'characters_offline_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'NameTag', name: 'characters_offline_name_tag_idx_btree', algorithm: 'btree', columns: [
        'name',
        'tag',
      ] },
    ],
    constraints: [
      { name: 'characters_offline_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CharactersOfflineRow),
  Classes: __table({
    name: 'classes',
    indexes: [
      { accessor: 'Id', name: 'classes_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'classes_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ClassesRow),
  CombatLog: __table({
    name: 'combat_log',
    indexes: [
      { accessor: 'Chunk', name: 'combat_log_chunk_x_chunk_z_idx_btree', algorithm: 'btree', columns: [
        'chunkX',
        'chunkZ',
      ] },
    ],
    constraints: [
    ],
    event: true,
  }, CombatLogRow),
  Enemies: __table({
    name: 'enemies',
    indexes: [
      { accessor: 'Id', name: 'enemies_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'enemies_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EnemiesRow),
  EnemyLootDrops: __table({
    name: 'enemy_loot_drops',
    indexes: [
      { accessor: 'CharacterId', name: 'enemy_loot_drops_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { accessor: 'Chunk', name: 'enemy_loot_drops_chunk_x_chunk_z_idx_btree', algorithm: 'btree', columns: [
        'chunkX',
        'chunkZ',
      ] },
      { accessor: 'EnemyId', name: 'enemy_loot_drops_enemy_id_idx_btree', algorithm: 'btree', columns: [
        'enemyId',
      ] },
      { accessor: 'Id', name: 'enemy_loot_drops_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'ItemId', name: 'enemy_loot_drops_item_id_idx_btree', algorithm: 'btree', columns: [
        'itemId',
      ] },
    ],
    constraints: [
      { name: 'enemy_loot_drops_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EnemyLootDropsRow),
  Entities: __table({
    name: 'entities',
    indexes: [
      { accessor: 'Chunk', name: 'entities_chunk_x_chunk_z_idx_btree', algorithm: 'btree', columns: [
        'chunkX',
        'chunkZ',
      ] },
      { accessor: 'EntityDataId', name: 'entities_entity_data_id_idx_btree', algorithm: 'btree', columns: [
        'entityDataId',
      ] },
      { accessor: 'EntityTypeId', name: 'entities_entity_type_id_idx_btree', algorithm: 'btree', columns: [
        'entityTypeId',
      ] },
      { accessor: 'Id', name: 'entities_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'entities_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EntitiesRow),
  GameEvent: __table({
    name: 'game_event',
    indexes: [
      { accessor: 'Chunk', name: 'game_event_chunk_x_chunk_z_idx_btree', algorithm: 'btree', columns: [
        'chunkX',
        'chunkZ',
      ] },
      { accessor: 'Id', name: 'game_event_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'game_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
    event: true,
  }, GameEventRow),
  ItemInstances: __table({
    name: 'item_instances',
    indexes: [
      { accessor: 'CharacterId', name: 'item_instances_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { accessor: 'Id', name: 'item_instances_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'ItemId', name: 'item_instances_item_id_idx_btree', algorithm: 'btree', columns: [
        'itemId',
      ] },
    ],
    constraints: [
      { name: 'item_instances_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ItemInstancesRow),
  Items: __table({
    name: 'items',
    indexes: [
      { accessor: 'Id', name: 'items_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'items_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ItemsRow),
  LevelRequirements: __table({
    name: 'level_requirements',
    indexes: [
      { accessor: 'Level', name: 'level_requirements_level_idx_btree', algorithm: 'btree', columns: [
        'level',
      ] },
    ],
    constraints: [
      { name: 'level_requirements_level_key', constraint: 'unique', columns: ['level'] },
    ],
  }, LevelRequirementsRow),
  LootTableEntries: __table({
    name: 'loot_table_entries',
    indexes: [
      { accessor: 'EnemyId', name: 'loot_table_entries_enemy_id_idx_btree', algorithm: 'btree', columns: [
        'enemyId',
      ] },
      { accessor: 'Id', name: 'loot_table_entries_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'ItemId', name: 'loot_table_entries_item_id_idx_btree', algorithm: 'btree', columns: [
        'itemId',
      ] },
      { accessor: 'LootTableName', name: 'loot_table_entries_loot_table_name_idx_btree', algorithm: 'btree', columns: [
        'lootTableName',
      ] },
    ],
    constraints: [
      { name: 'loot_table_entries_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LootTableEntriesRow),
  MessageEvent: __table({
    name: 'message_event',
    indexes: [
      { accessor: 'PartyId', name: 'message_event_party_id_idx_btree', algorithm: 'btree', columns: [
        'partyId',
      ] },
    ],
    constraints: [
    ],
    event: true,
  }, MessageEventRow),
  Npcs: __table({
    name: 'npcs',
    indexes: [
      { accessor: 'Id', name: 'npcs_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'npcs_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NpcsRow),
  Parties: __table({
    name: 'parties',
    indexes: [
      { accessor: 'Id', name: 'parties_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'LeaderCharacterId', name: 'parties_leader_character_id_idx_btree', algorithm: 'btree', columns: [
        'leaderCharacterId',
      ] },
    ],
    constraints: [
      { name: 'parties_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PartiesRow),
  PartyInvites: __table({
    name: 'party_invites',
    indexes: [
      { accessor: 'Id', name: 'party_invites_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'InviterCharacterId', name: 'party_invites_inviter_character_id_idx_btree', algorithm: 'btree', columns: [
        'inviterCharacterId',
      ] },
      { accessor: 'Pair', name: 'party_invites_inviter_character_id_target_character_id_idx_btree', algorithm: 'btree', columns: [
        'inviterCharacterId',
        'targetCharacterId',
      ] },
      { accessor: 'TargetCharacterId', name: 'party_invites_target_character_id_idx_btree', algorithm: 'btree', columns: [
        'targetCharacterId',
      ] },
    ],
    constraints: [
      { name: 'party_invites_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PartyInvitesRow),
  PartyMembers: __table({
    name: 'party_members',
    indexes: [
      { accessor: 'CharacterId', name: 'party_members_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { accessor: 'PartyId', name: 'party_members_party_id_idx_btree', algorithm: 'btree', columns: [
        'partyId',
      ] },
    ],
    constraints: [
      { name: 'party_members_character_id_key', constraint: 'unique', columns: ['characterId'] },
    ],
  }, PartyMembersRow),
  QuestProgress: __table({
    name: 'quest_progress',
    indexes: [
      { accessor: 'CharacterId', name: 'quest_progress_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { accessor: 'Id', name: 'quest_progress_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'QuestId', name: 'quest_progress_quest_id_idx_btree', algorithm: 'btree', columns: [
        'questId',
      ] },
    ],
    constraints: [
      { name: 'quest_progress_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, QuestProgressRow),
  Quests: __table({
    name: 'quests',
    indexes: [
      { accessor: 'Id', name: 'quests_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
    ],
  }, QuestsRow),
  ServerSettings: __table({
    name: 'server_settings',
    indexes: [
    ],
    constraints: [
    ],
  }, ServerSettingsRow),
  SpellButtonBindings: __table({
    name: 'spell_button_bindings',
    indexes: [
      { accessor: 'ButtonIndex', name: 'spell_button_bindings_button_index_idx_btree', algorithm: 'btree', columns: [
        'buttonIndex',
      ] },
      { accessor: 'CharacterIdButtonIndex', name: 'spell_button_bindings_character_id_button_index_idx_btree', algorithm: 'btree', columns: [
        'characterId',
        'buttonIndex',
      ] },
      { accessor: 'CharacterId', name: 'spell_button_bindings_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { accessor: 'Id', name: 'spell_button_bindings_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'spell_button_bindings_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SpellButtonBindingsRow),
  Spells: __table({
    name: 'spells',
    indexes: [
      { accessor: 'Id', name: 'spells_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'spells_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SpellsRow),
  StatDefinitions: __table({
    name: 'stat_definitions',
    indexes: [
      { accessor: 'Id', name: 'stat_definitions_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'stat_definitions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, StatDefinitionsRow),
  WorldObjects: __table({
    name: 'world_objects',
    indexes: [
      { accessor: 'Id', name: 'world_objects_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'world_objects_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldObjectsRow),
  WorldTime: __table({
    name: 'world_time',
    indexes: [
      { accessor: 'Id', name: 'world_time_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'world_time_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldTimeRow),
  AccountCharacters: __table({
    name: 'account_characters',
    indexes: [
    ],
    constraints: [
    ],
  }, AccountCharactersRow),
  QuestsWithProgress: __table({
    name: 'quests_with_progress',
    indexes: [
    ],
    constraints: [
    ],
  }, QuestsWithProgressRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("abandon_quest", AbandonQuestReducer),
  __reducerSchema("accept_party_invite", AcceptPartyInviteReducer),
  __reducerSchema("accept_quest", AcceptQuestReducer),
  __reducerSchema("add_changelog_entry", AddChangelogEntryReducer),
  __reducerSchema("add_enemy", AddEnemyReducer),
  __reducerSchema("add_enemy_entity", AddEnemyEntityReducer),
  __reducerSchema("add_item", AddItemReducer),
  __reducerSchema("add_loot_table_entry", AddLootTableEntryReducer),
  __reducerSchema("add_npc", AddNpcReducer),
  __reducerSchema("add_npc_entity", AddNpcEntityReducer),
  __reducerSchema("add_quest", AddQuestReducer),
  __reducerSchema("add_spell", AddSpellReducer),
  __reducerSchema("add_world_object", AddWorldObjectReducer),
  __reducerSchema("add_world_object_entity", AddWorldObjectEntityReducer),
  __reducerSchema("buy_item_from_npc", BuyItemFromNpcReducer),
  __reducerSchema("cancel_spell_cast", CancelSpellCastReducer),
  __reducerSchema("cast_arc_spell", CastArcSpellReducer),
  __reducerSchema("cast_area_spell", CastAreaSpellReducer),
  __reducerSchema("cast_mobility_spell", CastMobilitySpellReducer),
  __reducerSchema("cast_recall", CastRecallReducer),
  __reducerSchema("complete_quest", CompleteQuestReducer),
  __reducerSchema("create_character", CreateCharacterReducer),
  __reducerSchema("damage_enemy", DamageEnemyReducer),
  __reducerSchema("decline_party_invite", DeclinePartyInviteReducer),
  __reducerSchema("delete_all_enemies", DeleteAllEnemiesReducer),
  __reducerSchema("delete_all_enemy_entities", DeleteAllEnemyEntitiesReducer),
  __reducerSchema("delete_all_npc_entities", DeleteAllNpcEntitiesReducer),
  __reducerSchema("delete_all_npcs", DeleteAllNpcsReducer),
  __reducerSchema("delete_all_world_object_entities", DeleteAllWorldObjectEntitiesReducer),
  __reducerSchema("delete_all_world_objects", DeleteAllWorldObjectsReducer),
  __reducerSchema("delete_changelog_entry", DeleteChangelogEntryReducer),
  __reducerSchema("delete_character", DeleteCharacterReducer),
  __reducerSchema("delete_enemy", DeleteEnemyReducer),
  __reducerSchema("delete_item", DeleteItemReducer),
  __reducerSchema("delete_item_from_bag", DeleteItemFromBagReducer),
  __reducerSchema("delete_item_from_equipment", DeleteItemFromEquipmentReducer),
  __reducerSchema("delete_loot_table_entry", DeleteLootTableEntryReducer),
  __reducerSchema("delete_npc", DeleteNpcReducer),
  __reducerSchema("delete_quest", DeleteQuestReducer),
  __reducerSchema("delete_spell", DeleteSpellReducer),
  __reducerSchema("delete_world_object", DeleteWorldObjectReducer),
  __reducerSchema("enter_world", EnterWorldReducer),
  __reducerSchema("equip_item", EquipItemReducer),
  __reducerSchema("exit_world", ExitWorldReducer),
  __reducerSchema("heal_character", HealCharacterReducer),
  __reducerSchema("insert_wood_pile_and_nythera_quests", InsertWoodPileAndNytheraQuestsReducer),
  __reducerSchema("invite_to_party", InviteToPartyReducer),
  __reducerSchema("jump", JumpReducer),
  __reducerSchema("leave_party", LeavePartyReducer),
  __reducerSchema("loot_enemy_drop", LootEnemyDropReducer),
  __reducerSchema("loot_world_object", LootWorldObjectReducer),
  __reducerSchema("move", MoveReducer),
  __reducerSchema("move_item", MoveItemReducer),
  __reducerSchema("ping", PingReducer),
  __reducerSchema("repair_character_split_tables", RepairCharacterSplitTablesReducer),
  __reducerSchema("respawn_character", RespawnCharacterReducer),
  __reducerSchema("seed_classes", SeedClassesReducer),
  __reducerSchema("seed_enemies", SeedEnemiesReducer),
  __reducerSchema("seed_items", SeedItemsReducer),
  __reducerSchema("seed_level_requirements", SeedLevelRequirementsReducer),
  __reducerSchema("seed_loot_tables", SeedLootTablesReducer),
  __reducerSchema("seed_npcs", SeedNpcsReducer),
  __reducerSchema("seed_quests", SeedQuestsReducer),
  __reducerSchema("seed_spells", SeedSpellsReducer),
  __reducerSchema("seed_stat_definitions", SeedStatDefinitionsReducer),
  __reducerSchema("seed_world_objects", SeedWorldObjectsReducer),
  __reducerSchema("sell_item_to_npc", SellItemToNpcReducer),
  __reducerSchema("send_message", SendMessageReducer),
  __reducerSchema("set_action_bar_spell", SetActionBarSpellReducer),
  __reducerSchema("set_weapon_drawn", SetWeaponDrawnReducer),
  __reducerSchema("unequip_item", UnequipItemReducer),
  __reducerSchema("update_changelog_entry", UpdateChangelogEntryReducer),
  __reducerSchema("update_enemy", UpdateEnemyReducer),
  __reducerSchema("update_existing_character_inventory_slots", UpdateExistingCharacterInventorySlotsReducer),
  __reducerSchema("update_item", UpdateItemReducer),
  __reducerSchema("update_loot_table_entry", UpdateLootTableEntryReducer),
  __reducerSchema("update_npc", UpdateNpcReducer),
  __reducerSchema("update_quest", UpdateQuestReducer),
  __reducerSchema("update_spell", UpdateSpellReducer),
  __reducerSchema("update_tags", UpdateTagsReducer),
  __reducerSchema("update_world_object", UpdateWorldObjectReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.6.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

