// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.7.0 (commit d220349adb7af7eefa810eb08a185609356b83f6).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AbandonQuestReducer from "./abandon_quest_reducer";
import AcceptPartyInviteReducer from "./accept_party_invite_reducer";
import AcceptQuestReducer from "./accept_quest_reducer";
import ActivateActionBarItemReducer from "./activate_action_bar_item_reducer";
import AddChangelogEntryReducer from "./add_changelog_entry_reducer";
import AddEnemyReducer from "./add_enemy_reducer";
import AddEnemyEntityReducer from "./add_enemy_entity_reducer";
import AddFriendReducer from "./add_friend_reducer";
import AddItemReducer from "./add_item_reducer";
import AddNpcReducer from "./add_npc_reducer";
import AddNpcEntityReducer from "./add_npc_entity_reducer";
import AddQuestReducer from "./add_quest_reducer";
import AddSpellReducer from "./add_spell_reducer";
import AddWorldObjectReducer from "./add_world_object_reducer";
import AddWorldObjectEntityReducer from "./add_world_object_entity_reducer";
import AlterCharacterAppearanceReducer from "./alter_character_appearance_reducer";
import BackfillCompendiumInventoryDiscoveriesReducer from "./backfill_compendium_inventory_discoveries_reducer";
import BuyItemFromNpcReducer from "./buy_item_from_npc_reducer";
import CancelSpellCastReducer from "./cancel_spell_cast_reducer";
import CastArcSpellReducer from "./cast_arc_spell_reducer";
import CastAreaSpellReducer from "./cast_area_spell_reducer";
import CastGroundTargetSpellReducer from "./cast_ground_target_spell_reducer";
import CastMobilitySpellReducer from "./cast_mobility_spell_reducer";
import CastRecallReducer from "./cast_recall_reducer";
import CompleteQuestReducer from "./complete_quest_reducer";
import CreateCharacterReducer from "./create_character_reducer";
import DamageEnemyReducer from "./damage_enemy_reducer";
import DeclinePartyInviteReducer from "./decline_party_invite_reducer";
import DeleteAllEnemyEntitiesReducer from "./delete_all_enemy_entities_reducer";
import DeleteAllNpcEntitiesReducer from "./delete_all_npc_entities_reducer";
import DeleteAllWorldObjectEntitiesReducer from "./delete_all_world_object_entities_reducer";
import DeleteChangelogEntryReducer from "./delete_changelog_entry_reducer";
import DeleteCharacterReducer from "./delete_character_reducer";
import DeleteEnemyReducer from "./delete_enemy_reducer";
import DeleteItemReducer from "./delete_item_reducer";
import DeleteItemFromBagReducer from "./delete_item_from_bag_reducer";
import DeleteItemFromBankReducer from "./delete_item_from_bank_reducer";
import DeleteItemFromEquipmentReducer from "./delete_item_from_equipment_reducer";
import DeleteNpcReducer from "./delete_npc_reducer";
import DeleteQuestReducer from "./delete_quest_reducer";
import DeleteSpellReducer from "./delete_spell_reducer";
import DeleteWorldObjectReducer from "./delete_world_object_reducer";
import DiscoverNpcReducer from "./discover_npc_reducer";
import EnterWorldReducer from "./enter_world_reducer";
import EquipItemReducer from "./equip_item_reducer";
import EquipItemToSlotReducer from "./equip_item_to_slot_reducer";
import ExitWorldReducer from "./exit_world_reducer";
import HealCharacterReducer from "./heal_character_reducer";
import InviteToPartyReducer from "./invite_to_party_reducer";
import JumpReducer from "./jump_reducer";
import LeavePartyReducer from "./leave_party_reducer";
import LootEnemyDropReducer from "./loot_enemy_drop_reducer";
import LootWorldObjectReducer from "./loot_world_object_reducer";
import MarkCompendiumDiscoveriesSeenReducer from "./mark_compendium_discoveries_seen_reducer";
import MigrateLegacyActionBarBindingsReducer from "./migrate_legacy_action_bar_bindings_reducer";
import MigrateMyLegacyActionBarBindingsReducer from "./migrate_my_legacy_action_bar_bindings_reducer";
import MoveReducer from "./move_reducer";
import MoveItemReducer from "./move_item_reducer";
import MoveItemBetweenBagAndBankReducer from "./move_item_between_bag_and_bank_reducer";
import MoveItemWithinBankReducer from "./move_item_within_bank_reducer";
import PingReducer from "./ping_reducer";
import RemoveFriendReducer from "./remove_friend_reducer";
import ReportClientVersionReducer from "./report_client_version_reducer";
import ResetTalentsReducer from "./reset_talents_reducer";
import RespawnCharacterReducer from "./respawn_character_reducer";
import SeedClassesReducer from "./seed_classes_reducer";
import SeedEnemiesReducer from "./seed_enemies_reducer";
import SeedItemsReducer from "./seed_items_reducer";
import SeedLevelRequirementsReducer from "./seed_level_requirements_reducer";
import SeedLootTablesReducer from "./seed_loot_tables_reducer";
import SeedNpcsReducer from "./seed_npcs_reducer";
import SeedQuestsReducer from "./seed_quests_reducer";
import SeedSpellsReducer from "./seed_spells_reducer";
import SeedStatDefinitionsReducer from "./seed_stat_definitions_reducer";
import SeedTalentNodesReducer from "./seed_talent_nodes_reducer";
import SeedWorldObjectsReducer from "./seed_world_objects_reducer";
import SellItemToNpcReducer from "./sell_item_to_npc_reducer";
import SendMessageReducer from "./send_message_reducer";
import SendSystemAnnouncementReducer from "./send_system_announcement_reducer";
import SetActionBarBindingReducer from "./set_action_bar_binding_reducer";
import SetActionBarSpellReducer from "./set_action_bar_spell_reducer";
import SetMinRequiredGameVersionReducer from "./set_min_required_game_version_reducer";
import SetNpcEquipmentReducer from "./set_npc_equipment_reducer";
import SetRecallBindReducer from "./set_recall_bind_reducer";
import SetSittingReducer from "./set_sitting_reducer";
import SetTrackedQuestReducer from "./set_tracked_quest_reducer";
import SetWeaponDrawnReducer from "./set_weapon_drawn_reducer";
import SpendTalentPointReducer from "./spend_talent_point_reducer";
import UnequipItemReducer from "./unequip_item_reducer";
import UpdateChangelogEntryReducer from "./update_changelog_entry_reducer";
import UpdateEnemyReducer from "./update_enemy_reducer";
import UpdateItemReducer from "./update_item_reducer";
import UpdateNpcReducer from "./update_npc_reducer";
import UpdateQuestReducer from "./update_quest_reducer";
import UpdateSpellReducer from "./update_spell_reducer";
import UpdateWorldObjectReducer from "./update_world_object_reducer";
import UseItemFromBagReducer from "./use_item_from_bag_reducer";
import UsePortalReducer from "./use_portal_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AccountCharactersRow from "./account_characters_table";
import AccountFriendsRow from "./account_friends_table";
import ActionBarBindingsRow from "./action_bar_bindings_table";
import ActiveEffectsRow from "./active_effects_table";
import AuthSessionsRow from "./auth_sessions_table";
import BagSlotsRow from "./bag_slots_table";
import BagsRow from "./bags_table";
import BankSlotsRow from "./bank_slots_table";
import CalculatedSpellValuesRow from "./calculated_spell_values_table";
import ChangelogEntriesRow from "./changelog_entries_table";
import CharacterCompendiumDiscoveriesRow from "./character_compendium_discoveries_table";
import CharacterCurrenciesRow from "./character_currencies_table";
import CharacterEquipmentRow from "./character_equipment_table";
import CharacterMapFogRow from "./character_map_fog_table";
import CharacterRecallBindsRow from "./character_recall_binds_table";
import CharacterStatesRow from "./character_states_table";
import CharacterStatsRow from "./character_stats_table";
import CharacterTalentsRow from "./character_talents_table";
import CharacterTrackedQuestsRow from "./character_tracked_quests_table";
import CharactersRow from "./characters_table";
import CharactersOfflineRow from "./characters_offline_table";
import ConsumableItemsRow from "./consumable_items_table";
import CurrentChunkCharacterStatesRow from "./current_chunk_character_states_table";
import CurrentChunkCombatLogRow from "./current_chunk_combat_log_table";
import CurrentChunkEntitiesRow from "./current_chunk_entities_table";
import CurrentChunkGameEventsRow from "./current_chunk_game_events_table";
import CurrentChunkLootRow from "./current_chunk_loot_table";
import EnemiesRow from "./enemies_table";
import EquipmentItemsRow from "./equipment_items_table";
import InstancesRow from "./instances_table";
import ItemDefinitionsRow from "./item_definitions_table";
import ItemInstancesRow from "./item_instances_table";
import LevelRequirementsRow from "./level_requirements_table";
import LootTableEntriesRow from "./loot_table_entries_table";
import MessageEventRow from "./message_event_table";
import NpcEquipmentRow from "./npc_equipment_table";
import NpcsRow from "./npcs_table";
import PartiesRow from "./parties_table";
import PartyInvitesRow from "./party_invites_table";
import PartyMembersRow from "./party_members_table";
import QuestNpcEntitiesRow from "./quest_npc_entities_table";
import QuestTargetEntitiesRow from "./quest_target_entities_table";
import QuestsRow from "./quests_table";
import QuestsWithProgressRow from "./quests_with_progress_table";
import ServerSettingsRow from "./server_settings_table";
import SpellButtonBindingsRow from "./spell_button_bindings_table";
import SpellsRow from "./spells_table";
import StatDefinitionsRow from "./stat_definitions_table";
import TalentNodeStatesRow from "./talent_node_states_table";
import TalentNodesRow from "./talent_nodes_table";
import TalentPointsRow from "./talent_points_table";
import WorldObjectsRow from "./world_objects_table";
import WorldTimeRow from "./world_time_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  actionBarBindings: __table({
    name: 'action_bar_bindings',
    indexes: [
      { accessor: 'CharacterId', name: 'action_bar_bindings_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { accessor: 'Id', name: 'action_bar_bindings_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'action_bar_bindings_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ActionBarBindingsRow),
  activeEffects: __table({
    name: 'active_effects',
    indexes: [
      { accessor: 'Id', name: 'active_effects_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'TargetCharacterId', name: 'active_effects_target_character_id_idx_btree', algorithm: 'btree', columns: [
        'targetCharacterId',
      ] },
      { accessor: 'TargetEntityId', name: 'active_effects_target_entity_id_idx_btree', algorithm: 'btree', columns: [
        'targetEntityId',
      ] },
    ],
    constraints: [
      { name: 'active_effects_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ActiveEffectsRow),
  authSessions: __table({
    name: 'auth_sessions',
    indexes: [
      { accessor: 'AccountId', name: 'auth_sessions_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
    ],
    constraints: [
      { name: 'auth_sessions_account_id_key', constraint: 'unique', columns: ['accountId'] },
    ],
  }, AuthSessionsRow),
  bagSlots: __table({
    name: 'bag_slots',
    indexes: [
      { accessor: 'BagId', name: 'bag_slots_bag_id_idx_btree', algorithm: 'btree', columns: [
        'bagId',
      ] },
      { accessor: 'CharacterId', name: 'bag_slots_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { accessor: 'Id', name: 'bag_slots_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'bag_slots_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BagSlotsRow),
  bags: __table({
    name: 'bags',
    indexes: [
      { accessor: 'CharacterId', name: 'bags_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { accessor: 'Id', name: 'bags_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'bags_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BagsRow),
  bankSlots: __table({
    name: 'bank_slots',
    indexes: [
      { accessor: 'CharacterId', name: 'bank_slots_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { accessor: 'Id', name: 'bank_slots_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'bank_slots_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BankSlotsRow),
  changelogEntries: __table({
    name: 'changelog_entries',
    indexes: [
      { accessor: 'ChangeDate', name: 'changelog_entries_date_idx_btree', algorithm: 'btree', columns: [
        'date',
      ] },
      { accessor: 'Id', name: 'changelog_entries_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'changelog_entries_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChangelogEntriesRow),
  characterCompendiumDiscoveries: __table({
    name: 'character_compendium_discoveries',
    indexes: [
      { accessor: 'CharacterEntry', name: 'character_compendium_discoveries_character_id_entry_type_entry_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
        'entryType',
        'entryId',
      ] },
      { accessor: 'CharacterId', name: 'character_compendium_discoveries_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { accessor: 'Id', name: 'character_compendium_discoveries_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'character_compendium_discoveries_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CharacterCompendiumDiscoveriesRow),
  characterCurrencies: __table({
    name: 'character_currencies',
    indexes: [
      { accessor: 'CharacterId', name: 'character_currencies_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
    ],
    constraints: [
      { name: 'character_currencies_character_id_key', constraint: 'unique', columns: ['characterId'] },
    ],
  }, CharacterCurrenciesRow),
  characterEquipment: __table({
    name: 'character_equipment',
    indexes: [
      { accessor: 'CharacterId', name: 'character_equipment_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
    ],
    constraints: [
      { name: 'character_equipment_character_id_key', constraint: 'unique', columns: ['characterId'] },
    ],
  }, CharacterEquipmentRow),
  characterMapFog: __table({
    name: 'character_map_fog',
    indexes: [
      { accessor: 'CharacterId', name: 'character_map_fog_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { accessor: 'CharacterZone', name: 'character_map_fog_character_id_zone_name_idx_btree', algorithm: 'btree', columns: [
        'characterId',
        'zoneName',
      ] },
      { accessor: 'Id', name: 'character_map_fog_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'character_map_fog_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CharacterMapFogRow),
  characterRecallBinds: __table({
    name: 'character_recall_binds',
    indexes: [
      { accessor: 'CharacterId', name: 'character_recall_binds_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
    ],
    constraints: [
      { name: 'character_recall_binds_character_id_key', constraint: 'unique', columns: ['characterId'] },
    ],
  }, CharacterRecallBindsRow),
  characterStates: __table({
    name: 'character_states',
    indexes: [
      { accessor: 'CharacterId', name: 'character_states_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { accessor: 'Chunk', name: 'character_states_instance_id_chunk_x_chunk_z_idx_btree', algorithm: 'btree', columns: [
        'instanceId',
        'chunkX',
        'chunkZ',
      ] },
    ],
    constraints: [
      { name: 'character_states_character_id_key', constraint: 'unique', columns: ['characterId'] },
    ],
  }, CharacterStatesRow),
  characterStats: __table({
    name: 'character_stats',
    indexes: [
      { accessor: 'CharacterId', name: 'character_stats_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
    ],
    constraints: [
      { name: 'character_stats_character_id_key', constraint: 'unique', columns: ['characterId'] },
    ],
  }, CharacterStatsRow),
  characterTalents: __table({
    name: 'character_talents',
    indexes: [
      { accessor: 'TalentsByCharacter', name: 'character_talents_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { accessor: 'TalentsByCharacterNode', name: 'character_talents_character_id_node_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
        'nodeId',
      ] },
      { accessor: 'Id', name: 'character_talents_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'character_talents_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CharacterTalentsRow),
  characterTrackedQuests: __table({
    name: 'character_tracked_quests',
    indexes: [
      { accessor: 'CharacterId', name: 'character_tracked_quests_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
    ],
    constraints: [
      { name: 'character_tracked_quests_character_id_key', constraint: 'unique', columns: ['characterId'] },
    ],
  }, CharacterTrackedQuestsRow),
  characters: __table({
    name: 'characters',
    indexes: [
      { accessor: 'AccountId', name: 'characters_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
      { accessor: 'Id', name: 'characters_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'NameTag', name: 'characters_name_tag_idx_btree', algorithm: 'btree', columns: [
        'name',
        'tag',
      ] },
    ],
    constraints: [
      { name: 'characters_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CharactersRow),
  charactersOffline: __table({
    name: 'characters_offline',
    indexes: [
      { accessor: 'AccountId', name: 'characters_offline_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
      { accessor: 'Id', name: 'characters_offline_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'NameTag', name: 'characters_offline_name_tag_idx_btree', algorithm: 'btree', columns: [
        'name',
        'tag',
      ] },
    ],
    constraints: [
      { name: 'characters_offline_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CharactersOfflineRow),
  consumableItems: __table({
    name: 'consumable_items',
    indexes: [
      { accessor: 'ItemId', name: 'consumable_items_item_id_idx_btree', algorithm: 'btree', columns: [
        'itemId',
      ] },
    ],
    constraints: [
      { name: 'consumable_items_item_id_key', constraint: 'unique', columns: ['itemId'] },
    ],
  }, ConsumableItemsRow),
  enemies: __table({
    name: 'enemies',
    indexes: [
      { accessor: 'Id', name: 'enemies_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'enemies_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EnemiesRow),
  equipmentItems: __table({
    name: 'equipment_items',
    indexes: [
      { accessor: 'ItemId', name: 'equipment_items_item_id_idx_btree', algorithm: 'btree', columns: [
        'itemId',
      ] },
    ],
    constraints: [
      { name: 'equipment_items_item_id_key', constraint: 'unique', columns: ['itemId'] },
    ],
  }, EquipmentItemsRow),
  instances: __table({
    name: 'instances',
    indexes: [
      { accessor: 'Id', name: 'instances_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'OwnerCharacterId', name: 'instances_owner_character_id_idx_btree', algorithm: 'btree', columns: [
        'ownerCharacterId',
      ] },
      { accessor: 'PartyId', name: 'instances_party_id_idx_btree', algorithm: 'btree', columns: [
        'partyId',
      ] },
    ],
    constraints: [
      { name: 'instances_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, InstancesRow),
  itemDefinitions: __table({
    name: 'item_definitions',
    indexes: [
      { accessor: 'Id', name: 'item_definitions_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'item_definitions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ItemDefinitionsRow),
  itemInstances: __table({
    name: 'item_instances',
    indexes: [
      { accessor: 'CharacterId', name: 'item_instances_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { accessor: 'Id', name: 'item_instances_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'ItemId', name: 'item_instances_item_id_idx_btree', algorithm: 'btree', columns: [
        'itemId',
      ] },
    ],
    constraints: [
      { name: 'item_instances_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ItemInstancesRow),
  levelRequirements: __table({
    name: 'level_requirements',
    indexes: [
      { accessor: 'Level', name: 'level_requirements_level_idx_btree', algorithm: 'btree', columns: [
        'level',
      ] },
    ],
    constraints: [
      { name: 'level_requirements_level_key', constraint: 'unique', columns: ['level'] },
    ],
  }, LevelRequirementsRow),
  lootTableEntries: __table({
    name: 'loot_table_entries',
    indexes: [
      { accessor: 'EnemyId', name: 'loot_table_entries_enemy_id_idx_btree', algorithm: 'btree', columns: [
        'enemyId',
      ] },
      { accessor: 'Id', name: 'loot_table_entries_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'ItemId', name: 'loot_table_entries_item_id_idx_btree', algorithm: 'btree', columns: [
        'itemId',
      ] },
      { accessor: 'LootTableName', name: 'loot_table_entries_loot_table_name_idx_btree', algorithm: 'btree', columns: [
        'lootTableName',
      ] },
    ],
    constraints: [
      { name: 'loot_table_entries_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LootTableEntriesRow),
  messageEvent: __table({
    name: 'message_event',
    indexes: [
      { accessor: 'PartyId', name: 'message_event_party_id_idx_btree', algorithm: 'btree', columns: [
        'partyId',
      ] },
    ],
    constraints: [
    ],
    event: true,
  }, MessageEventRow),
  npcEquipment: __table({
    name: 'npc_equipment',
    indexes: [
      { accessor: 'NpcId', name: 'npc_equipment_npc_id_idx_btree', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'npc_equipment_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, NpcEquipmentRow),
  npcs: __table({
    name: 'npcs',
    indexes: [
      { accessor: 'Id', name: 'npcs_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'npcs_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NpcsRow),
  parties: __table({
    name: 'parties',
    indexes: [
      { accessor: 'Id', name: 'parties_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'LeaderCharacterId', name: 'parties_leader_character_id_idx_btree', algorithm: 'btree', columns: [
        'leaderCharacterId',
      ] },
    ],
    constraints: [
      { name: 'parties_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PartiesRow),
  partyInvites: __table({
    name: 'party_invites',
    indexes: [
      { accessor: 'Id', name: 'party_invites_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'InviterCharacterId', name: 'party_invites_inviter_character_id_idx_btree', algorithm: 'btree', columns: [
        'inviterCharacterId',
      ] },
      { accessor: 'Pair', name: 'party_invites_inviter_character_id_target_character_id_idx_btree', algorithm: 'btree', columns: [
        'inviterCharacterId',
        'targetCharacterId',
      ] },
      { accessor: 'TargetCharacterId', name: 'party_invites_target_character_id_idx_btree', algorithm: 'btree', columns: [
        'targetCharacterId',
      ] },
    ],
    constraints: [
      { name: 'party_invites_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PartyInvitesRow),
  partyMembers: __table({
    name: 'party_members',
    indexes: [
      { accessor: 'CharacterId', name: 'party_members_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { accessor: 'PartyId', name: 'party_members_party_id_idx_btree', algorithm: 'btree', columns: [
        'partyId',
      ] },
    ],
    constraints: [
      { name: 'party_members_character_id_key', constraint: 'unique', columns: ['characterId'] },
    ],
  }, PartyMembersRow),
  quests: __table({
    name: 'quests',
    indexes: [
      { accessor: 'Id', name: 'quests_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
    ],
  }, QuestsRow),
  serverSettings: __table({
    name: 'server_settings',
    indexes: [
    ],
    constraints: [
    ],
  }, ServerSettingsRow),
  spellButtonBindings: __table({
    name: 'spell_button_bindings',
    indexes: [
      { accessor: 'ButtonIndex', name: 'spell_button_bindings_button_index_idx_btree', algorithm: 'btree', columns: [
        'buttonIndex',
      ] },
      { accessor: 'CharacterIdButtonIndex', name: 'spell_button_bindings_character_id_button_index_idx_btree', algorithm: 'btree', columns: [
        'characterId',
        'buttonIndex',
      ] },
      { accessor: 'CharacterId', name: 'spell_button_bindings_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { accessor: 'Id', name: 'spell_button_bindings_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'spell_button_bindings_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SpellButtonBindingsRow),
  spells: __table({
    name: 'spells',
    indexes: [
      { accessor: 'ClassRequired', name: 'spells_class_required_idx_btree', algorithm: 'btree', columns: [
        'classRequired',
      ] },
      { accessor: 'Id', name: 'spells_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'spells_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SpellsRow),
  statDefinitions: __table({
    name: 'stat_definitions',
    indexes: [
      { accessor: 'Id', name: 'stat_definitions_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'stat_definitions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, StatDefinitionsRow),
  talentNodes: __table({
    name: 'talent_nodes',
    indexes: [
      { accessor: 'TalentNodesByClass', name: 'talent_nodes_class_id_idx_btree', algorithm: 'btree', columns: [
        'classId',
      ] },
      { accessor: 'Id', name: 'talent_nodes_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'talent_nodes_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TalentNodesRow),
  worldObjects: __table({
    name: 'world_objects',
    indexes: [
      { accessor: 'Id', name: 'world_objects_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'world_objects_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldObjectsRow),
  worldTime: __table({
    name: 'world_time',
    indexes: [
      { accessor: 'Id', name: 'world_time_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'world_time_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldTimeRow),
  accountCharacters: __table({
    name: 'account_characters',
    indexes: [
    ],
    constraints: [
    ],
  }, AccountCharactersRow),
  accountFriends: __table({
    name: 'account_friends',
    indexes: [
    ],
    constraints: [
    ],
  }, AccountFriendsRow),
  calculatedSpellValues: __table({
    name: 'calculated_spell_values',
    indexes: [
    ],
    constraints: [
    ],
  }, CalculatedSpellValuesRow),
  currentChunkCharacterStates: __table({
    name: 'current_chunk_character_states',
    indexes: [
    ],
    constraints: [
    ],
  }, CurrentChunkCharacterStatesRow),
  currentChunkCombatLog: __table({
    name: 'current_chunk_combat_log',
    indexes: [
    ],
    constraints: [
    ],
  }, CurrentChunkCombatLogRow),
  currentChunkEntities: __table({
    name: 'current_chunk_entities',
    indexes: [
    ],
    constraints: [
    ],
  }, CurrentChunkEntitiesRow),
  currentChunkGameEvents: __table({
    name: 'current_chunk_game_events',
    indexes: [
    ],
    constraints: [
    ],
  }, CurrentChunkGameEventsRow),
  currentChunkLoot: __table({
    name: 'current_chunk_loot',
    indexes: [
    ],
    constraints: [
    ],
  }, CurrentChunkLootRow),
  questNpcEntities: __table({
    name: 'quest_npc_entities',
    indexes: [
    ],
    constraints: [
    ],
  }, QuestNpcEntitiesRow),
  questTargetEntities: __table({
    name: 'quest_target_entities',
    indexes: [
    ],
    constraints: [
    ],
  }, QuestTargetEntitiesRow),
  questsWithProgress: __table({
    name: 'quests_with_progress',
    indexes: [
    ],
    constraints: [
    ],
  }, QuestsWithProgressRow),
  talentNodeStates: __table({
    name: 'talent_node_states',
    indexes: [
    ],
    constraints: [
    ],
  }, TalentNodeStatesRow),
  talentPoints: __table({
    name: 'talent_points',
    indexes: [
    ],
    constraints: [
    ],
  }, TalentPointsRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("abandon_quest", AbandonQuestReducer),
  __reducerSchema("accept_party_invite", AcceptPartyInviteReducer),
  __reducerSchema("accept_quest", AcceptQuestReducer),
  __reducerSchema("activate_action_bar_item", ActivateActionBarItemReducer),
  __reducerSchema("add_changelog_entry", AddChangelogEntryReducer),
  __reducerSchema("add_enemy", AddEnemyReducer),
  __reducerSchema("add_enemy_entity", AddEnemyEntityReducer),
  __reducerSchema("add_friend", AddFriendReducer),
  __reducerSchema("add_item", AddItemReducer),
  __reducerSchema("add_npc", AddNpcReducer),
  __reducerSchema("add_npc_entity", AddNpcEntityReducer),
  __reducerSchema("add_quest", AddQuestReducer),
  __reducerSchema("add_spell", AddSpellReducer),
  __reducerSchema("add_world_object", AddWorldObjectReducer),
  __reducerSchema("add_world_object_entity", AddWorldObjectEntityReducer),
  __reducerSchema("alter_character_appearance", AlterCharacterAppearanceReducer),
  __reducerSchema("backfill_compendium_inventory_discoveries", BackfillCompendiumInventoryDiscoveriesReducer),
  __reducerSchema("buy_item_from_npc", BuyItemFromNpcReducer),
  __reducerSchema("cancel_spell_cast", CancelSpellCastReducer),
  __reducerSchema("cast_arc_spell", CastArcSpellReducer),
  __reducerSchema("cast_area_spell", CastAreaSpellReducer),
  __reducerSchema("cast_ground_target_spell", CastGroundTargetSpellReducer),
  __reducerSchema("cast_mobility_spell", CastMobilitySpellReducer),
  __reducerSchema("cast_recall", CastRecallReducer),
  __reducerSchema("complete_quest", CompleteQuestReducer),
  __reducerSchema("create_character", CreateCharacterReducer),
  __reducerSchema("damage_enemy", DamageEnemyReducer),
  __reducerSchema("decline_party_invite", DeclinePartyInviteReducer),
  __reducerSchema("delete_all_enemy_entities", DeleteAllEnemyEntitiesReducer),
  __reducerSchema("delete_all_npc_entities", DeleteAllNpcEntitiesReducer),
  __reducerSchema("delete_all_world_object_entities", DeleteAllWorldObjectEntitiesReducer),
  __reducerSchema("delete_changelog_entry", DeleteChangelogEntryReducer),
  __reducerSchema("delete_character", DeleteCharacterReducer),
  __reducerSchema("delete_enemy", DeleteEnemyReducer),
  __reducerSchema("delete_item", DeleteItemReducer),
  __reducerSchema("delete_item_from_bag", DeleteItemFromBagReducer),
  __reducerSchema("delete_item_from_bank", DeleteItemFromBankReducer),
  __reducerSchema("delete_item_from_equipment", DeleteItemFromEquipmentReducer),
  __reducerSchema("delete_npc", DeleteNpcReducer),
  __reducerSchema("delete_quest", DeleteQuestReducer),
  __reducerSchema("delete_spell", DeleteSpellReducer),
  __reducerSchema("delete_world_object", DeleteWorldObjectReducer),
  __reducerSchema("discover_npc", DiscoverNpcReducer),
  __reducerSchema("enter_world", EnterWorldReducer),
  __reducerSchema("equip_item", EquipItemReducer),
  __reducerSchema("equip_item_to_slot", EquipItemToSlotReducer),
  __reducerSchema("exit_world", ExitWorldReducer),
  __reducerSchema("heal_character", HealCharacterReducer),
  __reducerSchema("invite_to_party", InviteToPartyReducer),
  __reducerSchema("jump", JumpReducer),
  __reducerSchema("leave_party", LeavePartyReducer),
  __reducerSchema("loot_enemy_drop", LootEnemyDropReducer),
  __reducerSchema("loot_world_object", LootWorldObjectReducer),
  __reducerSchema("mark_compendium_discoveries_seen", MarkCompendiumDiscoveriesSeenReducer),
  __reducerSchema("migrate_legacy_action_bar_bindings", MigrateLegacyActionBarBindingsReducer),
  __reducerSchema("migrate_my_legacy_action_bar_bindings", MigrateMyLegacyActionBarBindingsReducer),
  __reducerSchema("move", MoveReducer),
  __reducerSchema("move_item", MoveItemReducer),
  __reducerSchema("move_item_between_bag_and_bank", MoveItemBetweenBagAndBankReducer),
  __reducerSchema("move_item_within_bank", MoveItemWithinBankReducer),
  __reducerSchema("ping", PingReducer),
  __reducerSchema("remove_friend", RemoveFriendReducer),
  __reducerSchema("report_client_version", ReportClientVersionReducer),
  __reducerSchema("reset_talents", ResetTalentsReducer),
  __reducerSchema("respawn_character", RespawnCharacterReducer),
  __reducerSchema("seed_classes", SeedClassesReducer),
  __reducerSchema("seed_enemies", SeedEnemiesReducer),
  __reducerSchema("seed_items", SeedItemsReducer),
  __reducerSchema("seed_level_requirements", SeedLevelRequirementsReducer),
  __reducerSchema("seed_loot_tables", SeedLootTablesReducer),
  __reducerSchema("seed_npcs", SeedNpcsReducer),
  __reducerSchema("seed_quests", SeedQuestsReducer),
  __reducerSchema("seed_spells", SeedSpellsReducer),
  __reducerSchema("seed_stat_definitions", SeedStatDefinitionsReducer),
  __reducerSchema("seed_talent_nodes", SeedTalentNodesReducer),
  __reducerSchema("seed_world_objects", SeedWorldObjectsReducer),
  __reducerSchema("sell_item_to_npc", SellItemToNpcReducer),
  __reducerSchema("send_message", SendMessageReducer),
  __reducerSchema("send_system_announcement", SendSystemAnnouncementReducer),
  __reducerSchema("set_action_bar_binding", SetActionBarBindingReducer),
  __reducerSchema("set_action_bar_spell", SetActionBarSpellReducer),
  __reducerSchema("set_min_required_game_version", SetMinRequiredGameVersionReducer),
  __reducerSchema("set_npc_equipment", SetNpcEquipmentReducer),
  __reducerSchema("set_recall_bind", SetRecallBindReducer),
  __reducerSchema("set_sitting", SetSittingReducer),
  __reducerSchema("set_tracked_quest", SetTrackedQuestReducer),
  __reducerSchema("set_weapon_drawn", SetWeaponDrawnReducer),
  __reducerSchema("spend_talent_point", SpendTalentPointReducer),
  __reducerSchema("unequip_item", UnequipItemReducer),
  __reducerSchema("update_changelog_entry", UpdateChangelogEntryReducer),
  __reducerSchema("update_enemy", UpdateEnemyReducer),
  __reducerSchema("update_item", UpdateItemReducer),
  __reducerSchema("update_npc", UpdateNpcReducer),
  __reducerSchema("update_quest", UpdateQuestReducer),
  __reducerSchema("update_spell", UpdateSpellReducer),
  __reducerSchema("update_world_object", UpdateWorldObjectReducer),
  __reducerSchema("use_item_from_bag", UseItemFromBagReducer),
  __reducerSchema("use_portal", UsePortalReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `actionBarBindings` instead. This alias will be removed in the next major version. */
    readonly "ActionBarBindings": Omit<typeof tablesSchema.schemaType.tables["actionBarBindings"], "accessorName"> & { readonly accessorName: "ActionBarBindings" };
    /** @deprecated Use `activeEffects` instead. This alias will be removed in the next major version. */
    readonly "ActiveEffects": Omit<typeof tablesSchema.schemaType.tables["activeEffects"], "accessorName"> & { readonly accessorName: "ActiveEffects" };
    /** @deprecated Use `authSessions` instead. This alias will be removed in the next major version. */
    readonly "AuthSessions": Omit<typeof tablesSchema.schemaType.tables["authSessions"], "accessorName"> & { readonly accessorName: "AuthSessions" };
    /** @deprecated Use `bagSlots` instead. This alias will be removed in the next major version. */
    readonly "BagSlots": Omit<typeof tablesSchema.schemaType.tables["bagSlots"], "accessorName"> & { readonly accessorName: "BagSlots" };
    /** @deprecated Use `bags` instead. This alias will be removed in the next major version. */
    readonly "Bags": Omit<typeof tablesSchema.schemaType.tables["bags"], "accessorName"> & { readonly accessorName: "Bags" };
    /** @deprecated Use `bankSlots` instead. This alias will be removed in the next major version. */
    readonly "BankSlots": Omit<typeof tablesSchema.schemaType.tables["bankSlots"], "accessorName"> & { readonly accessorName: "BankSlots" };
    /** @deprecated Use `changelogEntries` instead. This alias will be removed in the next major version. */
    readonly "ChangelogEntries": Omit<typeof tablesSchema.schemaType.tables["changelogEntries"], "accessorName"> & { readonly accessorName: "ChangelogEntries" };
    /** @deprecated Use `characterCompendiumDiscoveries` instead. This alias will be removed in the next major version. */
    readonly "CharacterCompendiumDiscoveries": Omit<typeof tablesSchema.schemaType.tables["characterCompendiumDiscoveries"], "accessorName"> & { readonly accessorName: "CharacterCompendiumDiscoveries" };
    /** @deprecated Use `characterCurrencies` instead. This alias will be removed in the next major version. */
    readonly "CharacterCurrencies": Omit<typeof tablesSchema.schemaType.tables["characterCurrencies"], "accessorName"> & { readonly accessorName: "CharacterCurrencies" };
    /** @deprecated Use `characterEquipment` instead. This alias will be removed in the next major version. */
    readonly "CharacterEquipment": Omit<typeof tablesSchema.schemaType.tables["characterEquipment"], "accessorName"> & { readonly accessorName: "CharacterEquipment" };
    /** @deprecated Use `characterMapFog` instead. This alias will be removed in the next major version. */
    readonly "CharacterMapFog": Omit<typeof tablesSchema.schemaType.tables["characterMapFog"], "accessorName"> & { readonly accessorName: "CharacterMapFog" };
    /** @deprecated Use `characterRecallBinds` instead. This alias will be removed in the next major version. */
    readonly "CharacterRecallBinds": Omit<typeof tablesSchema.schemaType.tables["characterRecallBinds"], "accessorName"> & { readonly accessorName: "CharacterRecallBinds" };
    /** @deprecated Use `characterStates` instead. This alias will be removed in the next major version. */
    readonly "CharacterStates": Omit<typeof tablesSchema.schemaType.tables["characterStates"], "accessorName"> & { readonly accessorName: "CharacterStates" };
    /** @deprecated Use `characterStats` instead. This alias will be removed in the next major version. */
    readonly "CharacterStats": Omit<typeof tablesSchema.schemaType.tables["characterStats"], "accessorName"> & { readonly accessorName: "CharacterStats" };
    /** @deprecated Use `characterTalents` instead. This alias will be removed in the next major version. */
    readonly "CharacterTalents": Omit<typeof tablesSchema.schemaType.tables["characterTalents"], "accessorName"> & { readonly accessorName: "CharacterTalents" };
    /** @deprecated Use `characterTrackedQuests` instead. This alias will be removed in the next major version. */
    readonly "CharacterTrackedQuests": Omit<typeof tablesSchema.schemaType.tables["characterTrackedQuests"], "accessorName"> & { readonly accessorName: "CharacterTrackedQuests" };
    /** @deprecated Use `characters` instead. This alias will be removed in the next major version. */
    readonly "Characters": Omit<typeof tablesSchema.schemaType.tables["characters"], "accessorName"> & { readonly accessorName: "Characters" };
    /** @deprecated Use `charactersOffline` instead. This alias will be removed in the next major version. */
    readonly "CharactersOffline": Omit<typeof tablesSchema.schemaType.tables["charactersOffline"], "accessorName"> & { readonly accessorName: "CharactersOffline" };
    /** @deprecated Use `consumableItems` instead. This alias will be removed in the next major version. */
    readonly "ConsumableItems": Omit<typeof tablesSchema.schemaType.tables["consumableItems"], "accessorName"> & { readonly accessorName: "ConsumableItems" };
    /** @deprecated Use `enemies` instead. This alias will be removed in the next major version. */
    readonly "Enemies": Omit<typeof tablesSchema.schemaType.tables["enemies"], "accessorName"> & { readonly accessorName: "Enemies" };
    /** @deprecated Use `equipmentItems` instead. This alias will be removed in the next major version. */
    readonly "EquipmentItems": Omit<typeof tablesSchema.schemaType.tables["equipmentItems"], "accessorName"> & { readonly accessorName: "EquipmentItems" };
    /** @deprecated Use `instances` instead. This alias will be removed in the next major version. */
    readonly "Instances": Omit<typeof tablesSchema.schemaType.tables["instances"], "accessorName"> & { readonly accessorName: "Instances" };
    /** @deprecated Use `itemDefinitions` instead. This alias will be removed in the next major version. */
    readonly "ItemDefinitions": Omit<typeof tablesSchema.schemaType.tables["itemDefinitions"], "accessorName"> & { readonly accessorName: "ItemDefinitions" };
    /** @deprecated Use `itemInstances` instead. This alias will be removed in the next major version. */
    readonly "ItemInstances": Omit<typeof tablesSchema.schemaType.tables["itemInstances"], "accessorName"> & { readonly accessorName: "ItemInstances" };
    /** @deprecated Use `levelRequirements` instead. This alias will be removed in the next major version. */
    readonly "LevelRequirements": Omit<typeof tablesSchema.schemaType.tables["levelRequirements"], "accessorName"> & { readonly accessorName: "LevelRequirements" };
    /** @deprecated Use `lootTableEntries` instead. This alias will be removed in the next major version. */
    readonly "LootTableEntries": Omit<typeof tablesSchema.schemaType.tables["lootTableEntries"], "accessorName"> & { readonly accessorName: "LootTableEntries" };
    /** @deprecated Use `messageEvent` instead. This alias will be removed in the next major version. */
    readonly "MessageEvent": Omit<typeof tablesSchema.schemaType.tables["messageEvent"], "accessorName"> & { readonly accessorName: "MessageEvent" };
    /** @deprecated Use `npcEquipment` instead. This alias will be removed in the next major version. */
    readonly "NpcEquipment": Omit<typeof tablesSchema.schemaType.tables["npcEquipment"], "accessorName"> & { readonly accessorName: "NpcEquipment" };
    /** @deprecated Use `npcs` instead. This alias will be removed in the next major version. */
    readonly "Npcs": Omit<typeof tablesSchema.schemaType.tables["npcs"], "accessorName"> & { readonly accessorName: "Npcs" };
    /** @deprecated Use `parties` instead. This alias will be removed in the next major version. */
    readonly "Parties": Omit<typeof tablesSchema.schemaType.tables["parties"], "accessorName"> & { readonly accessorName: "Parties" };
    /** @deprecated Use `partyInvites` instead. This alias will be removed in the next major version. */
    readonly "PartyInvites": Omit<typeof tablesSchema.schemaType.tables["partyInvites"], "accessorName"> & { readonly accessorName: "PartyInvites" };
    /** @deprecated Use `partyMembers` instead. This alias will be removed in the next major version. */
    readonly "PartyMembers": Omit<typeof tablesSchema.schemaType.tables["partyMembers"], "accessorName"> & { readonly accessorName: "PartyMembers" };
    /** @deprecated Use `quests` instead. This alias will be removed in the next major version. */
    readonly "Quests": Omit<typeof tablesSchema.schemaType.tables["quests"], "accessorName"> & { readonly accessorName: "Quests" };
    /** @deprecated Use `serverSettings` instead. This alias will be removed in the next major version. */
    readonly "ServerSettings": Omit<typeof tablesSchema.schemaType.tables["serverSettings"], "accessorName"> & { readonly accessorName: "ServerSettings" };
    /** @deprecated Use `spellButtonBindings` instead. This alias will be removed in the next major version. */
    readonly "SpellButtonBindings": Omit<typeof tablesSchema.schemaType.tables["spellButtonBindings"], "accessorName"> & { readonly accessorName: "SpellButtonBindings" };
    /** @deprecated Use `spells` instead. This alias will be removed in the next major version. */
    readonly "Spells": Omit<typeof tablesSchema.schemaType.tables["spells"], "accessorName"> & { readonly accessorName: "Spells" };
    /** @deprecated Use `statDefinitions` instead. This alias will be removed in the next major version. */
    readonly "StatDefinitions": Omit<typeof tablesSchema.schemaType.tables["statDefinitions"], "accessorName"> & { readonly accessorName: "StatDefinitions" };
    /** @deprecated Use `talentNodes` instead. This alias will be removed in the next major version. */
    readonly "TalentNodes": Omit<typeof tablesSchema.schemaType.tables["talentNodes"], "accessorName"> & { readonly accessorName: "TalentNodes" };
    /** @deprecated Use `worldObjects` instead. This alias will be removed in the next major version. */
    readonly "WorldObjects": Omit<typeof tablesSchema.schemaType.tables["worldObjects"], "accessorName"> & { readonly accessorName: "WorldObjects" };
    /** @deprecated Use `worldTime` instead. This alias will be removed in the next major version. */
    readonly "WorldTime": Omit<typeof tablesSchema.schemaType.tables["worldTime"], "accessorName"> & { readonly accessorName: "WorldTime" };
    /** @deprecated Use `accountCharacters` instead. This alias will be removed in the next major version. */
    readonly "AccountCharacters": Omit<typeof tablesSchema.schemaType.tables["accountCharacters"], "accessorName"> & { readonly accessorName: "AccountCharacters" };
    /** @deprecated Use `accountFriends` instead. This alias will be removed in the next major version. */
    readonly "AccountFriends": Omit<typeof tablesSchema.schemaType.tables["accountFriends"], "accessorName"> & { readonly accessorName: "AccountFriends" };
    /** @deprecated Use `calculatedSpellValues` instead. This alias will be removed in the next major version. */
    readonly "CalculatedSpellValues": Omit<typeof tablesSchema.schemaType.tables["calculatedSpellValues"], "accessorName"> & { readonly accessorName: "CalculatedSpellValues" };
    /** @deprecated Use `currentChunkCharacterStates` instead. This alias will be removed in the next major version. */
    readonly "CurrentChunkCharacterStates": Omit<typeof tablesSchema.schemaType.tables["currentChunkCharacterStates"], "accessorName"> & { readonly accessorName: "CurrentChunkCharacterStates" };
    /** @deprecated Use `currentChunkCombatLog` instead. This alias will be removed in the next major version. */
    readonly "CurrentChunkCombatLog": Omit<typeof tablesSchema.schemaType.tables["currentChunkCombatLog"], "accessorName"> & { readonly accessorName: "CurrentChunkCombatLog" };
    /** @deprecated Use `currentChunkEntities` instead. This alias will be removed in the next major version. */
    readonly "CurrentChunkEntities": Omit<typeof tablesSchema.schemaType.tables["currentChunkEntities"], "accessorName"> & { readonly accessorName: "CurrentChunkEntities" };
    /** @deprecated Use `currentChunkGameEvents` instead. This alias will be removed in the next major version. */
    readonly "CurrentChunkGameEvents": Omit<typeof tablesSchema.schemaType.tables["currentChunkGameEvents"], "accessorName"> & { readonly accessorName: "CurrentChunkGameEvents" };
    /** @deprecated Use `currentChunkLoot` instead. This alias will be removed in the next major version. */
    readonly "CurrentChunkLoot": Omit<typeof tablesSchema.schemaType.tables["currentChunkLoot"], "accessorName"> & { readonly accessorName: "CurrentChunkLoot" };
    /** @deprecated Use `questNpcEntities` instead. This alias will be removed in the next major version. */
    readonly "QuestNpcEntities": Omit<typeof tablesSchema.schemaType.tables["questNpcEntities"], "accessorName"> & { readonly accessorName: "QuestNpcEntities" };
    /** @deprecated Use `questTargetEntities` instead. This alias will be removed in the next major version. */
    readonly "QuestTargetEntities": Omit<typeof tablesSchema.schemaType.tables["questTargetEntities"], "accessorName"> & { readonly accessorName: "QuestTargetEntities" };
    /** @deprecated Use `questsWithProgress` instead. This alias will be removed in the next major version. */
    readonly "QuestsWithProgress": Omit<typeof tablesSchema.schemaType.tables["questsWithProgress"], "accessorName"> & { readonly accessorName: "QuestsWithProgress" };
    /** @deprecated Use `talentNodeStates` instead. This alias will be removed in the next major version. */
    readonly "TalentNodeStates": Omit<typeof tablesSchema.schemaType.tables["talentNodeStates"], "accessorName"> & { readonly accessorName: "TalentNodeStates" };
    /** @deprecated Use `talentPoints` instead. This alias will be removed in the next major version. */
    readonly "TalentPoints": Omit<typeof tablesSchema.schemaType.tables["talentPoints"], "accessorName"> & { readonly accessorName: "TalentPoints" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.7.0" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "ActionBarBindings": "actionBarBindings",
  "ActiveEffects": "activeEffects",
  "AuthSessions": "authSessions",
  "BagSlots": "bagSlots",
  "Bags": "bags",
  "BankSlots": "bankSlots",
  "ChangelogEntries": "changelogEntries",
  "CharacterCompendiumDiscoveries": "characterCompendiumDiscoveries",
  "CharacterCurrencies": "characterCurrencies",
  "CharacterEquipment": "characterEquipment",
  "CharacterMapFog": "characterMapFog",
  "CharacterRecallBinds": "characterRecallBinds",
  "CharacterStates": "characterStates",
  "CharacterStats": "characterStats",
  "CharacterTalents": "characterTalents",
  "CharacterTrackedQuests": "characterTrackedQuests",
  "Characters": "characters",
  "CharactersOffline": "charactersOffline",
  "ConsumableItems": "consumableItems",
  "Enemies": "enemies",
  "EquipmentItems": "equipmentItems",
  "Instances": "instances",
  "ItemDefinitions": "itemDefinitions",
  "ItemInstances": "itemInstances",
  "LevelRequirements": "levelRequirements",
  "LootTableEntries": "lootTableEntries",
  "MessageEvent": "messageEvent",
  "NpcEquipment": "npcEquipment",
  "Npcs": "npcs",
  "Parties": "parties",
  "PartyInvites": "partyInvites",
  "PartyMembers": "partyMembers",
  "Quests": "quests",
  "ServerSettings": "serverSettings",
  "SpellButtonBindings": "spellButtonBindings",
  "Spells": "spells",
  "StatDefinitions": "statDefinitions",
  "TalentNodes": "talentNodes",
  "WorldObjects": "worldObjects",
  "WorldTime": "worldTime",
  "AccountCharacters": "accountCharacters",
  "AccountFriends": "accountFriends",
  "CalculatedSpellValues": "calculatedSpellValues",
  "CurrentChunkCharacterStates": "currentChunkCharacterStates",
  "CurrentChunkCombatLog": "currentChunkCombatLog",
  "CurrentChunkEntities": "currentChunkEntities",
  "CurrentChunkGameEvents": "currentChunkGameEvents",
  "CurrentChunkLoot": "currentChunkLoot",
  "QuestNpcEntities": "questNpcEntities",
  "QuestTargetEntities": "questTargetEntities",
  "QuestsWithProgress": "questsWithProgress",
  "TalentNodeStates": "talentNodeStates",
  "TalentPoints": "talentPoints",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor],
    });
  }
  return freeze ? Object.freeze(out) : out;
}

type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  /** @deprecated Use `actionBarBindings` instead. This alias will be removed in the next major version. */
  readonly "ActionBarBindings": __DbViewBase["actionBarBindings"];
  /** @deprecated Use `activeEffects` instead. This alias will be removed in the next major version. */
  readonly "ActiveEffects": __DbViewBase["activeEffects"];
  /** @deprecated Use `authSessions` instead. This alias will be removed in the next major version. */
  readonly "AuthSessions": __DbViewBase["authSessions"];
  /** @deprecated Use `bagSlots` instead. This alias will be removed in the next major version. */
  readonly "BagSlots": __DbViewBase["bagSlots"];
  /** @deprecated Use `bags` instead. This alias will be removed in the next major version. */
  readonly "Bags": __DbViewBase["bags"];
  /** @deprecated Use `bankSlots` instead. This alias will be removed in the next major version. */
  readonly "BankSlots": __DbViewBase["bankSlots"];
  /** @deprecated Use `changelogEntries` instead. This alias will be removed in the next major version. */
  readonly "ChangelogEntries": __DbViewBase["changelogEntries"];
  /** @deprecated Use `characterCompendiumDiscoveries` instead. This alias will be removed in the next major version. */
  readonly "CharacterCompendiumDiscoveries": __DbViewBase["characterCompendiumDiscoveries"];
  /** @deprecated Use `characterCurrencies` instead. This alias will be removed in the next major version. */
  readonly "CharacterCurrencies": __DbViewBase["characterCurrencies"];
  /** @deprecated Use `characterEquipment` instead. This alias will be removed in the next major version. */
  readonly "CharacterEquipment": __DbViewBase["characterEquipment"];
  /** @deprecated Use `characterMapFog` instead. This alias will be removed in the next major version. */
  readonly "CharacterMapFog": __DbViewBase["characterMapFog"];
  /** @deprecated Use `characterRecallBinds` instead. This alias will be removed in the next major version. */
  readonly "CharacterRecallBinds": __DbViewBase["characterRecallBinds"];
  /** @deprecated Use `characterStates` instead. This alias will be removed in the next major version. */
  readonly "CharacterStates": __DbViewBase["characterStates"];
  /** @deprecated Use `characterStats` instead. This alias will be removed in the next major version. */
  readonly "CharacterStats": __DbViewBase["characterStats"];
  /** @deprecated Use `characterTalents` instead. This alias will be removed in the next major version. */
  readonly "CharacterTalents": __DbViewBase["characterTalents"];
  /** @deprecated Use `characterTrackedQuests` instead. This alias will be removed in the next major version. */
  readonly "CharacterTrackedQuests": __DbViewBase["characterTrackedQuests"];
  /** @deprecated Use `characters` instead. This alias will be removed in the next major version. */
  readonly "Characters": __DbViewBase["characters"];
  /** @deprecated Use `charactersOffline` instead. This alias will be removed in the next major version. */
  readonly "CharactersOffline": __DbViewBase["charactersOffline"];
  /** @deprecated Use `consumableItems` instead. This alias will be removed in the next major version. */
  readonly "ConsumableItems": __DbViewBase["consumableItems"];
  /** @deprecated Use `enemies` instead. This alias will be removed in the next major version. */
  readonly "Enemies": __DbViewBase["enemies"];
  /** @deprecated Use `equipmentItems` instead. This alias will be removed in the next major version. */
  readonly "EquipmentItems": __DbViewBase["equipmentItems"];
  /** @deprecated Use `instances` instead. This alias will be removed in the next major version. */
  readonly "Instances": __DbViewBase["instances"];
  /** @deprecated Use `itemDefinitions` instead. This alias will be removed in the next major version. */
  readonly "ItemDefinitions": __DbViewBase["itemDefinitions"];
  /** @deprecated Use `itemInstances` instead. This alias will be removed in the next major version. */
  readonly "ItemInstances": __DbViewBase["itemInstances"];
  /** @deprecated Use `levelRequirements` instead. This alias will be removed in the next major version. */
  readonly "LevelRequirements": __DbViewBase["levelRequirements"];
  /** @deprecated Use `lootTableEntries` instead. This alias will be removed in the next major version. */
  readonly "LootTableEntries": __DbViewBase["lootTableEntries"];
  /** @deprecated Use `messageEvent` instead. This alias will be removed in the next major version. */
  readonly "MessageEvent": __DbViewBase["messageEvent"];
  /** @deprecated Use `npcEquipment` instead. This alias will be removed in the next major version. */
  readonly "NpcEquipment": __DbViewBase["npcEquipment"];
  /** @deprecated Use `npcs` instead. This alias will be removed in the next major version. */
  readonly "Npcs": __DbViewBase["npcs"];
  /** @deprecated Use `parties` instead. This alias will be removed in the next major version. */
  readonly "Parties": __DbViewBase["parties"];
  /** @deprecated Use `partyInvites` instead. This alias will be removed in the next major version. */
  readonly "PartyInvites": __DbViewBase["partyInvites"];
  /** @deprecated Use `partyMembers` instead. This alias will be removed in the next major version. */
  readonly "PartyMembers": __DbViewBase["partyMembers"];
  /** @deprecated Use `quests` instead. This alias will be removed in the next major version. */
  readonly "Quests": __DbViewBase["quests"];
  /** @deprecated Use `serverSettings` instead. This alias will be removed in the next major version. */
  readonly "ServerSettings": __DbViewBase["serverSettings"];
  /** @deprecated Use `spellButtonBindings` instead. This alias will be removed in the next major version. */
  readonly "SpellButtonBindings": __DbViewBase["spellButtonBindings"];
  /** @deprecated Use `spells` instead. This alias will be removed in the next major version. */
  readonly "Spells": __DbViewBase["spells"];
  /** @deprecated Use `statDefinitions` instead. This alias will be removed in the next major version. */
  readonly "StatDefinitions": __DbViewBase["statDefinitions"];
  /** @deprecated Use `talentNodes` instead. This alias will be removed in the next major version. */
  readonly "TalentNodes": __DbViewBase["talentNodes"];
  /** @deprecated Use `worldObjects` instead. This alias will be removed in the next major version. */
  readonly "WorldObjects": __DbViewBase["worldObjects"];
  /** @deprecated Use `worldTime` instead. This alias will be removed in the next major version. */
  readonly "WorldTime": __DbViewBase["worldTime"];
  /** @deprecated Use `accountCharacters` instead. This alias will be removed in the next major version. */
  readonly "AccountCharacters": __DbViewBase["accountCharacters"];
  /** @deprecated Use `accountFriends` instead. This alias will be removed in the next major version. */
  readonly "AccountFriends": __DbViewBase["accountFriends"];
  /** @deprecated Use `calculatedSpellValues` instead. This alias will be removed in the next major version. */
  readonly "CalculatedSpellValues": __DbViewBase["calculatedSpellValues"];
  /** @deprecated Use `currentChunkCharacterStates` instead. This alias will be removed in the next major version. */
  readonly "CurrentChunkCharacterStates": __DbViewBase["currentChunkCharacterStates"];
  /** @deprecated Use `currentChunkCombatLog` instead. This alias will be removed in the next major version. */
  readonly "CurrentChunkCombatLog": __DbViewBase["currentChunkCombatLog"];
  /** @deprecated Use `currentChunkEntities` instead. This alias will be removed in the next major version. */
  readonly "CurrentChunkEntities": __DbViewBase["currentChunkEntities"];
  /** @deprecated Use `currentChunkGameEvents` instead. This alias will be removed in the next major version. */
  readonly "CurrentChunkGameEvents": __DbViewBase["currentChunkGameEvents"];
  /** @deprecated Use `currentChunkLoot` instead. This alias will be removed in the next major version. */
  readonly "CurrentChunkLoot": __DbViewBase["currentChunkLoot"];
  /** @deprecated Use `questNpcEntities` instead. This alias will be removed in the next major version. */
  readonly "QuestNpcEntities": __DbViewBase["questNpcEntities"];
  /** @deprecated Use `questTargetEntities` instead. This alias will be removed in the next major version. */
  readonly "QuestTargetEntities": __DbViewBase["questTargetEntities"];
  /** @deprecated Use `questsWithProgress` instead. This alias will be removed in the next major version. */
  readonly "QuestsWithProgress": __DbViewBase["questsWithProgress"];
  /** @deprecated Use `talentNodeStates` instead. This alias will be removed in the next major version. */
  readonly "TalentNodeStates": __DbViewBase["talentNodeStates"];
  /** @deprecated Use `talentPoints` instead. This alias will be removed in the next major version. */
  readonly "TalentPoints": __DbViewBase["talentPoints"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  /** @deprecated Use `actionBarBindings` instead. This alias will be removed in the next major version. */
  readonly "ActionBarBindings": __TablesBase["actionBarBindings"];
  /** @deprecated Use `activeEffects` instead. This alias will be removed in the next major version. */
  readonly "ActiveEffects": __TablesBase["activeEffects"];
  /** @deprecated Use `authSessions` instead. This alias will be removed in the next major version. */
  readonly "AuthSessions": __TablesBase["authSessions"];
  /** @deprecated Use `bagSlots` instead. This alias will be removed in the next major version. */
  readonly "BagSlots": __TablesBase["bagSlots"];
  /** @deprecated Use `bags` instead. This alias will be removed in the next major version. */
  readonly "Bags": __TablesBase["bags"];
  /** @deprecated Use `bankSlots` instead. This alias will be removed in the next major version. */
  readonly "BankSlots": __TablesBase["bankSlots"];
  /** @deprecated Use `changelogEntries` instead. This alias will be removed in the next major version. */
  readonly "ChangelogEntries": __TablesBase["changelogEntries"];
  /** @deprecated Use `characterCompendiumDiscoveries` instead. This alias will be removed in the next major version. */
  readonly "CharacterCompendiumDiscoveries": __TablesBase["characterCompendiumDiscoveries"];
  /** @deprecated Use `characterCurrencies` instead. This alias will be removed in the next major version. */
  readonly "CharacterCurrencies": __TablesBase["characterCurrencies"];
  /** @deprecated Use `characterEquipment` instead. This alias will be removed in the next major version. */
  readonly "CharacterEquipment": __TablesBase["characterEquipment"];
  /** @deprecated Use `characterMapFog` instead. This alias will be removed in the next major version. */
  readonly "CharacterMapFog": __TablesBase["characterMapFog"];
  /** @deprecated Use `characterRecallBinds` instead. This alias will be removed in the next major version. */
  readonly "CharacterRecallBinds": __TablesBase["characterRecallBinds"];
  /** @deprecated Use `characterStates` instead. This alias will be removed in the next major version. */
  readonly "CharacterStates": __TablesBase["characterStates"];
  /** @deprecated Use `characterStats` instead. This alias will be removed in the next major version. */
  readonly "CharacterStats": __TablesBase["characterStats"];
  /** @deprecated Use `characterTalents` instead. This alias will be removed in the next major version. */
  readonly "CharacterTalents": __TablesBase["characterTalents"];
  /** @deprecated Use `characterTrackedQuests` instead. This alias will be removed in the next major version. */
  readonly "CharacterTrackedQuests": __TablesBase["characterTrackedQuests"];
  /** @deprecated Use `characters` instead. This alias will be removed in the next major version. */
  readonly "Characters": __TablesBase["characters"];
  /** @deprecated Use `charactersOffline` instead. This alias will be removed in the next major version. */
  readonly "CharactersOffline": __TablesBase["charactersOffline"];
  /** @deprecated Use `consumableItems` instead. This alias will be removed in the next major version. */
  readonly "ConsumableItems": __TablesBase["consumableItems"];
  /** @deprecated Use `enemies` instead. This alias will be removed in the next major version. */
  readonly "Enemies": __TablesBase["enemies"];
  /** @deprecated Use `equipmentItems` instead. This alias will be removed in the next major version. */
  readonly "EquipmentItems": __TablesBase["equipmentItems"];
  /** @deprecated Use `instances` instead. This alias will be removed in the next major version. */
  readonly "Instances": __TablesBase["instances"];
  /** @deprecated Use `itemDefinitions` instead. This alias will be removed in the next major version. */
  readonly "ItemDefinitions": __TablesBase["itemDefinitions"];
  /** @deprecated Use `itemInstances` instead. This alias will be removed in the next major version. */
  readonly "ItemInstances": __TablesBase["itemInstances"];
  /** @deprecated Use `levelRequirements` instead. This alias will be removed in the next major version. */
  readonly "LevelRequirements": __TablesBase["levelRequirements"];
  /** @deprecated Use `lootTableEntries` instead. This alias will be removed in the next major version. */
  readonly "LootTableEntries": __TablesBase["lootTableEntries"];
  /** @deprecated Use `messageEvent` instead. This alias will be removed in the next major version. */
  readonly "MessageEvent": __TablesBase["messageEvent"];
  /** @deprecated Use `npcEquipment` instead. This alias will be removed in the next major version. */
  readonly "NpcEquipment": __TablesBase["npcEquipment"];
  /** @deprecated Use `npcs` instead. This alias will be removed in the next major version. */
  readonly "Npcs": __TablesBase["npcs"];
  /** @deprecated Use `parties` instead. This alias will be removed in the next major version. */
  readonly "Parties": __TablesBase["parties"];
  /** @deprecated Use `partyInvites` instead. This alias will be removed in the next major version. */
  readonly "PartyInvites": __TablesBase["partyInvites"];
  /** @deprecated Use `partyMembers` instead. This alias will be removed in the next major version. */
  readonly "PartyMembers": __TablesBase["partyMembers"];
  /** @deprecated Use `quests` instead. This alias will be removed in the next major version. */
  readonly "Quests": __TablesBase["quests"];
  /** @deprecated Use `serverSettings` instead. This alias will be removed in the next major version. */
  readonly "ServerSettings": __TablesBase["serverSettings"];
  /** @deprecated Use `spellButtonBindings` instead. This alias will be removed in the next major version. */
  readonly "SpellButtonBindings": __TablesBase["spellButtonBindings"];
  /** @deprecated Use `spells` instead. This alias will be removed in the next major version. */
  readonly "Spells": __TablesBase["spells"];
  /** @deprecated Use `statDefinitions` instead. This alias will be removed in the next major version. */
  readonly "StatDefinitions": __TablesBase["statDefinitions"];
  /** @deprecated Use `talentNodes` instead. This alias will be removed in the next major version. */
  readonly "TalentNodes": __TablesBase["talentNodes"];
  /** @deprecated Use `worldObjects` instead. This alias will be removed in the next major version. */
  readonly "WorldObjects": __TablesBase["worldObjects"];
  /** @deprecated Use `worldTime` instead. This alias will be removed in the next major version. */
  readonly "WorldTime": __TablesBase["worldTime"];
  /** @deprecated Use `accountCharacters` instead. This alias will be removed in the next major version. */
  readonly "AccountCharacters": __TablesBase["accountCharacters"];
  /** @deprecated Use `accountFriends` instead. This alias will be removed in the next major version. */
  readonly "AccountFriends": __TablesBase["accountFriends"];
  /** @deprecated Use `calculatedSpellValues` instead. This alias will be removed in the next major version. */
  readonly "CalculatedSpellValues": __TablesBase["calculatedSpellValues"];
  /** @deprecated Use `currentChunkCharacterStates` instead. This alias will be removed in the next major version. */
  readonly "CurrentChunkCharacterStates": __TablesBase["currentChunkCharacterStates"];
  /** @deprecated Use `currentChunkCombatLog` instead. This alias will be removed in the next major version. */
  readonly "CurrentChunkCombatLog": __TablesBase["currentChunkCombatLog"];
  /** @deprecated Use `currentChunkEntities` instead. This alias will be removed in the next major version. */
  readonly "CurrentChunkEntities": __TablesBase["currentChunkEntities"];
  /** @deprecated Use `currentChunkGameEvents` instead. This alias will be removed in the next major version. */
  readonly "CurrentChunkGameEvents": __TablesBase["currentChunkGameEvents"];
  /** @deprecated Use `currentChunkLoot` instead. This alias will be removed in the next major version. */
  readonly "CurrentChunkLoot": __TablesBase["currentChunkLoot"];
  /** @deprecated Use `questNpcEntities` instead. This alias will be removed in the next major version. */
  readonly "QuestNpcEntities": __TablesBase["questNpcEntities"];
  /** @deprecated Use `questTargetEntities` instead. This alias will be removed in the next major version. */
  readonly "QuestTargetEntities": __TablesBase["questTargetEntities"];
  /** @deprecated Use `questsWithProgress` instead. This alias will be removed in the next major version. */
  readonly "QuestsWithProgress": __TablesBase["questsWithProgress"];
  /** @deprecated Use `talentNodeStates` instead. This alias will be removed in the next major version. */
  readonly "TalentNodeStates": __TablesBase["talentNodeStates"];
  /** @deprecated Use `talentPoints` instead. This alias will be removed in the next major version. */
  readonly "TalentPoints": __TablesBase["talentPoints"];
};

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for error events. */
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

