// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  name: __t.string(),
  description: __t.string(),
  itemType: __t.i32().name("item_type"),
  itemSubType: __t.i32().name("item_sub_type"),
  iconTexture: __t.string().name("icon_texture"),
  modelPath: __t.option(__t.string()).name("model_path"),
  maxStackSize: __t.i32().name("max_stack_size"),
  sellPrice: __t.i32().name("sell_price"),
});
