// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  enemyId: __t.u32().name("enemy_id"),
  lootTableName: __t.string().name("loot_table_name"),
  itemId: __t.i32().name("item_id"),
  dropChancePercent: __t.f32().name("drop_chance_percent"),
  minQuantity: __t.i32().name("min_quantity"),
  maxQuantity: __t.i32().name("max_quantity"),
  rolls: __t.i32(),
});
