// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  npcId: __t.u32().primaryKey().name("npc_id"),
  headItemId: __t.i32().name("head_item_id"),
  backItemId: __t.i32().name("back_item_id"),
  shoulderItemId: __t.i32().name("shoulder_item_id"),
  mainHandItemId: __t.i32().name("main_hand_item_id"),
  offHandItemId: __t.i32().name("off_hand_item_id"),
});
