// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  name: __t.string(),
  level: __t.i32(),
  modelPath: __t.string().name("model_path"),
  scale: __t.f32(),
  greetingText: __t.string().name("greeting_text"),
  sexSelection: __t.i32().name("sex_selection"),
  hairStyleSelection: __t.i32().name("hair_style_selection"),
  hairColorSelection: __t.i32().name("hair_color_selection"),
  role: __t.string(),
});
