// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  QuestObjective,
} from "./types";


export default __t.row({
  id: __t.i32(),
  name: __t.string(),
  pickupNpcId: __t.option(__t.u32()).name("pickup_npc_id"),
  dropOffNpcId: __t.option(__t.u32()).name("drop_off_npc_id"),
  pickupItemName: __t.option(__t.string()).name("pickup_item_name"),
  description: __t.string(),
  xpReward: __t.u64().name("xp_reward"),
  levelRequired: __t.i32().name("level_required"),
  questRequired: __t.i32().name("quest_required"),
  shortDescription: __t.string().name("short_description"),
  taskAmount: __t.i32().name("task_amount"),
  objectiveType: __t.i32().name("objective_type"),
  get objectives() {
    return __t.array(QuestObjective);
  },
  rewardAllItems: __t.bool().name("reward_all_items"),
  questRewardItems: __t.array(__t.i32()).name("quest_reward_items"),
});
