// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DbVector3,
} from "./types";


export default __t.row({
  entityId: __t.u32().primaryKey().name("entity_id"),
  entityTypeId: __t.u8().name("entity_type_id"),
  entityDataId: __t.u32().name("entity_data_id"),
  get position() {
    return DbVector3;
  },
  isAlive: __t.bool().name("is_alive"),
});
