// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  QuestObjectiveProgress,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  characterId: __t.u64().name("character_id"),
  questId: __t.i32().name("quest_id"),
  currentAmount: __t.i32().name("current_amount"),
  requiredAmount: __t.i32().name("required_amount"),
  get objectiveProgresses() {
    return __t.array(QuestObjectiveProgress).name("objective_progresses");
  },
  isComplete: __t.bool().name("is_complete"),
  isActive: __t.bool().name("is_active"),
  startedAt: __t.timestamp().name("started_at"),
  completedAt: __t.timestamp().name("completed_at"),
});
