// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  materialTier: __t.i32().name("material_tier"),
  refinementLevel: __t.i32().name("refinement_level"),
  materialItemId: __t.i32().name("material_item_id"),
  materialQuantity: __t.i32().name("material_quantity"),
  copperCost: __t.i32().name("copper_cost"),
});
