// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  npcId: __t.u32(),
  headItemId: __t.i32(),
  backItemId: __t.i32(),
  shoulderItemId: __t.i32(),
  mainHandItemId: __t.i32(),
  offHandItemId: __t.i32(),
  targetId: __t.string(),
};
