// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  description: __t.string(),
  iconTexture: __t.string().name("icon_texture"),
  castTime: __t.f32().name("cast_time"),
  cooldown: __t.f32(),
  minRange: __t.f32().name("min_range"),
  maxRange: __t.f32().name("max_range"),
  resourceGenerated: __t.i32().name("resource_generated"),
  resourceCost: __t.i32().name("resource_cost"),
  damage: __t.f32(),
  classRequired: __t.i32().name("class_required"),
  levelRequired: __t.i32().name("level_required"),
  isInstant: __t.bool().name("is_instant"),
  activeEffectType: __t.i32().name("active_effect_type"),
  activeEffectIsBuff: __t.bool().name("active_effect_is_buff"),
  activeEffectIsDurationless: __t.bool().name("active_effect_is_durationless"),
  activeEffectTarget: __t.i32().name("active_effect_target"),
  activeEffectDuration: __t.f32().name("active_effect_duration"),
  activeEffectTickInterval: __t.f32().name("active_effect_tick_interval"),
  activeEffectAmount: __t.f32().name("active_effect_amount"),
});
