// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  characterId: __t.u64().primaryKey().name("character_id"),
  spellPointsEarned: __t.i32().name("spell_points_earned"),
  spellPointsSpent: __t.i32().name("spell_points_spent"),
  attributePointsEarned: __t.i32().name("attribute_points_earned"),
  attributePointsSpent: __t.i32().name("attribute_points_spent"),
});
