// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  initiatorCharacterId: __t.u64().name("initiator_character_id"),
  targetCharacterId: __t.u64().name("target_character_id"),
  initiatorAccepted: __t.bool().name("initiator_accepted"),
  targetAccepted: __t.bool().name("target_accepted"),
  initiatorOfferedCopper: __t.i64().name("initiator_offered_copper"),
  targetOfferedCopper: __t.i64().name("target_offered_copper"),
  createdAt: __t.timestamp().name("created_at"),
});
