// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  tradeId: __t.u64().name("trade_id"),
  characterId: __t.u64().name("character_id"),
  slotIndex: __t.i32().name("slot_index"),
  itemInstanceId: __t.i32().name("item_instance_id"),
  itemId: __t.i32().name("item_id"),
  quantity: __t.i32(),
  qualityLevel: __t.i32().name("quality_level"),
  instabilityTier: __t.i32().name("instability_tier"),
});
