// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AccountAcquaintance = __t.object("AccountAcquaintance", {
  id: __t.u64(),
  ownerAccountId: __t.identity(),
  otherCharacterId: __t.u64(),
  groupedCount: __t.i32(),
  whisperCount: __t.i32(),
  tradeCount: __t.i32(),
  firstMetAt: __t.timestamp(),
  lastInteractionAt: __t.timestamp(),
});
export type AccountAcquaintance = __Infer<typeof AccountAcquaintance>;

export const AccountAcquaintanceSummary = __t.object("AccountAcquaintanceSummary", {
  id: __t.u64(),
  otherCharacterId: __t.u64(),
  groupedCount: __t.i32(),
  whisperCount: __t.i32(),
  tradeCount: __t.i32(),
  firstMetAt: __t.timestamp(),
  lastInteractionAt: __t.timestamp(),
});
export type AccountAcquaintanceSummary = __Infer<typeof AccountAcquaintanceSummary>;

export const AccountConnection = __t.object("AccountConnection", {
  accountId: __t.identity(),
  connectionKey: __t.string(),
});
export type AccountConnection = __Infer<typeof AccountConnection>;

export const AccountFriend = __t.object("AccountFriend", {
  id: __t.u64(),
  ownerAccountId: __t.identity(),
  friendAccountId: __t.identity(),
  friendCharacterId: __t.u64(),
  friendName: __t.string(),
  friendTag: __t.i32(),
  addedAt: __t.timestamp(),
});
export type AccountFriend = __Infer<typeof AccountFriend>;

export const AccountFriendPresence = __t.object("AccountFriendPresence", {
  id: __t.u64(),
  friendAccountId: __t.identity(),
  friendCharacterId: __t.u64(),
  friendName: __t.string(),
  friendTag: __t.i32(),
  isOnline: __t.bool(),
  zoneName: __t.string(),
});
export type AccountFriendPresence = __Infer<typeof AccountFriendPresence>;

export const ActionBarBinding = __t.object("ActionBarBinding", {
  id: __t.string(),
  characterId: __t.u64(),
  buttonIndex: __t.i32(),
  bindingType: __t.i32(),
  actionId: __t.u64(),
});
export type ActionBarBinding = __Infer<typeof ActionBarBinding>;

export const ActiveEffect = __t.object("ActiveEffect", {
  id: __t.u64(),
  spellId: __t.u64(),
  sourceCharacterId: __t.u64(),
  targetCharacterId: __t.u64(),
  targetEntityId: __t.u32(),
  targetType: __t.u8(),
  effectType: __t.i32(),
  isBuff: __t.bool(),
  appliedAtUnix: __t.i64(),
  expiresAtUnix: __t.i64(),
  nextTickAtUnix: __t.i64(),
  tickIntervalMs: __t.i32(),
  amount: __t.f32(),
  sourceItemId: __t.i32(),
  sourceProcId: __t.i32(),
  displayExpiresAtUnix: __t.i64(),
  sourceEnemyEntityId: __t.u32(),
  sourceEnemyId: __t.u32(),
});
export type ActiveEffect = __Infer<typeof ActiveEffect>;

export const ActiveEnemyCast = __t.object("ActiveEnemyCast", {
  enemyEntityId: __t.u32(),
  spellId: __t.u64(),
  abilitySlot: __t.i32(),
  rosterLength: __t.i32(),
  targetCharacterId: __t.u64(),
  startedAtUnix: __t.i64(),
  completesAtUnix: __t.i64(),
  instanceId: __t.u32(),
  chunkX: __t.i32(),
  chunkZ: __t.i32(),
});
export type ActiveEnemyCast = __Infer<typeof ActiveEnemyCast>;

export const ActiveEnemyEntity = __t.object("ActiveEnemyEntity", {
  enemyEntityId: __t.u32(),
  navigationRecoveryMode: __t.u8(),
  navigationRecoveryDeadlineUnix: __t.i64(),
  navigationRecoveryAnchorX: __t.f32(),
  navigationRecoveryAnchorZ: __t.f32(),
});
export type ActiveEnemyEntity = __Infer<typeof ActiveEnemyEntity>;

export const ActivityCycleRow = __t.object("ActivityCycleRow", {
  cadence: __t.i32(),
  cycleNumber: __t.i32(),
  startsAtUnix: __t.i64(),
  endsAtUnix: __t.i64(),
});
export type ActivityCycleRow = __Infer<typeof ActivityCycleRow>;

export const ActivityTaskRow = __t.object("ActivityTaskRow", {
  id: __t.u32(),
  cadence: __t.i32(),
  cycleNumber: __t.i32(),
  kind: __t.i32(),
  targetId: __t.u32(),
  zoneName: __t.string(),
  requiredAmount: __t.i32(),
  points: __t.i32(),
  recommendedLevel: __t.i32(),
  title: __t.string(),
  description: __t.string(),
  hasMarker: __t.bool(),
  markerX: __t.f32(),
  markerZ: __t.f32(),
  markerRadius: __t.f32(),
  sortOrder: __t.i32(),
});
export type ActivityTaskRow = __Infer<typeof ActivityTaskRow>;

export const AmbientEnemyTickTimer = __t.object("AmbientEnemyTickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type AmbientEnemyTickTimer = __Infer<typeof AmbientEnemyTickTimer>;

export const AreaEffect = __t.object("AreaEffect", {
  id: __t.u64(),
  spellId: __t.u64(),
  sourceCharacterId: __t.u64(),
  get position() {
    return DbVector3;
  },
  radius: __t.f32(),
  appliedAtUnix: __t.i64(),
  expiresAtUnix: __t.i64(),
  effectType: __t.i32(),
  isBuff: __t.bool(),
  amount: __t.f32(),
  followTargetEntityId: __t.option(__t.u32()),
  followsSourceCharacter: __t.bool(),
  instanceId: __t.u32(),
});
export type AreaEffect = __Infer<typeof AreaEffect>;

export const AreaEffectTarget = __t.object("AreaEffectTarget", {
  id: __t.u64(),
  areaEffectId: __t.u64(),
  targetCharacterId: __t.u64(),
  activeEffectId: __t.u64(),
});
export type AreaEffectTarget = __Infer<typeof AreaEffectTarget>;

export const AugmentDefinition = __t.object("AugmentDefinition", {
  itemId: __t.i32(),
  tier: __t.i32(),
  primaryStatId: __t.i32(),
  primaryBaseCentis: __t.i32(),
  primaryPerLevelCentis: __t.i32(),
  secondaryStatId: __t.i32(),
  secondaryBaseCentis: __t.i32(),
  secondaryPerLevelCentis: __t.i32(),
  maxLevel: __t.i32(),
  itemLevelRequirement: __t.i32(),
});
export type AugmentDefinition = __Infer<typeof AugmentDefinition>;

export const AugmentUpgradeCost = __t.object("AugmentUpgradeCost", {
  id: __t.i32(),
  augmentTier: __t.i32(),
  augmentLevel: __t.i32(),
  materialItemId: __t.i32(),
  materialQuantity: __t.i32(),
  copperCost: __t.i32(),
});
export type AugmentUpgradeCost = __Infer<typeof AugmentUpgradeCost>;

export const AuthSession = __t.object("AuthSession", {
  accountId: __t.identity(),
  loginMethod: __t.string(),
  providerId: __t.string(),
  preferredUsername: __t.string(),
  picture: __t.string(),
  isSteam: __t.bool(),
  ownsConfiguredSteamApp: __t.bool(),
  connectedAt: __t.timestamp(),
  isQueued: __t.bool(),
  queuePosition: __t.i32(),
  clientVersion: __t.i32(),
});
export type AuthSession = __Infer<typeof AuthSession>;

export const Bag = __t.object("Bag", {
  id: __t.i32(),
  name: __t.string(),
  characterId: __t.u64(),
  size: __t.i32(),
  isBank: __t.bool(),
});
export type Bag = __Infer<typeof Bag>;

export const BagSlot = __t.object("BagSlot", {
  id: __t.i32(),
  bagId: __t.i32(),
  itemInstanceId: __t.i32(),
  characterId: __t.u64(),
});
export type BagSlot = __Infer<typeof BagSlot>;

export const BankSlot = __t.object("BankSlot", {
  id: __t.i32(),
  itemInstanceId: __t.i32(),
  characterId: __t.u64(),
  tabIndex: __t.i32(),
});
export type BankSlot = __Infer<typeof BankSlot>;

export const BankTab = __t.object("BankTab", {
  id: __t.i32(),
  characterId: __t.u64(),
  tabIndex: __t.i32(),
  name: __t.string(),
});
export type BankTab = __Infer<typeof BankTab>;

export const BreachRewardEntry = __t.object("BreachRewardEntry", {
  id: __t.i32(),
  mapId: __t.string(),
  itemId: __t.i32(),
  rewardKind: __t.i32(),
});
export type BreachRewardEntry = __Infer<typeof BreachRewardEntry>;

export const CalculatedSpellValues = __t.object("CalculatedSpellValues", {
  id: __t.string(),
  characterId: __t.u64(),
  spellId: __t.u64(),
  damage: __t.f32(),
  healing: __t.f32(),
  castTime: __t.f32(),
  activeEffectAmount: __t.f32(),
  activeEffectDuration: __t.f32(),
  talentRank: __t.i32(),
  isUnlocked: __t.bool(),
});
export type CalculatedSpellValues = __Infer<typeof CalculatedSpellValues>;

export const ChangelogEntry = __t.object("ChangelogEntry", {
  id: __t.u32(),
  description: __t.string(),
  date: __t.string(),
});
export type ChangelogEntry = __Infer<typeof ChangelogEntry>;

export const Character = __t.object("Character", {
  id: __t.u64(),
  accountId: __t.identity(),
  name: __t.string(),
  raceSelection: __t.i32(),
  sexSelection: __t.i32(),
  classSelection: __t.i32(),
  createdAt: __t.timestamp(),
  deletedAt: __t.timestamp(),
  lastPlayed: __t.timestamp(),
  tag: __t.i32(),
  skinToneSelection: __t.i32(),
  hairStyleSelection: __t.i32(),
  hairColorSelection: __t.i32(),
  zoneName: __t.string(),
});
export type Character = __Infer<typeof Character>;

export const CharacterAbilityCooldown = __t.object("CharacterAbilityCooldown", {
  id: __t.string(),
  characterId: __t.u64(),
  spellId: __t.u64(),
  readyAtUnix: __t.i64(),
});
export type CharacterAbilityCooldown = __Infer<typeof CharacterAbilityCooldown>;

export const CharacterActionBarSetting = __t.object("CharacterActionBarSetting", {
  characterId: __t.u64(),
  visibleBarCount: __t.i32(),
});
export type CharacterActionBarSetting = __Infer<typeof CharacterActionBarSetting>;

export const CharacterActivityProgressRow = __t.object("CharacterActivityProgressRow", {
  id: __t.u64(),
  characterId: __t.u64(),
  taskId: __t.u32(),
  cadence: __t.i32(),
  cycleNumber: __t.i32(),
  currentAmount: __t.i32(),
  isComplete: __t.bool(),
  completedAtUnix: __t.i64(),
});
export type CharacterActivityProgressRow = __Infer<typeof CharacterActivityProgressRow>;

export const CharacterBreachProgressRow = __t.object("CharacterBreachProgressRow", {
  id: __t.u64(),
  characterId: __t.u64(),
  mapId: __t.string(),
  highestClearedInstability: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type CharacterBreachProgressRow = __Infer<typeof CharacterBreachProgressRow>;

export const CharacterChunkPosition = __t.object("CharacterChunkPosition", {
  characterId: __t.u64(),
  instanceId: __t.u32(),
  chunkX: __t.i32(),
  chunkZ: __t.i32(),
});
export type CharacterChunkPosition = __Infer<typeof CharacterChunkPosition>;

export const CharacterClass = __t.object("CharacterClass", {
  id: __t.i32(),
  name: __t.string(),
  maxHealth: __t.i32(),
  maxEnergy: __t.i32(),
  starterWeaponItemId: __t.i32(),
});
export type CharacterClass = __Infer<typeof CharacterClass>;

export const CharacterCompendiumDiscovery = __t.object("CharacterCompendiumDiscovery", {
  id: __t.u64(),
  characterId: __t.u64(),
  entryType: __t.string(),
  entryId: __t.u32(),
  discoveredAt: __t.timestamp(),
  isSeen: __t.bool(),
  bestQuality: __t.i32(),
  bestFishWeightTenths: __t.i32(),
});
export type CharacterCompendiumDiscovery = __Infer<typeof CharacterCompendiumDiscovery>;

export const CharacterCurrency = __t.object("CharacterCurrency", {
  characterId: __t.u64(),
  gold: __t.i32(),
  silver: __t.i32(),
  copper: __t.i32(),
});
export type CharacterCurrency = __Infer<typeof CharacterCurrency>;

export const CharacterEquipment = __t.object("CharacterEquipment", {
  characterId: __t.u64(),
  headSlotItemInstanceId: __t.i32(),
  neckSlotItemInstanceId: __t.i32(),
  backSlotItemInstanceId: __t.i32(),
  shoulderSlotItemInstanceId: __t.i32(),
  chestSlotItemInstanceId: __t.i32(),
  waistSlotItemInstanceId: __t.i32(),
  legSlotItemInstanceId: __t.i32(),
  footSlotItemInstanceId: __t.i32(),
  mainHandSlotItemInstanceId: __t.i32(),
  offHandSlotItemInstanceId: __t.i32(),
  handSlotItemInstanceId: __t.i32(),
  pickaxeSlotItemInstanceId: __t.i32(),
  fishingRodSlotItemInstanceId: __t.i32(),
});
export type CharacterEquipment = __Infer<typeof CharacterEquipment>;

export const CharacterMapFog = __t.object("CharacterMapFog", {
  id: __t.u64(),
  characterId: __t.u64(),
  zoneName: __t.string(),
  cellX: __t.i32(),
  cellY: __t.i32(),
  discoveredAt: __t.timestamp(),
});
export type CharacterMapFog = __Infer<typeof CharacterMapFog>;

export const CharacterMapFogBlock = __t.object("CharacterMapFogBlock", {
  id: __t.u64(),
  characterId: __t.u64(),
  blockX: __t.i32(),
  blockY: __t.i32(),
  cells: __t.byteArray(),
  updatedAt: __t.timestamp(),
});
export type CharacterMapFogBlock = __Infer<typeof CharacterMapFogBlock>;

export const CharacterMotionSample = __t.object("CharacterMotionSample", {
  characterId: __t.u64(),
  velocityX: __t.f32(),
  velocityZ: __t.f32(),
  lastObservedUnix: __t.i64(),
  lastAggroCheckUnix: __t.i64(),
  isGrounded: __t.bool(),
  airborneSinceUnix: __t.i64(),
  airbornePeakY: __t.f32(),
  lastSwimmingUnix: __t.i64(),
});
export type CharacterMotionSample = __Infer<typeof CharacterMotionSample>;

export const CharacterQuest = __t.object("CharacterQuest", {
  questId: __t.i32(),
  get questData() {
    return __t.option(Quest);
  },
  get progress() {
    return __t.option(QuestProgress);
  },
});
export type CharacterQuest = __Infer<typeof CharacterQuest>;

export const CharacterRecallBind = __t.object("CharacterRecallBind", {
  characterId: __t.u64(),
  npcId: __t.u32(),
  get position() {
    return DbVector3;
  },
  rotation: __t.f64(),
});
export type CharacterRecallBind = __Infer<typeof CharacterRecallBind>;

export const CharacterServiceRecordRow = __t.object("CharacterServiceRecordRow", {
  characterId: __t.u64(),
  lifetimeMarks: __t.i32(),
  rank: __t.i32(),
  activeTitleRank: __t.i32(),
});
export type CharacterServiceRecordRow = __Infer<typeof CharacterServiceRecordRow>;

export const CharacterServiceRewardClaimRow = __t.object("CharacterServiceRewardClaimRow", {
  id: __t.u64(),
  characterId: __t.u64(),
  rank: __t.i32(),
  claimedAtUnix: __t.i64(),
});
export type CharacterServiceRewardClaimRow = __Infer<typeof CharacterServiceRewardClaimRow>;

export const CharacterSkill = __t.object("CharacterSkill", {
  id: __t.u64(),
  characterId: __t.u64(),
  skillId: __t.i32(),
  level: __t.i32(),
  xp: __t.i32(),
});
export type CharacterSkill = __Infer<typeof CharacterSkill>;

export const CharacterState = __t.object("CharacterState", {
  characterId: __t.u64(),
  get position() {
    return DbVector3;
  },
  chunkX: __t.i32(),
  chunkZ: __t.i32(),
  rotation: __t.f64(),
  isWeaponDrawn: __t.bool(),
  isSitting: __t.bool(),
  instanceId: __t.u32(),
  isSwimming: __t.bool(),
  isInLava: __t.bool(),
});
export type CharacterState = __Infer<typeof CharacterState>;

export const CharacterStats = __t.object("CharacterStats", {
  characterId: __t.u64(),
  level: __t.i32(),
  xp: __t.u64(),
  health: __t.i32(),
  maxHealth: __t.i32(),
  energy: __t.i32(),
  maxEnergy: __t.i32(),
  vitality: __t.i32(),
  fortitude: __t.i32(),
  strength: __t.i32(),
  grace: __t.i32(),
  alacrity: __t.i32(),
  tempo: __t.i32(),
  accuracy: __t.i32(),
  swimFatigueMs: __t.i32(),
});
export type CharacterStats = __Infer<typeof CharacterStats>;

export const CharacterSummary = __t.object("CharacterSummary", {
  id: __t.u64(),
  accountId: __t.identity(),
  name: __t.string(),
  raceSelection: __t.i32(),
  sexSelection: __t.i32(),
  classSelection: __t.i32(),
  get position() {
    return DbVector3;
  },
  chunkX: __t.i32(),
  chunkZ: __t.i32(),
  rotation: __t.f64(),
  level: __t.i32(),
  xp: __t.u64(),
  health: __t.i32(),
  maxHealth: __t.i32(),
  energy: __t.i32(),
  maxEnergy: __t.i32(),
  vitality: __t.i32(),
  fortitude: __t.i32(),
  strength: __t.i32(),
  grace: __t.i32(),
  alacrity: __t.i32(),
  tempo: __t.i32(),
  accuracy: __t.i32(),
  createdAt: __t.timestamp(),
  deletedAt: __t.timestamp(),
  lastPlayed: __t.timestamp(),
  isWeaponDrawn: __t.bool(),
  isSwimming: __t.bool(),
  swimFatigueMs: __t.i32(),
  tag: __t.i32(),
  gold: __t.i32(),
  skinToneSelection: __t.i32(),
  hairStyleSelection: __t.i32(),
  hairColorSelection: __t.i32(),
  silver: __t.i32(),
  copper: __t.i32(),
  zoneName: __t.string(),
});
export type CharacterSummary = __Infer<typeof CharacterSummary>;

export const CharacterTalent = __t.object("CharacterTalent", {
  id: __t.u64(),
  characterId: __t.u64(),
  nodeId: __t.i32(),
  rank: __t.i32(),
});
export type CharacterTalent = __Infer<typeof CharacterTalent>;

export const CharacterTrackedQuest = __t.object("CharacterTrackedQuest", {
  characterId: __t.u64(),
  questId: __t.i32(),
});
export type CharacterTrackedQuest = __Infer<typeof CharacterTrackedQuest>;

export const CharacterTransferCredit = __t.object("CharacterTransferCredit", {
  accountId: __t.identity(),
  transfersUsed: __t.i32(),
  lastTransferAt: __t.timestamp(),
});
export type CharacterTransferCredit = __Infer<typeof CharacterTransferCredit>;

export const CharacterTransferTicket = __t.object("CharacterTransferTicket", {
  id: __t.u64(),
  accountId: __t.identity(),
  nonce: __t.string(),
  characterName: __t.string(),
  characterTag: __t.i32(),
  characterLevel: __t.i32(),
  payload: __t.string(),
  signature: __t.string(),
  createdAt: __t.timestamp(),
});
export type CharacterTransferTicket = __Infer<typeof CharacterTransferTicket>;

export const CharacterTravelSample = __t.object("CharacterTravelSample", {
  characterId: __t.u64(),
  instanceId: __t.u32(),
  anchorX: __t.f32(),
  anchorZ: __t.f32(),
});
export type CharacterTravelSample = __Infer<typeof CharacterTravelSample>;

export const CharacterWeeklyActivityRow = __t.object("CharacterWeeklyActivityRow", {
  id: __t.u64(),
  characterId: __t.u64(),
  weekNumber: __t.i32(),
  points: __t.i32(),
  tasksCompleted: __t.i32(),
  dailiesCompleted: __t.i32(),
  breachClears: __t.i32(),
  bestBreachMapId: __t.string(),
  bestBreachLevel: __t.i32(),
  highestInstability: __t.u32(),
  isClaimed: __t.bool(),
  claimedAtUnix: __t.i64(),
});
export type CharacterWeeklyActivityRow = __Infer<typeof CharacterWeeklyActivityRow>;

export const CombatLogEvent = __t.object("CombatLogEvent", {
  id: __t.u64(),
  characterId: __t.u64(),
  spellId: __t.i32(),
  amount: __t.f32(),
  entityId: __t.i32(),
  isCrit: __t.bool(),
  isMiss: __t.bool(),
  chunkX: __t.i32(),
  chunkZ: __t.i32(),
  instanceId: __t.u32(),
  sourceKind: __t.u8(),
  sourceEntityId: __t.u32(),
  targetCharacterId: __t.u64(),
  targetKind: __t.u8(),
  sourceEnemyId: __t.u32(),
  targetEnemyId: __t.u32(),
  outcome: __t.u8(),
  isPeriodic: __t.bool(),
});
export type CombatLogEvent = __Infer<typeof CombatLogEvent>;

export const ConnectionDiagnostic = __t.object("ConnectionDiagnostic", {
  connectionKey: __t.string(),
  accountId: __t.identity(),
  connectedAt: __t.timestamp(),
  lastHeartbeatAt: __t.timestamp(),
  heartbeatCount: __t.u64(),
  lastHeartbeatSequence: __t.u64(),
  clientVersion: __t.i32(),
});
export type ConnectionDiagnostic = __Infer<typeof ConnectionDiagnostic>;

export const ConsumableEffect = __t.object("ConsumableEffect", {
  id: __t.i32(),
  itemId: __t.i32(),
  effectKind: __t.i32(),
  statId: __t.i32(),
  amount: __t.f32(),
  durationSeconds: __t.f32(),
  tickIntervalSeconds: __t.f32(),
  sortOrder: __t.i32(),
});
export type ConsumableEffect = __Infer<typeof ConsumableEffect>;

export const ConsumableItem = __t.object("ConsumableItem", {
  itemId: __t.i32(),
  effectType: __t.i32(),
  effectAmount: __t.f32(),
  effectDurationSeconds: __t.f32(),
  effectTickIntervalSeconds: __t.f32(),
  levelRequirement: __t.i32(),
});
export type ConsumableItem = __Infer<typeof ConsumableItem>;

export const ConsumedTransferNonce = __t.object("ConsumedTransferNonce", {
  nonce: __t.string(),
  accountId: __t.identity(),
  characterId: __t.u64(),
  claimedAt: __t.timestamp(),
});
export type ConsumedTransferNonce = __Infer<typeof ConsumedTransferNonce>;

export const CookingDish = __t.object("CookingDish", {
  id: __t.i32(),
  affinity: __t.i32(),
  tier: __t.i32(),
  itemId: __t.i32(),
  requiredCookingSkill: __t.i32(),
  cookSeconds: __t.f32(),
  skillXp: __t.i32(),
});
export type CookingDish = __Infer<typeof CookingDish>;

export const CookingFire = __t.object("CookingFire", {
  characterId: __t.u64(),
  get position() {
    return DbVector3;
  },
  instanceId: __t.u32(),
  chunkX: __t.i32(),
  chunkZ: __t.i32(),
  litFromX: __t.f32(),
  litFromY: __t.f32(),
  litFromZ: __t.f32(),
  expiresAtUnix: __t.i64(),
});
export type CookingFire = __Infer<typeof CookingFire>;

export const CookingIngredient = __t.object("CookingIngredient", {
  itemId: __t.i32(),
  affinity: __t.i32(),
  potency: __t.i32(),
  note: __t.string(),
});
export type CookingIngredient = __Infer<typeof CookingIngredient>;

export const CookingSession = __t.object("CookingSession", {
  characterId: __t.u64(),
  instanceId: __t.u32(),
  startedX: __t.f32(),
  startedY: __t.f32(),
  startedZ: __t.f32(),
  ingredient1ItemId: __t.i32(),
  ingredient2ItemId: __t.i32(),
  ingredient3ItemId: __t.i32(),
  resultItemId: __t.i32(),
  startedAtUnix: __t.i64(),
  completesAtUnix: __t.i64(),
  expiresAtUnix: __t.i64(),
});
export type CookingSession = __Infer<typeof CookingSession>;

export const CreatureLore = __t.object("CreatureLore", {
  enemyId: __t.u32(),
  text: __t.string(),
});
export type CreatureLore = __Infer<typeof CreatureLore>;

export const DbVector3 = __t.object("DbVector3", {
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
});
export type DbVector3 = __Infer<typeof DbVector3>;

export const DefenseXpGuard = __t.object("DefenseXpGuard", {
  characterId: __t.u64(),
  nextXpAtUnix: __t.i64(),
});
export type DefenseXpGuard = __Infer<typeof DefenseXpGuard>;

export const Enemy = __t.object("Enemy", {
  id: __t.u32(),
  name: __t.string(),
  level: __t.i32(),
  xpReward: __t.i32(),
  moveSpeed: __t.f32(),
  isAggressive: __t.bool(),
  maxHealth: __t.i32(),
  attackDamage: __t.i32(),
  respawnSeconds: __t.i32(),
  aggroRange: __t.f32(),
  maxDistanceFromSpawn: __t.f32(),
  modelPath: __t.string(),
  deathSoundPath: __t.string(),
  wanderRadius: __t.f32(),
  scale: __t.f32(),
  attackSoundPath: __t.string(),
  isBipedal: __t.bool(),
});
export type Enemy = __Infer<typeof Enemy>;

export const EnemyAbilityCooldown = __t.object("EnemyAbilityCooldown", {
  enemyEntityId: __t.u32(),
  readyAtUnix: __t.array(__t.i64()),
});
export type EnemyAbilityCooldown = __Infer<typeof EnemyAbilityCooldown>;

export const EnemyGroundAttack = __t.object("EnemyGroundAttack", {
  id: __t.u64(),
  enemyEntityId: __t.u32(),
  instanceId: __t.u32(),
  chunkX: __t.i32(),
  chunkZ: __t.i32(),
  get position() {
    return DbVector3;
  },
  directionX: __t.f32(),
  directionZ: __t.f32(),
  radius: __t.f32(),
  halfAngle: __t.f32(),
  startedAtUnix: __t.i64(),
  activatesAtUnix: __t.i64(),
  expiresAtUnix: __t.i64(),
  tickIntervalMs: __t.i32(),
  power: __t.f32(),
  spellId: __t.u64(),
});
export type EnemyGroundAttack = __Infer<typeof EnemyGroundAttack>;

export const EnemyGroundAttackSchedule = __t.object("EnemyGroundAttackSchedule", {
  id: __t.u64(),
  enemyEntityId: __t.u32(),
  scheduledAt: __t.scheduleAt(),
  previousPulseUnix: __t.i64(),
});
export type EnemyGroundAttackSchedule = __Infer<typeof EnemyGroundAttackSchedule>;

export const EnemyGroundAttackState = __t.object("EnemyGroundAttackState", {
  enemyEntityId: __t.u32(),
  readyAtUnix: __t.i64(),
  sequence: __t.u32(),
});
export type EnemyGroundAttackState = __Infer<typeof EnemyGroundAttackState>;

export const EnemyLootDrop = __t.object("EnemyLootDrop", {
  id: __t.i32(),
  enemyId: __t.i32(),
  itemId: __t.i32(),
  quantity: __t.i32(),
  get position() {
    return DbVector3;
  },
  chunkX: __t.i32(),
  chunkZ: __t.i32(),
  characterId: __t.u64(),
  goldAmount: __t.i32(),
  qualityLevel: __t.i32(),
  instanceId: __t.u32(),
  copperAmount: __t.i32(),
  instabilityTier: __t.i32(),
  sourceEnemyId: __t.u32(),
});
export type EnemyLootDrop = __Infer<typeof EnemyLootDrop>;

export const EnemyMotionState = __t.object("EnemyMotionState", {
  enemyEntityId: __t.u32(),
  velocityX: __t.f32(),
  velocityZ: __t.f32(),
});
export type EnemyMotionState = __Infer<typeof EnemyMotionState>;

export const EnemyNavigationState = __t.object("EnemyNavigationState", {
  enemyEntityId: __t.u32(),
  mode: __t.u8(),
  targetCharacterId: __t.u64(),
  goalX: __t.f32(),
  goalY: __t.f32(),
  goalZ: __t.f32(),
  waypointX: __t.f32(),
  waypointY: __t.f32(),
  waypointZ: __t.f32(),
  hasWaypoint: __t.bool(),
  replanAfterUnix: __t.i64(),
  revision: __t.u32(),
  pathX: __t.array(__t.f32()),
  pathY: __t.array(__t.f32()),
  pathZ: __t.array(__t.f32()),
  pathCursor: __t.i32(),
});
export type EnemyNavigationState = __Infer<typeof EnemyNavigationState>;

export const EnemySimulationState = __t.object("EnemySimulationState", {
  id: __t.u8(),
  schedulerVersion: __t.i32(),
});
export type EnemySimulationState = __Infer<typeof EnemySimulationState>;

export const EnemySlowState = __t.object("EnemySlowState", {
  enemyEntityId: __t.u32(),
  dueBucket: __t.i64(),
});
export type EnemySlowState = __Infer<typeof EnemySlowState>;

export const Entity = __t.object("Entity", {
  id: __t.u32(),
  entityTypeId: __t.u8(),
  entityDataId: __t.u32(),
  get spawnPosition() {
    return DbVector3;
  },
  get position() {
    return DbVector3;
  },
  rotation: __t.f32(),
  health: __t.i32(),
  chunkX: __t.i32(),
  chunkZ: __t.i32(),
  targets: __t.array(__t.u64()),
  isAlive: __t.bool(),
  respawnAtUnix: __t.i64(),
  isAttacking: __t.bool(),
  isReturningToSpawn: __t.bool(),
  targetX: __t.f32(),
  targetZ: __t.f32(),
  nextMoveTimeUnix: __t.i64(),
  targetCharacterId: __t.option(__t.u64()),
  nextAttackTimeUnix: __t.i64(),
  lastUpdateUnix: __t.i64(),
  lastWanderUnix: __t.i64(),
  instanceId: __t.u32(),
  maxHealth: __t.i32(),
  motionSequence: __t.u64(),
  motionMode: __t.u8(),
  pathRevision: __t.u32(),
  teleportSequence: __t.u32(),
  velocityX: __t.f32(),
  velocityY: __t.f32(),
  velocityZ: __t.f32(),
});
export type Entity = __Infer<typeof Entity>;

export const EquipmentItem = __t.object("EquipmentItem", {
  itemId: __t.i32(),
  levelRequirement: __t.i32(),
  requiredClass: __t.i32(),
  quality: __t.i32(),
  damage: __t.f32(),
  armor: __t.f32(),
  vitality: __t.i32(),
  fortitude: __t.i32(),
  strength: __t.i32(),
  grace: __t.i32(),
  alacrity: __t.i32(),
  tempo: __t.i32(),
  slot: __t.string(),
  weaponHand: __t.string(),
});
export type EquipmentItem = __Infer<typeof EquipmentItem>;

export const FastTickTimer = __t.object("FastTickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type FastTickTimer = __Infer<typeof FastTickTimer>;

export const FishingCatch = __t.object("FishingCatch", {
  itemId: __t.i32(),
  zone: __t.string(),
  minFishingLevel: __t.i32(),
  weight: __t.i32(),
  rarity: __t.i32(),
  skillXp: __t.i32(),
});
export type FishingCatch = __Infer<typeof FishingCatch>;

export const FishingSession = __t.object("FishingSession", {
  characterId: __t.u64(),
  instanceId: __t.u32(),
  startedX: __t.f32(),
  startedY: __t.f32(),
  startedZ: __t.f32(),
  spotX: __t.f32(),
  spotZ: __t.f32(),
  catchItemId: __t.i32(),
  rarity: __t.i32(),
  castAtUnix: __t.i64(),
  biteAtUnix: __t.i64(),
  hookedAtUnix: __t.i64(),
  earliestLandAtUnix: __t.i64(),
  expiresAtUnix: __t.i64(),
  fishWeightTenths: __t.i32(),
});
export type FishingSession = __Infer<typeof FishingSession>;

export const GameEvent = __t.object("GameEvent", {
  id: __t.i32(),
  fromNpcId: __t.option(__t.i32()),
  fromCharId: __t.option(__t.u64()),
  toNpcId: __t.option(__t.i32()),
  toCharId: __t.option(__t.u64()),
  action: __t.string(),
  amount: __t.option(__t.f32()),
  isMiss: __t.bool(),
  timestamp: __t.timestamp(),
  duration: __t.option(__t.f32()),
  chunkX: __t.i32(),
  chunkZ: __t.i32(),
  deliveryType: __t.i32(),
  phase: __t.i32(),
  groundX: __t.f32(),
  groundZ: __t.f32(),
  instanceId: __t.u32(),
  fishWeightTenths: __t.i32(),
  isNewBestCatch: __t.bool(),
});
export type GameEvent = __Infer<typeof GameEvent>;

export const Guild = __t.object("Guild", {
  id: __t.u64(),
  name: __t.string(),
  nameKey: __t.string(),
  ownerCharacterId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Guild = __Infer<typeof Guild>;

export const GuildInvite = __t.object("GuildInvite", {
  id: __t.u64(),
  guildId: __t.u64(),
  inviterCharacterId: __t.u64(),
  targetCharacterId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type GuildInvite = __Infer<typeof GuildInvite>;

export const GuildMember = __t.object("GuildMember", {
  characterId: __t.u64(),
  guildId: __t.u64(),
  characterName: __t.string(),
  characterTag: __t.i32(),
  joinedAt: __t.timestamp(),
});
export type GuildMember = __Infer<typeof GuildMember>;

export const GuildMessageEvent = __t.object("GuildMessageEvent", {
  guildId: __t.u64(),
  characterId: __t.u64(),
  text: __t.string(),
  sent: __t.timestamp(),
});
export type GuildMessageEvent = __Infer<typeof GuildMessageEvent>;

export const HealingXpGuard = __t.object("HealingXpGuard", {
  characterId: __t.u64(),
  nextXpAtUnix: __t.i64(),
});
export type HealingXpGuard = __Infer<typeof HealingXpGuard>;

export const InstanceExpirySchedule = __t.object("InstanceExpirySchedule", {
  scheduledId: __t.u64(),
  instanceId: __t.u32(),
  scheduledAt: __t.scheduleAt(),
});
export type InstanceExpirySchedule = __Infer<typeof InstanceExpirySchedule>;

export const ItemDefinition = __t.object("ItemDefinition", {
  id: __t.i32(),
  name: __t.string(),
  description: __t.string(),
  itemType: __t.i32(),
  itemSubType: __t.i32(),
  iconTexture: __t.string(),
  modelPath: __t.option(__t.string()),
  maxStackSize: __t.i32(),
  sellPrice: __t.i32(),
});
export type ItemDefinition = __Infer<typeof ItemDefinition>;

export const ItemInstance = __t.object("ItemInstance", {
  id: __t.i32(),
  itemId: __t.i32(),
  quantity: __t.i32(),
  characterId: __t.u64(),
  qualityLevel: __t.i32(),
  isTradable: __t.bool(),
  instabilityTier: __t.i32(),
});
export type ItemInstance = __Infer<typeof ItemInstance>;

export const ItemSocket = __t.object("ItemSocket", {
  id: __t.i32(),
  itemInstanceId: __t.i32(),
  characterId: __t.u64(),
  socketIndex: __t.i32(),
  augmentItemInstanceId: __t.i32(),
});
export type ItemSocket = __Infer<typeof ItemSocket>;

export const ItemUpgrade = __t.object("ItemUpgrade", {
  itemInstanceId: __t.i32(),
  characterId: __t.u64(),
  upgradeLevel: __t.i32(),
});
export type ItemUpgrade = __Infer<typeof ItemUpgrade>;

export const LevelRequirement = __t.object("LevelRequirement", {
  level: __t.i32(),
  xpRequired: __t.u64(),
});
export type LevelRequirement = __Infer<typeof LevelRequirement>;

export const LootTableEntry = __t.object("LootTableEntry", {
  id: __t.i32(),
  enemyId: __t.u32(),
  lootTableName: __t.string(),
  itemId: __t.i32(),
  dropChancePercent: __t.f32(),
  minQuantity: __t.i32(),
  maxQuantity: __t.i32(),
  rolls: __t.i32(),
});
export type LootTableEntry = __Infer<typeof LootTableEntry>;

export const MapFogRepackSchedule = __t.object("MapFogRepackSchedule", {
  scheduledId: __t.u64(),
  migratedCells: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MapFogRepackSchedule = __Infer<typeof MapFogRepackSchedule>;

export const Merchant = __t.object("Merchant", {
  npcId: __t.u32(),
  name: __t.string(),
});
export type Merchant = __Infer<typeof Merchant>;

export const MerchantStockEntry = __t.object("MerchantStockEntry", {
  id: __t.i32(),
  npcId: __t.u32(),
  itemId: __t.i32(),
  price: __t.i32(),
});
export type MerchantStockEntry = __Infer<typeof MerchantStockEntry>;

export const MessageEvent = __t.object("MessageEvent", {
  characterId: __t.u64(),
  sent: __t.timestamp(),
  text: __t.string(),
  recipientCharacterId: __t.u64(),
  partyId: __t.u64(),
});
export type MessageEvent = __Infer<typeof MessageEvent>;

export const Npc = __t.object("Npc", {
  id: __t.u32(),
  name: __t.string(),
  level: __t.i32(),
  modelPath: __t.string(),
  scale: __t.f32(),
  greetingText: __t.string(),
  sexSelection: __t.i32(),
  hairStyleSelection: __t.i32(),
  hairColorSelection: __t.i32(),
  role: __t.string(),
});
export type Npc = __Infer<typeof Npc>;

export const NpcEquipment = __t.object("NpcEquipment", {
  npcId: __t.u32(),
  headItemId: __t.i32(),
  backItemId: __t.i32(),
  shoulderItemId: __t.i32(),
  mainHandItemId: __t.i32(),
  offHandItemId: __t.i32(),
  chestItemId: __t.i32(),
  waistItemId: __t.i32(),
  legsItemId: __t.i32(),
  handsItemId: __t.i32(),
  feetItemId: __t.i32(),
});
export type NpcEquipment = __Infer<typeof NpcEquipment>;

export const NpcTopic = __t.object("NpcTopic", {
  id: __t.u32(),
  npcId: __t.u32(),
  topic: __t.string(),
  text: __t.string(),
  requiredQuestComplete: __t.i32(),
  sortOrder: __t.i32(),
});
export type NpcTopic = __Infer<typeof NpcTopic>;

export const ObservedEnemyEntity = __t.object("ObservedEnemyEntity", {
  enemyEntityId: __t.u32(),
  navigationRecoveryDeadlineUnix: __t.i64(),
  navigationRecoveryAnchorX: __t.f32(),
  navigationRecoveryAnchorZ: __t.f32(),
  navigationRecoveryGoalX: __t.f32(),
  navigationRecoveryGoalZ: __t.f32(),
});
export type ObservedEnemyEntity = __Infer<typeof ObservedEnemyEntity>;

export const Party = __t.object("Party", {
  id: __t.u64(),
  leaderCharacterId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Party = __Infer<typeof Party>;

export const PartyInvite = __t.object("PartyInvite", {
  id: __t.u64(),
  inviterCharacterId: __t.u64(),
  targetCharacterId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type PartyInvite = __Infer<typeof PartyInvite>;

export const PartyMember = __t.object("PartyMember", {
  characterId: __t.u64(),
  joinedAt: __t.timestamp(),
  partyId: __t.u64(),
});
export type PartyMember = __Infer<typeof PartyMember>;

export const PendingMiningAction = __t.object("PendingMiningAction", {
  characterId: __t.u64(),
  worldObjectEntityId: __t.u32(),
  startedX: __t.f32(),
  startedY: __t.f32(),
  startedZ: __t.f32(),
  instanceId: __t.u32(),
  completesAtUnix: __t.i64(),
  durationSeconds: __t.f32(),
});
export type PendingMiningAction = __Infer<typeof PendingMiningAction>;

export const PendingProjectileImpact = __t.object("PendingProjectileImpact", {
  id: __t.u64(),
  characterId: __t.u64(),
  spellId: __t.u64(),
  targetEntityId: __t.i32(),
  impactsAtUnix: __t.i64(),
  procId: __t.i32(),
});
export type PendingProjectileImpact = __Infer<typeof PendingProjectileImpact>;

export const PendingSpellCast = __t.object("PendingSpellCast", {
  characterId: __t.u64(),
  spellId: __t.u64(),
  action: __t.string(),
  targetEntityId: __t.option(__t.i32()),
  targetCharacterId: __t.option(__t.u64()),
  startedX: __t.f32(),
  startedZ: __t.f32(),
  completesAtUnix: __t.i64(),
  deliveryType: __t.i32(),
});
export type PendingSpellCast = __Infer<typeof PendingSpellCast>;

export const ProcDefinition = __t.object("ProcDefinition", {
  id: __t.i32(),
  classId: __t.i32(),
  name: __t.string(),
  description: __t.string(),
  iconTexture: __t.string(),
  chancePercent: __t.f32(),
  durationSeconds: __t.f32(),
  powerBonusPercent: __t.f32(),
});
export type ProcDefinition = __Infer<typeof ProcDefinition>;

export const Quest = __t.object("Quest", {
  id: __t.i32(),
  name: __t.string(),
  pickupNpcId: __t.option(__t.u32()),
  dropOffNpcId: __t.option(__t.u32()),
  pickupItemName: __t.option(__t.string()),
  description: __t.string(),
  xpReward: __t.u64(),
  levelRequired: __t.i32(),
  questRequired: __t.i32(),
  shortDescription: __t.string(),
  taskAmount: __t.i32(),
  objectiveType: __t.i32(),
  get objectives() {
    return __t.array(QuestObjective);
  },
  rewardAllItems: __t.bool(),
  questRewardItems: __t.array(__t.i32()),
});
export type Quest = __Infer<typeof Quest>;

export const QuestCompletionText = __t.object("QuestCompletionText", {
  questId: __t.i32(),
  text: __t.string(),
});
export type QuestCompletionText = __Infer<typeof QuestCompletionText>;

export const QuestObjective = __t.object("QuestObjective", {
  objectiveType: __t.i32(),
  objectiveTargetIds: __t.array(__t.u32()),
  requiredAmount: __t.i32(),
  description: __t.string(),
});
export type QuestObjective = __Infer<typeof QuestObjective>;

export const QuestObjectiveProgress = __t.object("QuestObjectiveProgress", {
  objectiveType: __t.i32(),
  objectiveTargetIds: __t.array(__t.u32()),
  currentAmount: __t.i32(),
  requiredAmount: __t.i32(),
  isComplete: __t.bool(),
  description: __t.string(),
});
export type QuestObjectiveProgress = __Infer<typeof QuestObjectiveProgress>;

export const QuestProgress = __t.object("QuestProgress", {
  id: __t.u64(),
  characterId: __t.u64(),
  questId: __t.i32(),
  currentAmount: __t.i32(),
  requiredAmount: __t.i32(),
  get objectiveProgresses() {
    return __t.array(QuestObjectiveProgress);
  },
  isComplete: __t.bool(),
  isActive: __t.bool(),
  startedAt: __t.timestamp(),
  completedAt: __t.timestamp(),
});
export type QuestProgress = __Infer<typeof QuestProgress>;

export const QuestTargetEntity = __t.object("QuestTargetEntity", {
  entityId: __t.u32(),
  entityTypeId: __t.u8(),
  entityDataId: __t.u32(),
  get position() {
    return DbVector3;
  },
  isAlive: __t.bool(),
});
export type QuestTargetEntity = __Infer<typeof QuestTargetEntity>;

export const RefinementCost = __t.object("RefinementCost", {
  id: __t.i32(),
  materialTier: __t.i32(),
  refinementLevel: __t.i32(),
  materialItemId: __t.i32(),
  materialQuantity: __t.i32(),
  copperCost: __t.i32(),
});
export type RefinementCost = __Infer<typeof RefinementCost>;

export const ServerRealmConfig = __t.object("ServerRealmConfig", {
  id: __t.i32(),
  timeZoneId: __t.string(),
});
export type ServerRealmConfig = __Infer<typeof ServerRealmConfig>;

export const ServerSettings = __t.object("ServerSettings", {
  minReqGameVersion: __t.i32(),
  maxConcurrentPlayers: __t.i32(),
});
export type ServerSettings = __Infer<typeof ServerSettings>;

export const ServiceRankRow = __t.object("ServiceRankRow", {
  rank: __t.i32(),
  threshold: __t.i32(),
  title: __t.string(),
  rewardItemId: __t.i32(),
});
export type ServiceRankRow = __Infer<typeof ServiceRankRow>;

export const SkillDefinition = __t.object("SkillDefinition", {
  id: __t.i32(),
  name: __t.string(),
  description: __t.string(),
  iconTexture: __t.string(),
  maxLevel: __t.i32(),
  xpPerLevel: __t.i32(),
});
export type SkillDefinition = __Infer<typeof SkillDefinition>;

export const SocketUnlockCost = __t.object("SocketUnlockCost", {
  socketIndex: __t.i32(),
  materialItemId: __t.i32(),
  materialQuantity: __t.i32(),
  copperCost: __t.i32(),
});
export type SocketUnlockCost = __Infer<typeof SocketUnlockCost>;

export const Spell = __t.object("Spell", {
  id: __t.u64(),
  name: __t.string(),
  description: __t.string(),
  iconTexture: __t.string(),
  castTime: __t.f32(),
  cooldown: __t.f32(),
  minRange: __t.f32(),
  maxRange: __t.f32(),
  resourceGenerated: __t.i32(),
  resourceCost: __t.i32(),
  damage: __t.f32(),
  classRequired: __t.i32(),
  levelRequired: __t.i32(),
  isInstant: __t.bool(),
  activeEffectType: __t.i32(),
  activeEffectIsBuff: __t.bool(),
  activeEffectIsDurationless: __t.bool(),
  activeEffectTarget: __t.i32(),
  activeEffectDuration: __t.f32(),
  activeEffectTickInterval: __t.f32(),
  activeEffectAmount: __t.f32(),
  deliveryType: __t.i32(),
  projectileSpeed: __t.f32(),
  impactDelaySeconds: __t.f32(),
  areaFollowMode: __t.i32(),
  procTriggerId: __t.i32(),
  procConsumerId: __t.i32(),
  activeEffectIsStackable: __t.bool(),
});
export type Spell = __Infer<typeof Spell>;

export const SpellButtonBinding = __t.object("SpellButtonBinding", {
  id: __t.u64(),
  spellId: __t.u64(),
  buttonIndex: __t.i32(),
  characterId: __t.u64(),
});
export type SpellButtonBinding = __Infer<typeof SpellButtonBinding>;

export const StarterGearEntry = __t.object("StarterGearEntry", {
  id: __t.i32(),
  classId: __t.i32(),
  itemId: __t.i32(),
});
export type StarterGearEntry = __Infer<typeof StarterGearEntry>;

export const StatDefinition = __t.object("StatDefinition", {
  id: __t.i32(),
  key: __t.string(),
  name: __t.string(),
  description: __t.string(),
});
export type StatDefinition = __Infer<typeof StatDefinition>;

export const TalentNode = __t.object("TalentNode", {
  id: __t.i32(),
  classId: __t.i32(),
  row: __t.i32(),
  column: __t.i32(),
  nodeType: __t.i32(),
  spellId: __t.u64(),
  statType: __t.i32(),
  statAmountPerRank: __t.i32(),
  maxRank: __t.i32(),
  levelRequired: __t.i32(),
  choiceGroup: __t.i32(),
  requiredNodeId: __t.i32(),
  requiredGroupId: __t.i32(),
  isEnabled: __t.bool(),
  isFreeUnlock: __t.bool(),
  name: __t.string(),
  description: __t.string(),
  iconTexture: __t.string(),
});
export type TalentNode = __Infer<typeof TalentNode>;

export const TalentNodeState = __t.object("TalentNodeState", {
  id: __t.string(),
  characterId: __t.u64(),
  nodeId: __t.i32(),
  rank: __t.i32(),
  state: __t.i32(),
});
export type TalentNodeState = __Infer<typeof TalentNodeState>;

export const TalentPointsState = __t.object("TalentPointsState", {
  characterId: __t.u64(),
  spellPointsEarned: __t.i32(),
  spellPointsSpent: __t.i32(),
  attributePointsEarned: __t.i32(),
  attributePointsSpent: __t.i32(),
});
export type TalentPointsState = __Infer<typeof TalentPointsState>;

export const TickState = __t.object("TickState", {
  id: __t.i32(),
  lastProcessedBucket: __t.i64(),
  lastAreaEffectProcessUnix: __t.i64(),
  lastEnemyMovementBucket: __t.i64(),
});
export type TickState = __Infer<typeof TickState>;

export const TickTimer = __t.object("TickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickTimer = __Infer<typeof TickTimer>;

export const TradeOfferSlot = __t.object("TradeOfferSlot", {
  id: __t.u64(),
  tradeId: __t.u64(),
  characterId: __t.u64(),
  slotIndex: __t.i32(),
  itemInstanceId: __t.i32(),
  itemId: __t.i32(),
  quantity: __t.i32(),
  qualityLevel: __t.i32(),
  instabilityTier: __t.i32(),
});
export type TradeOfferSlot = __Infer<typeof TradeOfferSlot>;

export const TradeSession = __t.object("TradeSession", {
  id: __t.u64(),
  initiatorCharacterId: __t.u64(),
  targetCharacterId: __t.u64(),
  initiatorAccepted: __t.bool(),
  targetAccepted: __t.bool(),
  initiatorOfferedCopper: __t.i64(),
  targetOfferedCopper: __t.i64(),
  createdAt: __t.timestamp(),
});
export type TradeSession = __Infer<typeof TradeSession>;

export const TransferTicketSummary = __t.object("TransferTicketSummary", {
  id: __t.u64(),
  nonce: __t.string(),
  characterName: __t.string(),
  characterTag: __t.i32(),
  characterLevel: __t.i32(),
  payload: __t.string(),
  signature: __t.string(),
  createdAt: __t.timestamp(),
});
export type TransferTicketSummary = __Infer<typeof TransferTicketSummary>;

export const WeatherClockState = __t.object("WeatherClockState", {
  id: __t.u8(),
  nowUnixMs: __t.i64(),
});
export type WeatherClockState = __Infer<typeof WeatherClockState>;

export const WorldInstance = __t.object("WorldInstance", {
  id: __t.u32(),
  mapId: __t.string(),
  partyId: __t.u64(),
  ownerCharacterId: __t.u64(),
  createdAt: __t.timestamp(),
  instability: __t.u32(),
  isCompleted: __t.bool(),
});
export type WorldInstance = __Infer<typeof WorldInstance>;

export const WorldObject = __t.object("WorldObject", {
  id: __t.u32(),
  name: __t.string(),
  lootTableName: __t.string(),
  respawnSeconds: __t.i32(),
  modelPath: __t.string(),
  scale: __t.f32(),
  requireQuestForInteraction: __t.bool(),
  gatheringSkillId: __t.i32(),
  requiredSkillLevel: __t.i32(),
  tintHex: __t.string(),
  gatherDurationSeconds: __t.f32(),
});
export type WorldObject = __Infer<typeof WorldObject>;

export const WorldObjectCooldown = __t.object("WorldObjectCooldown", {
  worldObjectEntityId: __t.u32(),
  dueBucket: __t.i64(),
});
export type WorldObjectCooldown = __Infer<typeof WorldObjectCooldown>;

export const WorldTime = __t.object("WorldTime", {
  id: __t.i32(),
  inGameMinuteOfDay: __t.i32(),
  day: __t.i32(),
  updatedAtUnix: __t.i64(),
});
export type WorldTime = __Infer<typeof WorldTime>;

export const ZoneWeatherConfig = __t.object("ZoneWeatherConfig", {
  zone: __t.string(),
  clearMinSeconds: __t.u32(),
  clearMaxSeconds: __t.u32(),
  rainMinSeconds: __t.u32(),
  rainMaxSeconds: __t.u32(),
  fadeSeconds: __t.u32(),
});
export type ZoneWeatherConfig = __Infer<typeof ZoneWeatherConfig>;

export const ZoneWeatherSchedule = __t.object("ZoneWeatherSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  zone: __t.string(),
});
export type ZoneWeatherSchedule = __Infer<typeof ZoneWeatherSchedule>;

export const ZoneWeatherState = __t.object("ZoneWeatherState", {
  zone: __t.string(),
  raining: __t.bool(),
  startedAtUnixMs: __t.i64(),
  endsAtUnixMs: __t.i64(),
  fadeSeconds: __t.u32(),
  randomState: __t.u64(),
  wetnessAtStart: __t.f32(),
});
export type ZoneWeatherState = __Infer<typeof ZoneWeatherState>;

