// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ActiveEffect = __t.object("ActiveEffect", {
  id: __t.u64(),
  spellId: __t.u64(),
  sourceCharacterId: __t.u64(),
  targetCharacterId: __t.u64(),
  targetEntityId: __t.u32(),
  targetType: __t.u8(),
  effectType: __t.i32(),
  isBuff: __t.bool(),
  appliedAtUnix: __t.i64(),
  expiresAtUnix: __t.i64(),
  nextTickAtUnix: __t.i64(),
  tickIntervalMs: __t.i32(),
  amount: __t.f32(),
});
export type ActiveEffect = __Infer<typeof ActiveEffect>;

export const ActiveEnemyEntity = __t.object("ActiveEnemyEntity", {
  enemyEntityId: __t.u32(),
});
export type ActiveEnemyEntity = __Infer<typeof ActiveEnemyEntity>;

export const AreaEffect = __t.object("AreaEffect", {
  id: __t.u64(),
  spellId: __t.u64(),
  sourceCharacterId: __t.u64(),
  get position() {
    return DbVector3;
  },
  radius: __t.f32(),
  appliedAtUnix: __t.i64(),
  expiresAtUnix: __t.i64(),
  effectType: __t.i32(),
  isBuff: __t.bool(),
  amount: __t.f32(),
});
export type AreaEffect = __Infer<typeof AreaEffect>;

export const AreaEffectTarget = __t.object("AreaEffectTarget", {
  id: __t.u64(),
  areaEffectId: __t.u64(),
  targetCharacterId: __t.u64(),
  activeEffectId: __t.u64(),
});
export type AreaEffectTarget = __Infer<typeof AreaEffectTarget>;

export const AuthSession = __t.object("AuthSession", {
  accountId: __t.identity(),
  loginMethod: __t.string(),
  providerId: __t.string(),
  preferredUsername: __t.string(),
  picture: __t.string(),
  isSteam: __t.bool(),
  ownsConfiguredSteamApp: __t.bool(),
  connectedAt: __t.timestamp(),
  isQueued: __t.bool(),
  queuePosition: __t.i32(),
});
export type AuthSession = __Infer<typeof AuthSession>;

export const Bag = __t.object("Bag", {
  id: __t.i32(),
  name: __t.string(),
  characterId: __t.u64(),
  size: __t.i32(),
});
export type Bag = __Infer<typeof Bag>;

export const BagSlot = __t.object("BagSlot", {
  id: __t.i32(),
  bagId: __t.i32(),
  itemInstanceId: __t.i32(),
  characterId: __t.u64(),
});
export type BagSlot = __Infer<typeof BagSlot>;

export const ChangelogEntry = __t.object("ChangelogEntry", {
  id: __t.u32(),
  description: __t.string(),
  date: __t.string(),
});
export type ChangelogEntry = __Infer<typeof ChangelogEntry>;

export const Character = __t.object("Character", {
  id: __t.u64(),
  accountId: __t.identity(),
  name: __t.string(),
  raceSelection: __t.i32(),
  sexSelection: __t.i32(),
  classSelection: __t.i32(),
  createdAt: __t.timestamp(),
  deletedAt: __t.timestamp(),
  lastPlayed: __t.timestamp(),
  tag: __t.i32(),
});
export type Character = __Infer<typeof Character>;

export const CharacterClass = __t.object("CharacterClass", {
  id: __t.i32(),
  name: __t.string(),
  maxHealth: __t.i32(),
  maxEnergy: __t.i32(),
  starterWeaponItemId: __t.i32(),
});
export type CharacterClass = __Infer<typeof CharacterClass>;

export const CharacterCurrency = __t.object("CharacterCurrency", {
  characterId: __t.u64(),
  gold: __t.i32(),
});
export type CharacterCurrency = __Infer<typeof CharacterCurrency>;

export const CharacterEquipment = __t.object("CharacterEquipment", {
  characterId: __t.u64(),
  headSlotItemInstanceId: __t.i32(),
  neckSlotItemInstanceId: __t.i32(),
  backSlotItemInstanceId: __t.i32(),
  shoulderSlotItemInstanceId: __t.i32(),
  chestSlotItemInstanceId: __t.i32(),
  waistSlotItemInstanceId: __t.i32(),
  legSlotItemInstanceId: __t.i32(),
  footSlotItemInstanceId: __t.i32(),
  mainHandSlotItemInstanceId: __t.i32(),
  offHandSlotItemInstanceId: __t.i32(),
});
export type CharacterEquipment = __Infer<typeof CharacterEquipment>;

export const CharacterMapFog = __t.object("CharacterMapFog", {
  id: __t.u64(),
  characterId: __t.u64(),
  zoneName: __t.string(),
  cellX: __t.i32(),
  cellY: __t.i32(),
  discoveredAt: __t.timestamp(),
});
export type CharacterMapFog = __Infer<typeof CharacterMapFog>;

export const CharacterQuest = __t.object("CharacterQuest", {
  get questData() {
    return __t.option(Quest);
  },
  get progress() {
    return __t.option(QuestProgress);
  },
});
export type CharacterQuest = __Infer<typeof CharacterQuest>;

export const CharacterState = __t.object("CharacterState", {
  characterId: __t.u64(),
  get position() {
    return DbVector3;
  },
  chunkX: __t.i32(),
  chunkZ: __t.i32(),
  rotation: __t.f64(),
  isWeaponDrawn: __t.bool(),
});
export type CharacterState = __Infer<typeof CharacterState>;

export const CharacterStats = __t.object("CharacterStats", {
  characterId: __t.u64(),
  level: __t.i32(),
  xp: __t.u64(),
  health: __t.i32(),
  maxHealth: __t.i32(),
  energy: __t.i32(),
  maxEnergy: __t.i32(),
  vitality: __t.i32(),
  fortitude: __t.i32(),
  strength: __t.i32(),
  grace: __t.i32(),
  alacrity: __t.i32(),
  tempo: __t.i32(),
});
export type CharacterStats = __Infer<typeof CharacterStats>;

export const CharacterSummary = __t.object("CharacterSummary", {
  id: __t.u64(),
  accountId: __t.identity(),
  name: __t.string(),
  raceSelection: __t.i32(),
  sexSelection: __t.i32(),
  classSelection: __t.i32(),
  get position() {
    return DbVector3;
  },
  chunkX: __t.i32(),
  chunkZ: __t.i32(),
  rotation: __t.f64(),
  level: __t.i32(),
  xp: __t.u64(),
  health: __t.i32(),
  maxHealth: __t.i32(),
  energy: __t.i32(),
  maxEnergy: __t.i32(),
  vitality: __t.i32(),
  fortitude: __t.i32(),
  strength: __t.i32(),
  grace: __t.i32(),
  alacrity: __t.i32(),
  tempo: __t.i32(),
  createdAt: __t.timestamp(),
  deletedAt: __t.timestamp(),
  lastPlayed: __t.timestamp(),
  isWeaponDrawn: __t.bool(),
  tag: __t.i32(),
  gold: __t.i32(),
});
export type CharacterSummary = __Infer<typeof CharacterSummary>;

export const CombatLogEvent = __t.object("CombatLogEvent", {
  characterId: __t.u64(),
  spellId: __t.i32(),
  amount: __t.f32(),
  entityId: __t.i32(),
  isCrit: __t.bool(),
  chunkX: __t.i32(),
  chunkZ: __t.i32(),
});
export type CombatLogEvent = __Infer<typeof CombatLogEvent>;

export const DbVector3 = __t.object("DbVector3", {
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
});
export type DbVector3 = __Infer<typeof DbVector3>;

export const Enemy = __t.object("Enemy", {
  id: __t.u32(),
  name: __t.string(),
  level: __t.i32(),
  xpReward: __t.i32(),
  moveSpeed: __t.f32(),
  isAggressive: __t.bool(),
  maxHealth: __t.i32(),
  attackDamage: __t.i32(),
  respawnSeconds: __t.i32(),
  aggroRange: __t.f32(),
  maxDistanceFromSpawn: __t.f32(),
  modelPath: __t.string(),
  deathSoundPath: __t.string(),
  wanderRadius: __t.f32(),
  scale: __t.f32(),
  attackSoundPath: __t.string(),
});
export type Enemy = __Infer<typeof Enemy>;

export const EnemyLootDrop = __t.object("EnemyLootDrop", {
  id: __t.i32(),
  enemyId: __t.i32(),
  itemId: __t.i32(),
  quantity: __t.i32(),
  get position() {
    return DbVector3;
  },
  chunkX: __t.i32(),
  chunkZ: __t.i32(),
  characterId: __t.u64(),
  goldAmount: __t.i32(),
  qualityLevel: __t.i32(),
});
export type EnemyLootDrop = __Infer<typeof EnemyLootDrop>;

export const EnemySlowState = __t.object("EnemySlowState", {
  enemyEntityId: __t.u32(),
  dueBucket: __t.i64(),
});
export type EnemySlowState = __Infer<typeof EnemySlowState>;

export const Entity = __t.object("Entity", {
  id: __t.u32(),
  entityTypeId: __t.u8(),
  entityDataId: __t.u32(),
  get spawnPosition() {
    return DbVector3;
  },
  get position() {
    return DbVector3;
  },
  rotation: __t.f32(),
  health: __t.i32(),
  chunkX: __t.i32(),
  chunkZ: __t.i32(),
  targets: __t.array(__t.u64()),
  isAlive: __t.bool(),
  respawnAtUnix: __t.i64(),
  isAttacking: __t.bool(),
  isReturningToSpawn: __t.bool(),
  targetX: __t.f32(),
  targetZ: __t.f32(),
  nextMoveTimeUnix: __t.i64(),
  targetCharacterId: __t.option(__t.u64()),
  nextAttackTimeUnix: __t.i64(),
  lastUpdateUnix: __t.i64(),
  lastWanderUnix: __t.i64(),
});
export type Entity = __Infer<typeof Entity>;

export const FastTickTimer = __t.object("FastTickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type FastTickTimer = __Infer<typeof FastTickTimer>;

export const GameEvent = __t.object("GameEvent", {
  id: __t.i32(),
  fromNpcId: __t.option(__t.i32()),
  fromCharId: __t.option(__t.u64()),
  toNpcId: __t.option(__t.i32()),
  toCharId: __t.option(__t.u64()),
  action: __t.string(),
  amount: __t.option(__t.f32()),
  timestamp: __t.timestamp(),
  duration: __t.option(__t.f32()),
  chunkX: __t.i32(),
  chunkZ: __t.i32(),
});
export type GameEvent = __Infer<typeof GameEvent>;

export const Item = __t.object("Item", {
  id: __t.i32(),
  name: __t.string(),
  description: __t.string(),
  itemType: __t.i32(),
  itemSubType: __t.i32(),
  iconTexture: __t.string(),
  modelPath: __t.option(__t.string()),
  maxStackSize: __t.i32(),
  levelRequirement: __t.i32(),
  requiredClass: __t.i32(),
  quality: __t.i32(),
  sellPrice: __t.i32(),
  damage: __t.f32(),
  armor: __t.f32(),
  vitality: __t.i32(),
  fortitude: __t.i32(),
  strength: __t.i32(),
  grace: __t.i32(),
  alacrity: __t.i32(),
  tempo: __t.i32(),
  slot: __t.option(__t.string()),
});
export type Item = __Infer<typeof Item>;

export const ItemInstance = __t.object("ItemInstance", {
  id: __t.i32(),
  itemId: __t.i32(),
  quantity: __t.i32(),
  characterId: __t.u64(),
  qualityLevel: __t.i32(),
});
export type ItemInstance = __Infer<typeof ItemInstance>;

export const LevelRequirement = __t.object("LevelRequirement", {
  level: __t.i32(),
  xpRequired: __t.u64(),
});
export type LevelRequirement = __Infer<typeof LevelRequirement>;

export const LootTableEntry = __t.object("LootTableEntry", {
  id: __t.i32(),
  enemyId: __t.u32(),
  lootTableName: __t.string(),
  itemId: __t.i32(),
  dropChancePercent: __t.f32(),
  minQuantity: __t.i32(),
  maxQuantity: __t.i32(),
  rolls: __t.i32(),
});
export type LootTableEntry = __Infer<typeof LootTableEntry>;

export const MessageEvent = __t.object("MessageEvent", {
  characterId: __t.u64(),
  sent: __t.timestamp(),
  text: __t.string(),
  recipientCharacterId: __t.u64(),
  partyId: __t.u64(),
});
export type MessageEvent = __Infer<typeof MessageEvent>;

export const Npc = __t.object("Npc", {
  id: __t.u32(),
  name: __t.string(),
  level: __t.i32(),
  modelPath: __t.string(),
  scale: __t.f32(),
  greetingText: __t.string(),
});
export type Npc = __Infer<typeof Npc>;

export const Party = __t.object("Party", {
  id: __t.u64(),
  leaderCharacterId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Party = __Infer<typeof Party>;

export const PartyInvite = __t.object("PartyInvite", {
  id: __t.u64(),
  inviterCharacterId: __t.u64(),
  targetCharacterId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type PartyInvite = __Infer<typeof PartyInvite>;

export const PartyMember = __t.object("PartyMember", {
  characterId: __t.u64(),
  joinedAt: __t.timestamp(),
  partyId: __t.u64(),
});
export type PartyMember = __Infer<typeof PartyMember>;

export const PendingProjectileImpact = __t.object("PendingProjectileImpact", {
  id: __t.u64(),
  characterId: __t.u64(),
  spellId: __t.u64(),
  targetEntityId: __t.i32(),
  impactsAtUnix: __t.i64(),
});
export type PendingProjectileImpact = __Infer<typeof PendingProjectileImpact>;

export const PendingSpellCast = __t.object("PendingSpellCast", {
  characterId: __t.u64(),
  spellId: __t.u64(),
  action: __t.string(),
  targetEntityId: __t.option(__t.i32()),
  targetCharacterId: __t.option(__t.u64()),
  startedX: __t.f32(),
  startedZ: __t.f32(),
  completesAtUnix: __t.i64(),
});
export type PendingSpellCast = __Infer<typeof PendingSpellCast>;

export const Quest = __t.object("Quest", {
  id: __t.i32(),
  name: __t.string(),
  pickupNpcId: __t.option(__t.u32()),
  dropOffNpcId: __t.option(__t.u32()),
  pickupItemName: __t.option(__t.string()),
  description: __t.string(),
  xpReward: __t.u64(),
  levelRequired: __t.i32(),
  questRequired: __t.i32(),
  shortDescription: __t.string(),
  taskAmount: __t.i32(),
  objectiveType: __t.i32(),
  get objectives() {
    return __t.array(QuestObjective);
  },
  rewardAllItems: __t.bool(),
  questRewardItems: __t.array(__t.i32()),
});
export type Quest = __Infer<typeof Quest>;

export const QuestObjective = __t.object("QuestObjective", {
  objectiveType: __t.i32(),
  objectiveTargetIds: __t.array(__t.u32()),
  requiredAmount: __t.i32(),
  description: __t.string(),
});
export type QuestObjective = __Infer<typeof QuestObjective>;

export const QuestObjectiveProgress = __t.object("QuestObjectiveProgress", {
  objectiveType: __t.i32(),
  objectiveTargetIds: __t.array(__t.u32()),
  currentAmount: __t.i32(),
  requiredAmount: __t.i32(),
  isComplete: __t.bool(),
  description: __t.string(),
});
export type QuestObjectiveProgress = __Infer<typeof QuestObjectiveProgress>;

export const QuestProgress = __t.object("QuestProgress", {
  id: __t.u64(),
  characterId: __t.u64(),
  questId: __t.i32(),
  currentAmount: __t.i32(),
  requiredAmount: __t.i32(),
  get objectiveProgresses() {
    return __t.array(QuestObjectiveProgress);
  },
  isComplete: __t.bool(),
  isActive: __t.bool(),
  startedAt: __t.timestamp(),
  completedAt: __t.timestamp(),
});
export type QuestProgress = __Infer<typeof QuestProgress>;

export const ServerSettings = __t.object("ServerSettings", {
  minReqGameVersion: __t.i32(),
  maxConcurrentPlayers: __t.i32(),
});
export type ServerSettings = __Infer<typeof ServerSettings>;

export const Spell = __t.object("Spell", {
  id: __t.u64(),
  name: __t.string(),
  description: __t.string(),
  iconTexture: __t.string(),
  castTime: __t.f32(),
  cooldown: __t.f32(),
  minRange: __t.f32(),
  maxRange: __t.f32(),
  resourceGenerated: __t.i32(),
  resourceCost: __t.i32(),
  damage: __t.f32(),
  classRequired: __t.i32(),
  levelRequired: __t.i32(),
  isInstant: __t.bool(),
  activeEffectType: __t.i32(),
  activeEffectIsBuff: __t.bool(),
  activeEffectIsDurationless: __t.bool(),
  activeEffectTarget: __t.i32(),
  activeEffectDuration: __t.f32(),
  activeEffectTickInterval: __t.f32(),
  activeEffectAmount: __t.f32(),
});
export type Spell = __Infer<typeof Spell>;

export const SpellButtonBinding = __t.object("SpellButtonBinding", {
  id: __t.u64(),
  spellId: __t.u64(),
  buttonIndex: __t.i32(),
  characterId: __t.u64(),
});
export type SpellButtonBinding = __Infer<typeof SpellButtonBinding>;

export const StatDefinition = __t.object("StatDefinition", {
  id: __t.i32(),
  key: __t.string(),
  name: __t.string(),
  description: __t.string(),
});
export type StatDefinition = __Infer<typeof StatDefinition>;

export const TickState = __t.object("TickState", {
  id: __t.i32(),
  lastProcessedBucket: __t.i64(),
  lastAreaEffectProcessUnix: __t.i64(),
});
export type TickState = __Infer<typeof TickState>;

export const TickTimer = __t.object("TickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickTimer = __Infer<typeof TickTimer>;

export const WorldObject = __t.object("WorldObject", {
  id: __t.u32(),
  name: __t.string(),
  lootTableName: __t.string(),
  respawnSeconds: __t.i32(),
  modelPath: __t.string(),
  scale: __t.f32(),
  requireQuestForInteraction: __t.bool(),
});
export type WorldObject = __Infer<typeof WorldObject>;

export const WorldObjectCooldown = __t.object("WorldObjectCooldown", {
  worldObjectEntityId: __t.u32(),
  dueBucket: __t.i64(),
});
export type WorldObjectCooldown = __Infer<typeof WorldObjectCooldown>;

export const WorldTime = __t.object("WorldTime", {
  id: __t.i32(),
  inGameMinuteOfDay: __t.i32(),
  day: __t.i32(),
  updatedAtUnix: __t.i64(),
});
export type WorldTime = __Infer<typeof WorldTime>;

