// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  QuestObjective,
} from "./types";

export default {
  id: __t.i32(),
  name: __t.string(),
  pickupNpcId: __t.u32(),
  dropOffNpcId: __t.u32(),
  pickupItemName: __t.string(),
  description: __t.string(),
  xpReward: __t.u64(),
  levelRequired: __t.i32(),
  questRequired: __t.i32(),
  shortDescription: __t.string(),
  taskAmount: __t.i32(),
  objectiveType: __t.i32(),
  get objectives() {
    return __t.array(QuestObjective);
  },
  rewardAllItems: __t.bool(),
  questRewardItems: __t.array(__t.i32()),
  targetId: __t.string(),
};
