// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.i32(),
  name: __t.string(),
  description: __t.string(),
  itemType: __t.i32(),
  itemSubType: __t.i32(),
  iconTexture: __t.string(),
  modelPath: __t.string(),
  maxStackSize: __t.i32(),
  levelRequirement: __t.i32(),
  requiredClass: __t.i32(),
  quality: __t.i32(),
  sellPrice: __t.i32(),
  damage: __t.f32(),
  armor: __t.f32(),
  slot: __t.string(),
  targetId: __t.string(),
};
