// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  name: __t.string(),
  lootTableName: __t.string().name("loot_table_name"),
  respawnSeconds: __t.i32().name("respawn_seconds"),
  modelPath: __t.string().name("model_path"),
  scale: __t.f32(),
  requireQuestForInteraction: __t.bool().name("require_quest_for_interaction"),
});
