// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  zone: __t.string().primaryKey(),
  raining: __t.bool(),
  startedAtUnixMs: __t.i64().name("started_at_unix_ms"),
  endsAtUnixMs: __t.i64().name("ends_at_unix_ms"),
  fadeSeconds: __t.u32().name("fade_seconds"),
  randomState: __t.u64().name("random_state"),
  wetnessAtStart: __t.f32().name("wetness_at_start"),
});
