// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  zone: __t.string().primaryKey(),
  clearMinSeconds: __t.u32().name("clear_min_seconds"),
  clearMaxSeconds: __t.u32().name("clear_max_seconds"),
  rainMinSeconds: __t.u32().name("rain_min_seconds"),
  rainMaxSeconds: __t.u32().name("rain_max_seconds"),
  fadeSeconds: __t.u32().name("fade_seconds"),
});
